/**
 * EPR Selector - Ensemble Pass Rate based Fix Selection
 *
 * Implements research-based fix selection using generated test ensembles
 * to validate and rank fix candidates. EPR measures the fraction of
 * generated tests that pass with a given fix applied.
 *
 * Research basis: Ensemble methods for program repair validation
 *
 * Features implemented:
 * - Feature #42: FixCandidate interface
 * - Feature #43: EPRSelector class
 * - Feature #44: generateTestEnsemble()
 * - Feature #45: calculateEPR()
 * - Feature #46: selectFix()
 * - Feature #47: rankByEPR()
 *
 * @packageDocumentation
 */

import type { Language, SourceLocation } from './types.js';

// =============================================================================
// Feature #42: FixCandidate Interface
// =============================================================================

/**
 * Fix candidate with code changes and test results
 */
export interface FixCandidate {
  /** Unique identifier for this fix candidate */
  id: string;

  /** The code change to apply */
  code: CodeChange;

  /** Tests that passed with this fix applied */
  passedTests: TestResult[];

  /** Tests that failed with this fix applied */
  failedTests: TestResult[];

  /** Ensemble Pass Rate (0-1 range) */
  epr: number;

  /** Additional metadata about the fix */
  metadata: FixMetadata;
}

/**
 * Code change representing a fix
 */
export interface CodeChange {
  /** File path to modify */
  filePath: string;

  /** Original code before fix */
  originalCode: string;

  /** Fixed code after applying the fix */
  fixedCode: string;

  /** Location of the change */
  location: SourceLocation;

  /** Type of change */
  changeType: ChangeType;

  /** Human-readable description of the fix */
  description: string;
}

export type ChangeType =
  | 'replace'
  | 'insert'
  | 'delete'
  | 'modify_condition'
  | 'add_null_check'
  | 'fix_type'
  | 'fix_import'
  | 'refactor';

/**
 * Test result from running a test case
 */
export interface TestResult {
  /** Test identifier */
  testId: string;

  /** Test name */
  name: string;

  /** Whether the test passed */
  passed: boolean;

  /** Execution time in milliseconds */
  executionTime: number;

  /** Error message if test failed */
  error?: string;

  /** Stack trace if test failed */
  stackTrace?: string;

  /** Test category for diversity tracking */
  category: TestCategory;

  /** Assertions made by the test */
  assertions: Assertion[];
}

export type TestCategory =
  | 'positive'      // Tests expected behavior
  | 'negative'      // Tests error handling
  | 'boundary'      // Tests edge cases
  | 'regression'    // Tests previously fixed bugs
  | 'mutation'      // Tests generated by mutation
  | 'fuzz'          // Tests generated by fuzzing
  | 'property';     // Property-based tests

/**
 * Assertion made by a test
 */
export interface Assertion {
  /** Type of assertion */
  type: AssertionType;

  /** Expected value */
  expected: unknown;

  /** Actual value */
  actual: unknown;

  /** Whether assertion passed */
  passed: boolean;

  /** Human-readable message */
  message: string;
}

export type AssertionType =
  | 'equals'
  | 'not_equals'
  | 'throws'
  | 'not_throws'
  | 'truthy'
  | 'falsy'
  | 'contains'
  | 'matches'
  | 'type_of'
  | 'instance_of';

/**
 * Metadata about a fix candidate
 */
export interface FixMetadata {
  /** Source of the fix (e.g., 'llm', 'template', 'historical') */
  source: FixSource;

  /** Confidence score from the generator (0-1) */
  generatorConfidence: number;

  /** Time to generate the fix */
  generationTime: number;

  /** Model or template used */
  generator: string;

  /** Tags for categorization */
  tags: string[];

  /** Related bug report ID if applicable */
  bugReportId?: string;

  /** Git diff format of the change */
  diff?: string;
}

export type FixSource =
  | 'llm'
  | 'template'
  | 'historical'
  | 'mutation'
  | 'search'
  | 'hybrid';

// =============================================================================
// Test Ensemble Types (Feature #44)
// =============================================================================

/**
 * Configuration for test ensemble generation
 */
export interface TestEnsembleConfig {
  /** Target number of tests in the ensemble */
  ensembleSize: number;

  /** Distribution of test categories */
  categoryDistribution: CategoryDistribution;

  /** Minimum diversity score (0-1) */
  minDiversity: number;

  /** Maximum time for test generation (ms) */
  maxGenerationTime: number;

  /** Language of the code under test */
  language: Language;

  /** Test framework to use */
  framework: TestFramework;

  /** Whether to include fuzzing */
  includeFuzzing: boolean;

  /** Whether to include property-based tests */
  includePropertyTests: boolean;
}

/**
 * Distribution of test categories in ensemble
 */
export interface CategoryDistribution {
  positive: number;    // e.g., 0.3 = 30% positive tests
  negative: number;    // e.g., 0.2 = 20% negative tests
  boundary: number;    // e.g., 0.2 = 20% boundary tests
  regression: number;  // e.g., 0.1 = 10% regression tests
  mutation: number;    // e.g., 0.1 = 10% mutation tests
  fuzz: number;        // e.g., 0.05 = 5% fuzz tests
  property: number;    // e.g., 0.05 = 5% property tests
}

export type TestFramework =
  | 'jest'
  | 'mocha'
  | 'vitest'
  | 'pytest'
  | 'unittest'
  | 'go_test'
  | 'junit'
  | 'rspec';

/**
 * Generated test ensemble
 */
export interface TestEnsemble {
  /** Unique identifier */
  id: string;

  /** Tests in the ensemble */
  tests: GeneratedTest[];

  /** Bug description this ensemble validates */
  bugDescription: string;

  /** Diversity score (0-1) */
  diversityScore: number;

  /** Coverage information */
  coverage: CoverageInfo;

  /** Generation statistics */
  stats: EnsembleStats;
}

/**
 * A generated test case
 */
export interface GeneratedTest {
  /** Unique identifier */
  id: string;

  /** Test name */
  name: string;

  /** Test code */
  code: string;

  /** Test category */
  category: TestCategory;

  /** Input values for the test */
  inputs: TestInput[];

  /** Expected output */
  expectedOutput: ExpectedOutput;

  /** Generation method used */
  generationMethod: GenerationMethod;

  /** Confidence in test quality (0-1) */
  confidence: number;
}

/**
 * Test input specification
 */
export interface TestInput {
  /** Parameter name */
  name: string;

  /** Input value */
  value: unknown;

  /** Type of the input */
  type: string;

  /** How this input was generated */
  source: InputSource;
}

export type InputSource =
  | 'example'        // From documentation/examples
  | 'boundary'       // Edge case value
  | 'random'         // Random generation
  | 'mutation'       // Mutated from valid input
  | 'symbolic'       // Symbolic execution
  | 'historical';    // From historical test data

/**
 * Expected output specification
 */
export interface ExpectedOutput {
  /** Expected return value */
  returnValue?: unknown;

  /** Expected exception type */
  exceptionType?: string;

  /** Expected side effects */
  sideEffects?: SideEffect[];

  /** Expected state changes */
  stateChanges?: StateChange[];
}

/**
 * Side effect of a function
 */
export interface SideEffect {
  type: 'console' | 'file' | 'network' | 'database' | 'state';
  description: string;
  expected: unknown;
}

/**
 * State change after execution
 */
export interface StateChange {
  target: string;
  before: unknown;
  after: unknown;
}

export type GenerationMethod =
  | 'template'       // Template-based
  | 'llm'            // LLM-generated
  | 'mutation'       // Mutation testing
  | 'symbolic'       // Symbolic execution
  | 'fuzzing'        // Fuzzing
  | 'property';      // Property-based

/**
 * Coverage information for test ensemble
 */
export interface CoverageInfo {
  /** Line coverage percentage */
  lineCoverage: number;

  /** Branch coverage percentage */
  branchCoverage: number;

  /** Function coverage percentage */
  functionCoverage: number;

  /** Uncovered lines */
  uncoveredLines: number[];

  /** Uncovered branches */
  uncoveredBranches: BranchInfo[];
}

/**
 * Branch information
 */
export interface BranchInfo {
  line: number;
  column: number;
  type: 'if' | 'switch' | 'ternary' | 'loop';
  coveredBranches: number;
  totalBranches: number;
}

/**
 * Statistics about test ensemble generation
 */
export interface EnsembleStats {
  /** Total tests generated */
  totalGenerated: number;

  /** Tests kept after filtering */
  testsKept: number;

  /** Tests removed as duplicates */
  duplicatesRemoved: number;

  /** Tests removed as low quality */
  lowQualityRemoved: number;

  /** Generation time (ms) */
  generationTime: number;

  /** Category breakdown */
  categoryBreakdown: Record<TestCategory, number>;
}

// =============================================================================
// EPR Calculation Types (Feature #45)
// =============================================================================

/**
 * EPR calculation result
 */
export interface EPRResult {
  /** Ensemble Pass Rate (0-1) */
  epr: number;

  /** Number of tests passed */
  passedCount: number;

  /** Number of tests failed */
  failedCount: number;

  /** Total tests in ensemble */
  totalTests: number;

  /** Confidence interval for EPR */
  confidenceInterval: ConfidenceInterval;

  /** Breakdown by test category */
  categoryBreakdown: CategoryEPR[];

  /** Detailed test results */
  testResults: TestResult[];
}

/**
 * Confidence interval for EPR estimate
 */
export interface ConfidenceInterval {
  /** Lower bound (e.g., 95% CI) */
  lower: number;

  /** Upper bound */
  upper: number;

  /** Confidence level (e.g., 0.95) */
  level: number;
}

/**
 * EPR breakdown by test category
 */
export interface CategoryEPR {
  category: TestCategory;
  passed: number;
  failed: number;
  epr: number;
}

// =============================================================================
// Fix Selection Types (Feature #46)
// =============================================================================

/**
 * Fix selection configuration
 */
export interface FixSelectionConfig {
  /** Minimum EPR threshold for acceptance */
  eprThreshold: number;

  /** Target precision (0.1 EPR ≈ 0.9 precision) */
  targetPrecision: number;

  /** Maximum fixes to return */
  maxFixes: number;

  /** Whether to require all categories pass */
  requireAllCategories: boolean;

  /** Minimum tests per category */
  minTestsPerCategory: number;

  /** Weight for different categories */
  categoryWeights: Partial<Record<TestCategory, number>>;
}

/**
 * Fix selection result
 */
export interface FixSelectionResult {
  /** Selected fix (if any meets threshold) */
  selectedFix: FixCandidate | null;

  /** All candidates ranked by EPR */
  rankedCandidates: RankedFixCandidate[];

  /** Selection statistics */
  stats: SelectionStats;

  /** Reason for selection or rejection */
  reason: SelectionReason;
}

/**
 * Fix candidate with ranking information
 */
export interface RankedFixCandidate {
  /** The fix candidate */
  fix: FixCandidate;

  /** Rank (1-based) */
  rank: number;

  /** Weighted EPR score */
  weightedEPR: number;

  /** Whether it meets the threshold */
  meetsThreshold: boolean;

  /** Category breakdown */
  categoryResults: CategoryEPR[];
}

/**
 * Statistics about fix selection
 */
export interface SelectionStats {
  /** Total candidates evaluated */
  totalCandidates: number;

  /** Candidates meeting threshold */
  candidatesMeetingThreshold: number;

  /** Average EPR across all candidates */
  averageEPR: number;

  /** Maximum EPR found */
  maxEPR: number;

  /** Minimum EPR found */
  minEPR: number;

  /** Total evaluation time (ms) */
  evaluationTime: number;
}

/**
 * Reason for fix selection or rejection
 */
export interface SelectionReason {
  /** Whether a fix was selected */
  selected: boolean;

  /** Human-readable explanation */
  explanation: string;

  /** Specific criteria met or failed */
  criteria: SelectionCriterion[];
}

/**
 * Individual selection criterion
 */
export interface SelectionCriterion {
  name: string;
  required: boolean;
  met: boolean;
  value: number;
  threshold: number;
}

// =============================================================================
// Feature #43: EPRSelector Class
// =============================================================================

/**
 * EPR Selector configuration
 */
export interface EPRSelectorConfig {
  /** Test ensemble configuration */
  ensembleConfig: Partial<TestEnsembleConfig>;

  /** Fix selection configuration */
  selectionConfig: Partial<FixSelectionConfig>;

  /** Test executor function */
  testExecutor?: TestExecutor;

  /** Test generator function */
  testGenerator?: TestGenerator;

  /** Enable caching of test results */
  enableCaching: boolean;

  /** Cache TTL in milliseconds */
  cacheTTL: number;

  /** Enable parallel test execution */
  parallelExecution: boolean;

  /** Maximum parallel tests */
  maxParallelTests: number;
}

/**
 * Function to execute tests
 */
export type TestExecutor = (
  test: GeneratedTest,
  fixedCode: string,
) => Promise<TestResult>;

/**
 * Function to generate tests
 */
export type TestGenerator = (
  bugDescription: string,
  codeContext: string,
  config: TestEnsembleConfig,
) => Promise<GeneratedTest[]>;

/**
 * Bug context for test generation
 */
export interface BugContext {
  /** Bug description */
  description: string;

  /** Error message */
  errorMessage: string;

  /** Stack trace */
  stackTrace?: string;

  /** Code context */
  codeContext: string;

  /** Function under test */
  functionName: string;

  /** File path */
  filePath: string;

  /** Language */
  language: Language;

  /** Existing tests if any */
  existingTests?: string[];
}

/**
 * EPR Selector for fix validation and ranking
 *
 * Uses Ensemble Pass Rate to validate and rank fix candidates.
 * A low EPR threshold (e.g., 0.1) achieves high precision (≈90%)
 * while accepting more valid fixes.
 */
export class EPRSelector {
  private config: EPRSelectorConfig;
  private ensembleConfig: TestEnsembleConfig;
  private selectionConfig: FixSelectionConfig;
  private cache: Map<string, { result: TestResult; timestamp: number }>;

  constructor(config: Partial<EPRSelectorConfig> = {}) {
    this.config = {
      ensembleConfig: {},
      selectionConfig: {},
      enableCaching: true,
      cacheTTL: 5 * 60 * 1000, // 5 minutes
      parallelExecution: true,
      maxParallelTests: 4,
      ...config,
    };

    this.ensembleConfig = this.getDefaultEnsembleConfig();
    this.selectionConfig = this.getDefaultSelectionConfig();
    this.cache = new Map();
  }

  private getDefaultEnsembleConfig(): TestEnsembleConfig {
    return {
      ensembleSize: 50,
      categoryDistribution: {
        positive: 0.3,
        negative: 0.2,
        boundary: 0.2,
        regression: 0.1,
        mutation: 0.1,
        fuzz: 0.05,
        property: 0.05,
      },
      minDiversity: 0.7,
      maxGenerationTime: 30000,
      language: 'javascript',
      framework: 'jest',
      includeFuzzing: true,
      includePropertyTests: true,
      ...this.config.ensembleConfig,
    };
  }

  private getDefaultSelectionConfig(): FixSelectionConfig {
    return {
      eprThreshold: 0.1,  // 0.1 EPR ≈ 0.9 precision
      targetPrecision: 0.9,
      maxFixes: 10,
      requireAllCategories: false,
      minTestsPerCategory: 2,
      categoryWeights: {
        positive: 1.0,
        negative: 1.0,
        boundary: 1.2,
        regression: 1.5,
        mutation: 1.0,
        fuzz: 0.8,
        property: 1.0,
      },
      ...this.config.selectionConfig,
    };
  }

  // ===========================================================================
  // Feature #44: generateTestEnsemble()
  // ===========================================================================

  /**
   * Generate a diverse test ensemble for validating fixes
   */
  async generateTestEnsemble(bugContext: BugContext): Promise<TestEnsemble> {
    const startTime = Date.now();
    const tests: GeneratedTest[] = [];
    const stats: EnsembleStats = {
      totalGenerated: 0,
      testsKept: 0,
      duplicatesRemoved: 0,
      lowQualityRemoved: 0,
      generationTime: 0,
      categoryBreakdown: {
        positive: 0,
        negative: 0,
        boundary: 0,
        regression: 0,
        mutation: 0,
        fuzz: 0,
        property: 0,
      },
    };

    const config = this.ensembleConfig;
    const targetSize = config.ensembleSize;

    // Generate tests for each category based on distribution
    const categories: TestCategory[] = [
      'positive', 'negative', 'boundary', 'regression',
      'mutation', 'fuzz', 'property',
    ];

    for (const category of categories) {
      const distribution = config.categoryDistribution[category];
      const targetCount = Math.ceil(targetSize * distribution);

      if (targetCount === 0) continue;

      // Skip fuzz/property if not enabled
      if (category === 'fuzz' && !config.includeFuzzing) continue;
      if (category === 'property' && !config.includePropertyTests) continue;

      const categoryTests = await this.generateTestsForCategory(
        bugContext,
        category,
        targetCount,
      );

      stats.totalGenerated += categoryTests.length;

      // Filter duplicates and low-quality tests
      const filtered = this.filterTests(categoryTests, tests);
      stats.duplicatesRemoved += categoryTests.length - filtered.validTests.length - filtered.lowQuality;
      stats.lowQualityRemoved += filtered.lowQuality;

      tests.push(...filtered.validTests);
      stats.categoryBreakdown[category] = filtered.validTests.length;
    }

    stats.testsKept = tests.length;
    stats.generationTime = Date.now() - startTime;

    // Calculate diversity score
    const diversityScore = this.calculateDiversity(tests);

    // Calculate coverage info (mock for now)
    const coverage = this.estimateCoverage(tests, bugContext);

    return {
      id: `ensemble-${Date.now()}`,
      tests,
      bugDescription: bugContext.description,
      diversityScore,
      coverage,
      stats,
    };
  }

  private async generateTestsForCategory(
    bugContext: BugContext,
    category: TestCategory,
    count: number,
  ): Promise<GeneratedTest[]> {
    // Use custom generator if provided
    if (this.config.testGenerator) {
      const generated = await this.config.testGenerator(
        bugContext.description,
        bugContext.codeContext,
        { ...this.ensembleConfig, ensembleSize: count },
      );
      return generated.filter(t => t.category === category).slice(0, count);
    }

    // Default: generate template-based tests
    return this.generateTemplateTests(bugContext, category, count);
  }

  private generateTemplateTests(
    bugContext: BugContext,
    category: TestCategory,
    count: number,
  ): GeneratedTest[] {
    const tests: GeneratedTest[] = [];
    const framework = this.ensembleConfig.framework;

    for (let i = 0; i < count; i++) {
      const test = this.createTestFromTemplate(bugContext, category, i, framework);
      if (test) {
        tests.push(test);
      }
    }

    return tests;
  }

  private createTestFromTemplate(
    bugContext: BugContext,
    category: TestCategory,
    index: number,
    framework: TestFramework,
  ): GeneratedTest | null {
    const { functionName, description: _description } = bugContext;
    const testId = `test-${category}-${index}`;
    const testName = `${functionName} ${category} test ${index + 1}`;

    // Generate inputs based on category
    const inputs = this.generateInputsForCategory(category, bugContext);
    const expectedOutput = this.generateExpectedOutput(category, bugContext);

    // Generate test code based on framework
    const code = this.generateTestCode(
      framework,
      testName,
      functionName,
      inputs,
      expectedOutput,
      category,
    );

    return {
      id: testId,
      name: testName,
      code,
      category,
      inputs,
      expectedOutput,
      generationMethod: 'template',
      confidence: this.estimateTestConfidence(category, inputs),
    };
  }

  private generateInputsForCategory(
    category: TestCategory,
    _context: BugContext,
  ): TestInput[] {
    switch (category) {
      case 'positive':
        return [
          { name: 'input', value: 'validValue', type: 'string', source: 'example' },
        ];
      case 'negative':
        return [
          { name: 'input', value: null, type: 'null', source: 'boundary' },
        ];
      case 'boundary':
        return [
          { name: 'input', value: '', type: 'string', source: 'boundary' },
          { name: 'input', value: 0, type: 'number', source: 'boundary' },
        ];
      case 'fuzz':
        return [
          { name: 'input', value: this.generateFuzzInput(), type: 'unknown', source: 'random' },
        ];
      default:
        return [
          { name: 'input', value: 'test', type: 'string', source: 'example' },
        ];
    }
  }

  private generateFuzzInput(): unknown {
    const types = ['string', 'number', 'boolean', 'array', 'object'];
    const type = types[Math.floor(Math.random() * types.length)];

    switch (type) {
      case 'string':
        return Array.from({ length: 10 }, () =>
          String.fromCharCode(Math.floor(Math.random() * 128))
        ).join('');
      case 'number':
        return Math.random() * 1000000 - 500000;
      case 'boolean':
        return Math.random() > 0.5;
      case 'array':
        return Array.from({ length: 5 }, () => Math.random());
      case 'object':
        return { key: Math.random() };
      default:
        return null;
    }
  }

  private generateExpectedOutput(
    category: TestCategory,
    _context: BugContext,
  ): ExpectedOutput {
    switch (category) {
      case 'negative':
        return { exceptionType: 'Error' };
      case 'positive':
        return { returnValue: true };
      default:
        return {};
    }
  }

  private generateTestCode(
    framework: TestFramework,
    testName: string,
    functionName: string,
    inputs: TestInput[],
    expected: ExpectedOutput,
    _category: TestCategory,
  ): string {
    const inputStr = inputs.map(i => JSON.stringify(i.value)).join(', ');

    switch (framework) {
      case 'jest':
      case 'vitest':
        if (expected.exceptionType) {
          return `test('${testName}', () => {
  expect(() => ${functionName}(${inputStr})).toThrow();
});`;
        }
        return `test('${testName}', () => {
  const result = ${functionName}(${inputStr});
  expect(result).toBeDefined();
});`;

      case 'mocha':
        if (expected.exceptionType) {
          return `it('${testName}', () => {
  assert.throws(() => ${functionName}(${inputStr}));
});`;
        }
        return `it('${testName}', () => {
  const result = ${functionName}(${inputStr});
  assert.isDefined(result);
});`;

      case 'pytest':
        if (expected.exceptionType) {
          return `def test_${testName.replace(/\s+/g, '_')}():
    with pytest.raises(Exception):
        ${functionName}(${inputStr})`;
        }
        return `def test_${testName.replace(/\s+/g, '_')}():
    result = ${functionName}(${inputStr})
    assert result is not None`;

      default:
        return `// Test: ${testName}\n${functionName}(${inputStr});`;
    }
  }

  private estimateTestConfidence(category: TestCategory, inputs: TestInput[]): number {
    let confidence = 0.7; // Base confidence

    // Adjust based on category
    const categoryBonus: Record<TestCategory, number> = {
      positive: 0.1,
      negative: 0.1,
      boundary: 0.15,
      regression: 0.2,
      mutation: 0.05,
      fuzz: -0.1,
      property: 0.1,
    };
    confidence += categoryBonus[category] ?? 0;

    // Adjust based on input source
    for (const input of inputs) {
      if (input.source === 'example' || input.source === 'historical') {
        confidence += 0.05;
      } else if (input.source === 'random') {
        confidence -= 0.05;
      }
    }

    return Math.max(0, Math.min(1, confidence));
  }

  private filterTests(
    newTests: GeneratedTest[],
    existingTests: GeneratedTest[],
  ): { validTests: GeneratedTest[]; lowQuality: number } {
    const validTests: GeneratedTest[] = [];
    let lowQuality = 0;

    const existingCodes = new Set(existingTests.map(t => t.code));

    for (const test of newTests) {
      // Check for duplicates
      if (existingCodes.has(test.code)) {
        continue;
      }

      // Check for low quality
      if (test.confidence < 0.5) {
        lowQuality++;
        continue;
      }

      validTests.push(test);
      existingCodes.add(test.code);
    }

    return { validTests, lowQuality };
  }

  private calculateDiversity(tests: GeneratedTest[]): number {
    if (tests.length === 0) return 0;

    // Calculate category diversity
    const categories = new Set(tests.map(t => t.category));
    const categoryDiversity = categories.size / 7; // 7 possible categories

    // Calculate input diversity
    const inputTypes = new Set(tests.flatMap(t => t.inputs.map(i => i.type)));
    const inputDiversity = Math.min(1, inputTypes.size / 5);

    // Calculate method diversity
    const methods = new Set(tests.map(t => t.generationMethod));
    const methodDiversity = methods.size / 6; // 6 possible methods

    return (categoryDiversity + inputDiversity + methodDiversity) / 3;
  }

  private estimateCoverage(tests: GeneratedTest[], _context: BugContext): CoverageInfo {
    // Estimate coverage based on test categories
    const hasPositive = tests.some(t => t.category === 'positive');
    const hasNegative = tests.some(t => t.category === 'negative');
    const hasBoundary = tests.some(t => t.category === 'boundary');

    let lineCoverage = 0.5;
    let branchCoverage = 0.3;

    if (hasPositive) {
      lineCoverage += 0.2;
      branchCoverage += 0.15;
    }
    if (hasNegative) {
      lineCoverage += 0.15;
      branchCoverage += 0.2;
    }
    if (hasBoundary) {
      lineCoverage += 0.1;
      branchCoverage += 0.2;
    }

    return {
      lineCoverage: Math.min(1, lineCoverage),
      branchCoverage: Math.min(1, branchCoverage),
      functionCoverage: hasPositive ? 1 : 0.5,
      uncoveredLines: [],
      uncoveredBranches: [],
    };
  }

  // ===========================================================================
  // Feature #45: calculateEPR()
  // ===========================================================================

  /**
   * Calculate Ensemble Pass Rate for a fix candidate
   */
  async calculateEPR(
    fix: FixCandidate,
    ensemble: TestEnsemble,
  ): Promise<EPRResult> {
    const testResults: TestResult[] = [];
    const categoryResults: Map<TestCategory, { passed: number; failed: number }> = new Map();

    // Initialize category tracking
    const categories: TestCategory[] = [
      'positive', 'negative', 'boundary', 'regression',
      'mutation', 'fuzz', 'property',
    ];
    for (const cat of categories) {
      categoryResults.set(cat, { passed: 0, failed: 0 });
    }

    // Run tests
    if (this.config.parallelExecution) {
      const batchSize = this.config.maxParallelTests;
      for (let i = 0; i < ensemble.tests.length; i += batchSize) {
        const batch = ensemble.tests.slice(i, i + batchSize);
        const results = await Promise.all(
          batch.map(test => this.runTest(test, fix))
        );
        testResults.push(...results);

        for (const result of results) {
          const catResult = categoryResults.get(result.category)!;
          if (result.passed) {
            catResult.passed++;
          } else {
            catResult.failed++;
          }
        }
      }
    } else {
      for (const test of ensemble.tests) {
        const result = await this.runTest(test, fix);
        testResults.push(result);

        const catResult = categoryResults.get(result.category)!;
        if (result.passed) {
          catResult.passed++;
        } else {
          catResult.failed++;
        }
      }
    }

    // Calculate EPR
    const passedCount = testResults.filter(r => r.passed).length;
    const failedCount = testResults.length - passedCount;
    const epr = testResults.length > 0 ? passedCount / testResults.length : 0;

    // Calculate confidence interval using Wilson score
    const confidenceInterval = this.calculateConfidenceInterval(
      passedCount,
      testResults.length,
      0.95,
    );

    // Build category breakdown
    const categoryBreakdown: CategoryEPR[] = [];
    for (const [category, results] of categoryResults) {
      const total = results.passed + results.failed;
      if (total > 0) {
        categoryBreakdown.push({
          category,
          passed: results.passed,
          failed: results.failed,
          epr: results.passed / total,
        });
      }
    }

    return {
      epr,
      passedCount,
      failedCount,
      totalTests: testResults.length,
      confidenceInterval,
      categoryBreakdown,
      testResults,
    };
  }

  private async runTest(test: GeneratedTest, fix: FixCandidate): Promise<TestResult> {
    // Check cache
    const cacheKey = `${fix.id}-${test.id}`;
    if (this.config.enableCaching) {
      const cached = this.cache.get(cacheKey);
      if (cached && Date.now() - cached.timestamp < this.config.cacheTTL) {
        return cached.result;
      }
    }

    let result: TestResult;

    // Use custom executor if provided
    if (this.config.testExecutor) {
      result = await this.config.testExecutor(test, fix.code.fixedCode);
    } else {
      // Simulate test execution
      result = this.simulateTestExecution(test, fix);
    }

    // Cache result
    if (this.config.enableCaching) {
      this.cache.set(cacheKey, { result, timestamp: Date.now() });
    }

    return result;
  }

  private simulateTestExecution(test: GeneratedTest, fix: FixCandidate): TestResult {
    // Simulate based on test category and fix EPR
    // In real implementation, this would actually run the test
    const basePassRate = fix.epr || 0.8;

    // Adjust pass rate by category
    const categoryMultiplier: Record<TestCategory, number> = {
      positive: 1.0,
      negative: 0.9,
      boundary: 0.85,
      regression: 0.95,
      mutation: 0.8,
      fuzz: 0.7,
      property: 0.85,
    };

    const passRate = basePassRate * (categoryMultiplier[test.category] ?? 0.8);
    const passed = Math.random() < passRate;

    return {
      testId: test.id,
      name: test.name,
      passed,
      executionTime: Math.random() * 100 + 10,
      category: test.category,
      assertions: [{
        type: 'equals',
        expected: true,
        actual: passed,
        passed,
        message: passed ? 'Test passed' : 'Test failed',
      }],
      ...(passed ? {} : {
        error: 'Assertion failed',
        stackTrace: 'at test.js:1:1',
      }),
    };
  }

  private calculateConfidenceInterval(
    successes: number,
    total: number,
    confidence: number,
  ): ConfidenceInterval {
    if (total === 0) {
      return { lower: 0, upper: 1, level: confidence };
    }

    // Wilson score interval
    const z = this.getZScore(confidence);
    const phat = successes / total;
    const n = total;

    const denominator = 1 + z * z / n;
    const center = phat + z * z / (2 * n);
    const margin = z * Math.sqrt((phat * (1 - phat) + z * z / (4 * n)) / n);

    return {
      lower: Math.max(0, (center - margin) / denominator),
      upper: Math.min(1, (center + margin) / denominator),
      level: confidence,
    };
  }

  private getZScore(confidence: number): number {
    // Z-scores for common confidence levels
    const zScores: Record<number, number> = {
      0.90: 1.645,
      0.95: 1.96,
      0.99: 2.576,
    };
    return zScores[confidence] ?? 1.96;
  }

  // ===========================================================================
  // Feature #46: selectFix()
  // ===========================================================================

  /**
   * Select the best fix based on EPR threshold
   */
  async selectFix(
    candidates: FixCandidate[],
    ensemble: TestEnsemble,
  ): Promise<FixSelectionResult> {
    const startTime = Date.now();

    if (candidates.length === 0) {
      return {
        selectedFix: null,
        rankedCandidates: [],
        stats: this.createEmptyStats(startTime),
        reason: {
          selected: false,
          explanation: 'No fix candidates provided',
          criteria: [],
        },
      };
    }

    // Calculate EPR for all candidates
    const rankedCandidates: RankedFixCandidate[] = [];

    for (const fix of candidates) {
      const eprResult = await this.calculateEPR(fix, ensemble);

      // Update fix with calculated EPR
      fix.epr = eprResult.epr;
      fix.passedTests = eprResult.testResults.filter(r => r.passed);
      fix.failedTests = eprResult.testResults.filter(r => !r.passed);

      // Calculate weighted EPR
      const weightedEPR = this.calculateWeightedEPR(eprResult);

      rankedCandidates.push({
        fix,
        rank: 0, // Will be set after sorting
        weightedEPR,
        meetsThreshold: weightedEPR >= this.selectionConfig.eprThreshold,
        categoryResults: eprResult.categoryBreakdown,
      });
    }

    // Sort by weighted EPR (descending)
    rankedCandidates.sort((a, b) => b.weightedEPR - a.weightedEPR);

    // Assign ranks
    for (let i = 0; i < rankedCandidates.length; i++) {
      rankedCandidates[i]!.rank = i + 1;
    }

    // Select the best fix that meets threshold
    const selectedCandidate = rankedCandidates.find(c => c.meetsThreshold);
    const selectedFix = selectedCandidate?.fix ?? null;

    // Calculate stats
    const eprs = rankedCandidates.map(c => c.weightedEPR);
    const stats: SelectionStats = {
      totalCandidates: candidates.length,
      candidatesMeetingThreshold: rankedCandidates.filter(c => c.meetsThreshold).length,
      averageEPR: eprs.reduce((a, b) => a + b, 0) / eprs.length,
      maxEPR: Math.max(...eprs),
      minEPR: Math.min(...eprs),
      evaluationTime: Date.now() - startTime,
    };

    // Build selection reason
    const reason = this.buildSelectionReason(selectedFix, rankedCandidates);

    return {
      selectedFix,
      rankedCandidates: rankedCandidates.slice(0, this.selectionConfig.maxFixes),
      stats,
      reason,
    };
  }

  private calculateWeightedEPR(eprResult: EPRResult): number {
    const weights = this.selectionConfig.categoryWeights;
    let weightedSum = 0;
    let totalWeight = 0;

    for (const catResult of eprResult.categoryBreakdown) {
      const weight = weights[catResult.category] ?? 1.0;
      const count = catResult.passed + catResult.failed;
      weightedSum += catResult.epr * weight * count;
      totalWeight += weight * count;
    }

    return totalWeight > 0 ? weightedSum / totalWeight : eprResult.epr;
  }

  private createEmptyStats(startTime: number): SelectionStats {
    return {
      totalCandidates: 0,
      candidatesMeetingThreshold: 0,
      averageEPR: 0,
      maxEPR: 0,
      minEPR: 0,
      evaluationTime: Date.now() - startTime,
    };
  }

  private buildSelectionReason(
    selectedFix: FixCandidate | null,
    rankedCandidates: RankedFixCandidate[],
  ): SelectionReason {
    const criteria: SelectionCriterion[] = [];

    // EPR threshold criterion
    const bestEPR = rankedCandidates[0]?.weightedEPR ?? 0;
    criteria.push({
      name: 'EPR Threshold',
      required: true,
      met: bestEPR >= this.selectionConfig.eprThreshold,
      value: bestEPR,
      threshold: this.selectionConfig.eprThreshold,
    });

    // Category requirements
    if (this.selectionConfig.requireAllCategories) {
      const bestCandidate = rankedCandidates[0];
      const allCategoriesPassed = bestCandidate
        ? bestCandidate.categoryResults.every(c =>
            c.passed >= this.selectionConfig.minTestsPerCategory
          )
        : false;
      criteria.push({
        name: 'All Categories Pass',
        required: true,
        met: allCategoriesPassed,
        value: allCategoriesPassed ? 1 : 0,
        threshold: 1,
      });
    }

    let explanation: string;
    if (selectedFix) {
      explanation = `Selected fix with EPR ${selectedFix.epr.toFixed(3)} ` +
        `(threshold: ${this.selectionConfig.eprThreshold}). ` +
        `Passed ${selectedFix.passedTests.length}/${selectedFix.passedTests.length + selectedFix.failedTests.length} tests.`;
    } else if (rankedCandidates.length === 0) {
      explanation = 'No fix candidates were provided for evaluation.';
    } else {
      explanation = `No fix met the EPR threshold of ${this.selectionConfig.eprThreshold}. ` +
        `Best candidate had EPR ${bestEPR.toFixed(3)}.`;
    }

    return {
      selected: selectedFix !== null,
      explanation,
      criteria,
    };
  }

  // ===========================================================================
  // Feature #47: rankByEPR()
  // ===========================================================================

  /**
   * Rank fix candidates by their Ensemble Pass Rate
   */
  rankByEPR(candidates: FixCandidate[]): FixCandidate[] {
    // Sort by EPR descending
    return [...candidates].sort((a, b) => b.epr - a.epr);
  }

  /**
   * Rank candidates with detailed information
   */
  async rankByEPRWithDetails(
    candidates: FixCandidate[],
    ensemble: TestEnsemble,
  ): Promise<RankedFixCandidate[]> {
    const ranked: RankedFixCandidate[] = [];

    for (const fix of candidates) {
      const eprResult = await this.calculateEPR(fix, ensemble);

      // Update fix
      fix.epr = eprResult.epr;
      fix.passedTests = eprResult.testResults.filter(r => r.passed);
      fix.failedTests = eprResult.testResults.filter(r => !r.passed);

      const weightedEPR = this.calculateWeightedEPR(eprResult);

      ranked.push({
        fix,
        rank: 0,
        weightedEPR,
        meetsThreshold: weightedEPR >= this.selectionConfig.eprThreshold,
        categoryResults: eprResult.categoryBreakdown,
      });
    }

    // Sort by weighted EPR descending
    ranked.sort((a, b) => b.weightedEPR - a.weightedEPR);

    // Assign ranks
    for (let i = 0; i < ranked.length; i++) {
      ranked[i]!.rank = i + 1;
    }

    return ranked;
  }

  // ===========================================================================
  // Utility Methods
  // ===========================================================================

  /**
   * Clear the test result cache
   */
  clearCache(): void {
    this.cache.clear();
  }

  /**
   * Get cache statistics
   */
  getCacheStats(): { size: number; hitRate: number } {
    return {
      size: this.cache.size,
      hitRate: 0, // Would need to track hits/misses for accurate rate
    };
  }

  /**
   * Update configuration
   */
  updateConfig(config: Partial<EPRSelectorConfig>): void {
    this.config = { ...this.config, ...config };
    if (config.ensembleConfig) {
      this.ensembleConfig = { ...this.ensembleConfig, ...config.ensembleConfig };
    }
    if (config.selectionConfig) {
      this.selectionConfig = { ...this.selectionConfig, ...config.selectionConfig };
    }
  }
}

// =============================================================================
// Factory Functions
// =============================================================================

/**
 * Create an EPR Selector with default configuration
 */
export function createEPRSelector(
  config: Partial<EPRSelectorConfig> = {},
): EPRSelector {
  return new EPRSelector(config);
}

/**
 * Quick EPR calculation for a single fix
 */
export async function calculateFixEPR(
  fix: FixCandidate,
  ensemble: TestEnsemble,
  config?: Partial<EPRSelectorConfig>,
): Promise<EPRResult> {
  const selector = new EPRSelector(config);
  return selector.calculateEPR(fix, ensemble);
}

/**
 * Quick fix selection from candidates
 */
export async function selectBestFix(
  candidates: FixCandidate[],
  ensemble: TestEnsemble,
  config?: Partial<EPRSelectorConfig>,
): Promise<FixSelectionResult> {
  const selector = new EPRSelector(config);
  return selector.selectFix(candidates, ensemble);
}
