/**
 * Theme Export System
 *
 * Production-grade export for Odoo themes using JSZip.
 * Handles ZIP creation, validation, and multiple output formats.
 */

import JSZip from "jszip";
import { validateTheme, formatValidationResult } from "../odoo-skills";
import type { GeneratedFile, ValidationResult } from "../odoo-skills";

// =============================================================================
// TYPES
// =============================================================================

export interface ExportOptions {
  /** Theme module name */
  themeName: string;
  /** Files to include in export */
  files: GeneratedFile[];
  /** Include validation in export */
  validate?: boolean;
  /** Include README */
  includeReadme?: boolean;
  /** Include .gitignore */
  includeGitignore?: boolean;
  /** Author name for manifest */
  author?: string;
  /** Website URL for manifest */
  website?: string;
}

export interface ExportResult {
  /** Success status */
  success: boolean;
  /** ZIP blob for download */
  blob?: Blob;
  /** Validation result if validation was requested */
  validation?: ValidationResult;
  /** Error message if failed */
  error?: string;
  /** Export statistics */
  stats: {
    fileCount: number;
    totalSize: number;
    validationErrors: number;
    validationWarnings: number;
  };
}

// =============================================================================
// README GENERATION
// =============================================================================

/**
 * Generate README.md for the theme
 */
function generateReadme(options: ExportOptions): string {
  return `# ${options.themeName}

An Odoo 18 website theme generated by Platxa Website Studio.

## Installation

1. Copy this module to your Odoo addons directory
2. Update the app list in Odoo: Settings > Apps > Update Apps List
3. Search for "${options.themeName}" and install

## Structure

\`\`\`
${options.themeName}/
├── __manifest__.py          # Module manifest
├── __init__.py              # Python init
├── views/                   # QWeb templates
│   ├── layout.xml
│   ├── pages.xml
│   └── snippets.xml
├── static/
│   └── src/
│       ├── scss/           # Styles
│       │   ├── primary_variables.scss
│       │   ├── bootstrap_overridden.scss
│       │   └── theme.scss
│       └── js/
│           └── theme.js
└── i18n/                   # Translations
    ├── ${options.themeName}.pot
    └── *.po
\`\`\`

## Customization

### Colors
Edit \`static/src/scss/primary_variables.scss\` to change the color palette.

### Typography
Modify the font settings in \`static/src/scss/bootstrap_overridden.scss\`.

### Pages
Add or modify page templates in \`views/pages.xml\`.

### Snippets
Create custom snippets in \`views/snippets.xml\`.

## Requirements

- Odoo 18.0 or later
- Website module installed

## License

LGPL-3

---

Generated by [Platxa Website Studio](https://platxa.com)
`;
}

/**
 * Generate .gitignore for the theme
 */
function generateGitignore(): string {
  return `# Byte-compiled / optimized / DLL files
__pycache__/
*.py[cod]
*$py.class

# C extensions
*.so

# Distribution / packaging
dist/
build/
*.egg-info/

# IDE
.idea/
.vscode/
*.swp
*.swo

# OS
.DS_Store
Thumbs.db

# Logs
*.log

# Compiled SCSS
static/src/css/

# Local development
.env
.env.local
`;
}

// =============================================================================
// MAIN EXPORT FUNCTIONS
// =============================================================================

/**
 * Export theme as a ZIP file using JSZip
 */
export async function exportTheme(options: ExportOptions): Promise<ExportResult> {
  const {
    themeName,
    files,
    validate = true,
    includeReadme = true,
    includeGitignore = true,
  } = options;

  // Validate theme name (must be valid Python module name)
  const validNamePattern = /^[a-z][a-z0-9_]*$/;
  if (!validNamePattern.test(themeName)) {
    return {
      success: false,
      error: `Invalid theme name "${themeName}". Must be a valid Python module name (lowercase letters, numbers, underscores, starting with letter).`,
      stats: {
        fileCount: 0,
        totalSize: 0,
        validationErrors: 1,
        validationWarnings: 0,
      },
    };
  }

  // Validate if requested
  let validation: ValidationResult | undefined;
  if (validate) {
    validation = validateTheme(files);
    if (!validation.valid) {
      console.warn("Theme validation failed:", formatValidationResult(validation));
    }
  }

  try {
    const zip = new JSZip();

    // Create theme folder
    const themeFolder = zip.folder(themeName);
    if (!themeFolder) {
      throw new Error("Failed to create theme folder in ZIP");
    }

    // Add all generated files
    // PRODUCTION-CRITICAL FIX: Handle path prefix mismatch
    // Files may have 'theme_generated/' prefix while themeName is different (e.g., 'theme_custom')
    // This prevents nested structures like theme_custom/theme_generated/...
    let totalSize = 0;
    for (const file of files) {
      let relativePath = file.path;

      // Remove ANY theme_* prefix to get the actual relative path
      // This handles: theme_generated/views/... -> views/...
      //               theme_custom/views/... -> views/...
      //               themeName/views/... -> views/...
      const themePrefix = relativePath.match(/^theme_[a-z0-9_]+\//i);
      if (themePrefix) {
        relativePath = relativePath.substring(themePrefix[0].length);
      } else if (relativePath.startsWith(`${themeName}/`)) {
        relativePath = relativePath.substring(themeName.length + 1);
      }

      // Ensure we don't have double slashes or leading slashes
      relativePath = relativePath.replace(/^\/+/, '').replace(/\/+/g, '/');

      themeFolder.file(relativePath, file.content);
      totalSize += file.content.length;
    }

    // Add README if requested
    if (includeReadme) {
      const readme = generateReadme(options);
      themeFolder.file("README.md", readme);
      totalSize += readme.length;
    }

    // Add .gitignore if requested
    if (includeGitignore) {
      const gitignore = generateGitignore();
      themeFolder.file(".gitignore", gitignore);
      totalSize += gitignore.length;
    }

    // Generate ZIP blob
    const blob = await zip.generateAsync({
      type: "blob",
      compression: "DEFLATE",
      compressionOptions: { level: 6 },
    });

    return {
      success: true,
      blob,
      validation,
      stats: {
        fileCount: files.length + (includeReadme ? 1 : 0) + (includeGitignore ? 1 : 0),
        totalSize,
        validationErrors: validation?.stats.errors || 0,
        validationWarnings: validation?.stats.warnings || 0,
      },
    };
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : "Unknown export error",
      stats: {
        fileCount: 0,
        totalSize: 0,
        validationErrors: validation?.stats.errors || 0,
        validationWarnings: validation?.stats.warnings || 0,
      },
    };
  }
}

/**
 * Export theme files as JSON (for API response)
 */
export function exportAsJson(
  themeName: string,
  files: GeneratedFile[]
): {
  themeName: string;
  files: Array<{ path: string; content: string; type: string }>;
  validation?: ValidationResult;
  exportedAt: string;
  version: string;
} {
  const validation = validateTheme(files);

  return {
    themeName,
    files: files.map((f) => ({
      path: f.path,
      content: f.content,
      type: f.type,
    })),
    validation,
    exportedAt: new Date().toISOString(),
    version: "1.0.0",
  };
}

/**
 * Validate files before export
 */
export function validateBeforeExport(files: GeneratedFile[]): {
  valid: boolean;
  errors: string[];
  warnings: string[];
  canExport: boolean;
  validation: ValidationResult;
  message: string;
} {
  const validation = validateTheme(files);

  // Extract error and warning messages
  const errors = validation.issues
    .filter((i) => i.severity === "error")
    .map((i) => i.message);
  const warnings = validation.issues
    .filter((i) => i.severity === "warning")
    .map((i) => i.message);

  if (validation.stats.errors > 0) {
    return {
      valid: false,
      errors,
      warnings,
      canExport: false,
      validation,
      message: `Cannot export: ${validation.stats.errors} error(s) found. Please fix them first.`,
    };
  }

  if (validation.stats.warnings > 0) {
    return {
      valid: true,
      errors,
      warnings,
      canExport: true,
      validation,
      message: `Export possible with ${validation.stats.warnings} warning(s). Consider reviewing them.`,
    };
  }

  return {
    valid: true,
    errors,
    warnings,
    canExport: true,
    validation,
    message: "All validations passed. Ready to export.",
  };
}

/**
 * Get file extension from type
 */
export function getFileExtension(type: string): string {
  const extensions: Record<string, string> = {
    xml: ".xml",
    py: ".py",
    scss: ".scss",
    css: ".css",
    js: ".js",
    po: ".po",
    pot: ".pot",
    png: ".png",
    svg: ".svg",
  };
  return extensions[type] || "";
}
