/**
 * Playful Theme Template
 *
 * Bright, energetic design with vibrant colors, rounded corners, and fun typography.
 * Perfect for creative brands, kids' products, games, and entertainment websites.
 *
 * Features:
 * - Bright, saturated colors (pinks, yellows, teals)
 * - Large rounded corners and pill shapes
 * - Playful, bouncy animations
 * - Fun, friendly typography
 * - Soft shadows and gradients
 * - Light/dark mode support
 *
 * Feature #63: Theme System - Playful Theme
 */

import type { ThemeTemplate, ColorScheme, Typography, Spacing, LayoutOptions } from "../../theme-registry";

// =============================================================================
// Theme Configuration
// =============================================================================

/** Playful theme color scheme - Light mode */
export const playfulLightColors: ColorScheme = {
  primary: "#FF6B9D",        // Bright pink
  secondary: "#00D4AA",      // Vibrant teal
  background: "#FFFBF5",     // Warm cream
  surface: "#FFFFFF",
  text: "#2D3436",
  textMuted: "#636E72",
  border: "#FFE0CC",
  success: "#00B894",
  warning: "#FDCB6E",
  error: "#FF7675",
};

/** Playful theme color scheme - Dark mode */
export const playfulDarkColors: ColorScheme = {
  primary: "#FF8FB4",        // Softer pink
  secondary: "#2EE5BC",      // Brighter teal
  background: "#1A1625",     // Deep purple-black
  surface: "#2D2640",
  text: "#F8F9FA",
  textMuted: "#B2BEC3",
  border: "#4A4260",
  success: "#55EFC4",
  warning: "#FFEAA7",
  error: "#FF8B8B",
};

/** Playful theme typography */
export const playfulTypography: Typography = {
  headingFont: "'Baloo 2', 'Fredoka One', 'Nunito', system-ui, sans-serif",
  bodyFont: "'Nunito', 'Comic Neue', 'Quicksand', system-ui, sans-serif",
  baseFontSize: "16px",
  lineHeight: "1.6",
  headingWeight: "700",
};

/** Playful theme spacing - generous for breathing room */
export const playfulSpacing: Spacing = {
  sectionPadding: "100px",
  containerWidth: "1140px",
  gap: "24px",
  borderRadius: "24px",  // Extra rounded for playful feel
};

/** Playful theme layout */
export const playfulLayout: LayoutOptions = {
  headerStyle: "sticky",
  navStyle: "horizontal",
  footerColumns: 3,
};

// =============================================================================
// Theme Template Definition
// =============================================================================

/** Playful theme template */
export const playfulTheme: ThemeTemplate = {
  id: "playful-fun",
  name: "Playful Fun",
  description: "Bright colors, rounded corners, and fun typography for an energetic, creative feel. Perfect for kids, games, and entertainment brands.",
  category: "creative",
  tags: ["fun", "colorful", "rounded", "energetic", "creative", "playful", "kids", "entertainment"],
  previewImage: "/themes/playful-fun/preview.png",
  thumbnail: "/themes/playful-fun/thumb.png",
  colors: playfulLightColors,
  typography: playfulTypography,
  spacing: playfulSpacing,
  layout: playfulLayout,
  isPremium: false,
  version: "1.0.0",
  author: "Platxa Studio",
  updatedAt: new Date("2024-02-20"),
  odooVersion: "17.0",
};

// =============================================================================
// SCSS Generation
// =============================================================================

/** Generate playful theme SCSS */
export function generatePlayfulSCSS(darkMode: boolean = false): string {
  const colors = darkMode ? playfulDarkColors : playfulLightColors;
  const accent = "#FFD93D"; // Sunny yellow

  return `
// =============================================================================
// Playful Theme - ${darkMode ? "Dark Mode" : "Light Mode"}
// Generated by Platxa Studio
// =============================================================================

// -----------------------------------------------------------------------------
// Variables
// -----------------------------------------------------------------------------

// Colors
$theme-primary: ${colors.primary};
$theme-secondary: ${colors.secondary};
$theme-accent: ${accent};
$theme-background: ${colors.background};
$theme-surface: ${colors.surface};
$theme-text: ${colors.text};
$theme-text-muted: ${colors.textMuted};
$theme-border: ${colors.border};
$theme-success: ${colors.success};
$theme-warning: ${colors.warning};
$theme-error: ${colors.error};

// Typography
$theme-font-heading: ${playfulTypography.headingFont};
$theme-font-body: ${playfulTypography.bodyFont};
$theme-font-size-base: ${playfulTypography.baseFontSize};
$theme-line-height: ${playfulTypography.lineHeight};
$theme-heading-weight: ${playfulTypography.headingWeight};

// Spacing
$theme-section-padding: ${playfulSpacing.sectionPadding};
$theme-container-width: ${playfulSpacing.containerWidth};
$theme-gap: ${playfulSpacing.gap};
$theme-radius: ${playfulSpacing.borderRadius};
$theme-radius-full: 9999px;

// Transitions - bouncy
$theme-transition: 0.3s cubic-bezier(0.68, -0.55, 0.265, 1.55);
$theme-transition-normal: 0.3s ease;

// Shadows - soft, colorful
$theme-shadow-sm: 0 2px 8px rgba(255, 107, 157, 0.1);
$theme-shadow: 0 4px 12px rgba(255, 107, 157, 0.15);
$theme-shadow-md: 0 6px 20px rgba(255, 107, 157, 0.2);
$theme-shadow-lg: 0 10px 30px rgba(255, 107, 157, 0.25);
$theme-shadow-glow: 0 0 20px rgba(255, 217, 61, 0.5);

// -----------------------------------------------------------------------------
// CSS Custom Properties
// -----------------------------------------------------------------------------

:root {
  --color-primary: #{$theme-primary};
  --color-secondary: #{$theme-secondary};
  --color-accent: #{$theme-accent};
  --color-background: #{$theme-background};
  --color-surface: #{$theme-surface};
  --color-text: #{$theme-text};
  --color-text-muted: #{$theme-text-muted};
  --color-border: #{$theme-border};
  --color-success: #{$theme-success};
  --color-warning: #{$theme-warning};
  --color-error: #{$theme-error};

  --font-heading: #{$theme-font-heading};
  --font-body: #{$theme-font-body};
  --font-size-base: #{$theme-font-size-base};
  --line-height: #{$theme-line-height};

  --section-padding: #{$theme-section-padding};
  --container-width: #{$theme-container-width};
  --gap: #{$theme-gap};
  --radius: #{$theme-radius};
  --radius-full: #{$theme-radius-full};

  --transition: #{$theme-transition};
  --transition-normal: #{$theme-transition-normal};

  --shadow-sm: #{$theme-shadow-sm};
  --shadow: #{$theme-shadow};
  --shadow-md: #{$theme-shadow-md};
  --shadow-lg: #{$theme-shadow-lg};
  --shadow-glow: #{$theme-shadow-glow};
}

// -----------------------------------------------------------------------------
// Reset & Base
// -----------------------------------------------------------------------------

*,
*::before,
*::after {
  box-sizing: border-box;
}

html {
  font-size: $theme-font-size-base;
  scroll-behavior: smooth;
  -webkit-font-smoothing: antialiased;
}

body {
  margin: 0;
  font-family: $theme-font-body;
  font-size: 1rem;
  line-height: $theme-line-height;
  color: $theme-text;
  background-color: $theme-background;
  transition: background-color $theme-transition-normal, color $theme-transition-normal;
}

// -----------------------------------------------------------------------------
// Typography
// -----------------------------------------------------------------------------

h1, h2, h3, h4, h5, h6 {
  margin: 0 0 1.25rem;
  font-family: $theme-font-heading;
  font-weight: $theme-heading-weight;
  line-height: 1.2;
  color: $theme-text;
}

h1 {
  font-size: clamp(2.5rem, 6vw, 4.5rem);
  margin-bottom: 1.5rem;
}

h2 {
  font-size: clamp(2rem, 5vw, 3.5rem);
}

h3 {
  font-size: clamp(1.5rem, 4vw, 2.5rem);
}

h4 {
  font-size: 1.5rem;
}

h5 {
  font-size: 1.25rem;
}

h6 {
  font-size: 1rem;
}

p {
  margin: 0 0 1.25rem;
  color: $theme-text-muted;

  &:last-child {
    margin-bottom: 0;
  }
}

a {
  color: $theme-primary;
  text-decoration: none;
  transition: color $theme-transition-normal;

  &:hover {
    color: $theme-secondary;
  }
}

// -----------------------------------------------------------------------------
// Layout
// -----------------------------------------------------------------------------

.container {
  width: 100%;
  max-width: $theme-container-width;
  margin: 0 auto;
  padding: 0 1.5rem;
}

section,
.section {
  padding: $theme-section-padding 0;

  @media (max-width: 768px) {
    padding: calc(#{$theme-section-padding} / 2) 0;
  }
}

// -----------------------------------------------------------------------------
// Header
// -----------------------------------------------------------------------------

.header {
  position: sticky;
  top: 0;
  z-index: 100;
  padding: 1rem 0;
  background-color: $theme-background;
  border-bottom: 3px solid $theme-border;
  backdrop-filter: blur(8px);

  .header-inner {
    display: flex;
    align-items: center;
    justify-content: space-between;
    gap: 2rem;
  }
}

.logo {
  font-family: $theme-font-heading;
  font-size: 1.5rem;
  font-weight: 800;
  color: $theme-primary;
  text-decoration: none;

  &:hover {
    color: $theme-secondary;
    transform: scale(1.05);
  }
}

.nav {
  display: flex;
  gap: 2rem;

  @media (max-width: 768px) {
    display: none;
  }
}

.nav-link {
  font-family: $theme-font-heading;
  font-size: 1rem;
  font-weight: 600;
  color: $theme-text-muted;
  text-decoration: none;
  transition: color $theme-transition-normal, transform $theme-transition;

  &:hover,
  &.active {
    color: $theme-primary;
    transform: translateY(-2px);
  }
}

// -----------------------------------------------------------------------------
// Hero Section
// -----------------------------------------------------------------------------

.hero {
  min-height: 80vh;
  display: flex;
  align-items: center;
  padding: calc(#{$theme-section-padding} * 1.5) 0;
  text-align: center;

  .hero-content {
    max-width: 900px;
    margin: 0 auto;
  }

  .hero-title {
    margin-bottom: 1.5rem;
    background: linear-gradient(135deg, $theme-primary 0%, $theme-secondary 50%, $theme-accent 100%);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    background-clip: text;
  }

  .hero-subtitle {
    font-size: 1.25rem;
    line-height: 1.7;
    color: $theme-text-muted;
    margin-bottom: 2.5rem;
  }
}

// -----------------------------------------------------------------------------
// Buttons
// -----------------------------------------------------------------------------

.btn {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  gap: 0.5rem;
  padding: 1rem 2rem;
  font-family: $theme-font-heading;
  font-size: 1rem;
  font-weight: 700;
  line-height: 1;
  text-decoration: none;
  border: 3px solid transparent;
  border-radius: $theme-radius-full;
  cursor: pointer;
  transition: all $theme-transition;

  &:disabled {
    opacity: 0.5;
    cursor: not-allowed;
  }
}

.btn-primary {
  color: #ffffff;
  background: linear-gradient(135deg, $theme-primary 0%, darken($theme-primary, 10%) 100%);
  border-color: transparent;
  box-shadow: $theme-shadow-md, 0 4px 0 darken($theme-primary, 15%);

  &:hover:not(:disabled) {
    transform: translateY(-3px);
    box-shadow: $theme-shadow-lg, 0 6px 0 darken($theme-primary, 15%);
  }

  &:active:not(:disabled) {
    transform: translateY(0);
    box-shadow: $theme-shadow-sm, 0 2px 0 darken($theme-primary, 15%);
  }
}

.btn-secondary {
  color: #ffffff;
  background: linear-gradient(135deg, $theme-secondary 0%, darken($theme-secondary, 10%) 100%);
  border-color: transparent;
  box-shadow: $theme-shadow-md, 0 4px 0 darken($theme-secondary, 15%);

  &:hover:not(:disabled) {
    transform: translateY(-3px);
    box-shadow: $theme-shadow-lg, 0 6px 0 darken($theme-secondary, 15%);
  }
}

.btn-outline {
  color: $theme-primary;
  background-color: transparent;
  border-color: $theme-primary;

  &:hover:not(:disabled) {
    background-color: $theme-primary;
    color: #ffffff;
    transform: translateY(-3px);
  }
}

.btn-ghost {
  color: $theme-text-muted;
  background-color: transparent;
  border-color: transparent;

  &:hover:not(:disabled) {
    color: $theme-primary;
    background-color: rgba(255, 107, 157, 0.1);
  }
}

// -----------------------------------------------------------------------------
// Cards
// -----------------------------------------------------------------------------

.card {
  padding: 2rem;
  background-color: $theme-surface;
  border: 3px solid $theme-border;
  border-radius: $theme-radius;
  box-shadow: $theme-shadow;
  transition: all $theme-transition;

  &:hover {
    transform: translateY(-5px) rotate(-1deg);
    box-shadow: $theme-shadow-lg;
    border-color: $theme-primary;
  }
}

.card-title {
  font-size: 1.25rem;
  margin-bottom: 0.75rem;
  color: $theme-text;
}

.card-text {
  font-size: 1rem;
  color: $theme-text-muted;
}

// -----------------------------------------------------------------------------
// Badges
// -----------------------------------------------------------------------------

.badge {
  display: inline-flex;
  align-items: center;
  padding: 0.25rem 0.875rem;
  font-family: $theme-font-heading;
  font-size: 0.75rem;
  font-weight: 700;
  text-transform: uppercase;
  letter-spacing: 0.05em;
  border-radius: $theme-radius-full;
}

.badge-primary {
  background-color: $theme-primary;
  color: #ffffff;
}

.badge-secondary {
  background-color: $theme-secondary;
  color: #ffffff;
}

.badge-accent {
  background-color: $theme-accent;
  color: $theme-text;
}

// -----------------------------------------------------------------------------
// Grid
// -----------------------------------------------------------------------------

.grid {
  display: grid;
  gap: $theme-gap;
}

.grid-2 {
  grid-template-columns: repeat(2, 1fr);

  @media (max-width: 768px) {
    grid-template-columns: 1fr;
  }
}

.grid-3 {
  grid-template-columns: repeat(3, 1fr);

  @media (max-width: 1024px) {
    grid-template-columns: repeat(2, 1fr);
  }

  @media (max-width: 640px) {
    grid-template-columns: 1fr;
  }
}

// -----------------------------------------------------------------------------
// Footer
// -----------------------------------------------------------------------------

.footer {
  padding: 4rem 0;
  background-color: $theme-surface;
  border-top: 3px solid $theme-border;

  .footer-inner {
    display: flex;
    justify-content: space-between;
    align-items: center;
    gap: 2rem;

    @media (max-width: 640px) {
      flex-direction: column;
      text-align: center;
    }
  }

  .footer-text {
    font-size: 0.875rem;
    color: $theme-text-muted;
  }
}

// -----------------------------------------------------------------------------
// Animations
// -----------------------------------------------------------------------------

@keyframes bounce {
  0%, 100% { transform: translateY(0); }
  50% { transform: translateY(-10px); }
}

@keyframes wiggle {
  0%, 100% { transform: rotate(-3deg); }
  50% { transform: rotate(3deg); }
}

@keyframes pop {
  0% { transform: scale(0.95); }
  50% { transform: scale(1.05); }
  100% { transform: scale(1); }
}

@keyframes float {
  0%, 100% { transform: translateY(0); }
  50% { transform: translateY(-5px); }
}

.animate-bounce { animation: bounce 2s ease-in-out infinite; }
.animate-wiggle { animation: wiggle 1s ease-in-out infinite; }
.animate-pop { animation: pop 0.3s ease-out; }
.animate-float { animation: float 3s ease-in-out infinite; }

// -----------------------------------------------------------------------------
// Utilities
// -----------------------------------------------------------------------------

.text-center { text-align: center; }
.text-gradient {
  background: linear-gradient(135deg, $theme-primary 0%, $theme-secondary 100%);
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
  background-clip: text;
}

.rounded-full { border-radius: $theme-radius-full; }
.shadow-glow { box-shadow: $theme-shadow-glow; }
`.trim();
}

/** Generate CSS variables only */
export function generatePlayfulCSSVariables(darkMode: boolean = false): string {
  const colors = darkMode ? playfulDarkColors : playfulLightColors;

  return `
:root {
  /* Colors */
  --color-primary: ${colors.primary};
  --color-secondary: ${colors.secondary};
  --color-accent: #FFD93D;
  --color-background: ${colors.background};
  --color-surface: ${colors.surface};
  --color-text: ${colors.text};
  --color-text-muted: ${colors.textMuted};
  --color-border: ${colors.border};
  --color-success: ${colors.success};
  --color-warning: ${colors.warning};
  --color-error: ${colors.error};

  /* Typography */
  --font-heading: ${playfulTypography.headingFont};
  --font-body: ${playfulTypography.bodyFont};
  --font-size-base: ${playfulTypography.baseFontSize};
  --line-height: ${playfulTypography.lineHeight};
  --heading-weight: ${playfulTypography.headingWeight};

  /* Spacing */
  --section-padding: ${playfulSpacing.sectionPadding};
  --container-width: ${playfulSpacing.containerWidth};
  --gap: ${playfulSpacing.gap};
  --radius: ${playfulSpacing.borderRadius};
  --radius-full: 9999px;
}
`.trim();
}

/** Generate Odoo manifest */
export function generatePlayfulManifest(): Record<string, unknown> {
  return {
    name: playfulTheme.name,
    summary: playfulTheme.description,
    description: `
${playfulTheme.description}

Features:
- Bright, saturated colors (pinks, yellows, teals)
- Large rounded corners and pill shapes
- Playful, bouncy animations
- Fun, friendly typography (Baloo 2, Nunito)
- Soft shadows and gradients
- Light and dark mode support
- Mobile-first responsive design
    `.trim(),
    category: "Theme/Website",
    version: playfulTheme.version,
    author: playfulTheme.author,
    website: "https://platxa.com",
    license: "LGPL-3",
    depends: ["website"],
    data: [
      "views/templates.xml",
      "views/snippets.xml",
      "views/options.xml",
    ],
    assets: {
      "web.assets_frontend": [
        "/theme_playful_fun/static/src/scss/theme.scss",
        "/theme_playful_fun/static/src/js/theme.js",
      ],
    },
    images: [playfulTheme.previewImage],
    application: false,
    installable: true,
    auto_install: false,
  };
}

// =============================================================================
// Exports
// =============================================================================

export default playfulTheme;
