/**
 * Git Integration for Theme Version Control
 *
 * Provides Git operations for Odoo themes including:
 * - Repository initialization
 * - Commit history management
 * - Branch operations
 * - Remote repository sync
 */

import type { GeneratedFile } from "../odoo-skills";

// =============================================================================
// TYPES
// =============================================================================

export interface GitConfig {
  /** Repository URL (GitHub, GitLab, etc.) */
  remoteUrl?: string;
  /** Default branch name */
  defaultBranch: string;
  /** Author name for commits */
  authorName: string;
  /** Author email for commits */
  authorEmail: string;
}

export interface GitCommit {
  /** Commit hash (SHA) */
  hash: string;
  /** Short hash (7 chars) */
  shortHash: string;
  /** Commit message */
  message: string;
  /** Author name */
  author: string;
  /** Author email */
  email: string;
  /** Commit timestamp */
  timestamp: Date;
  /** Files changed in this commit */
  files: string[];
}

export interface GitBranch {
  /** Branch name */
  name: string;
  /** Is current branch */
  current: boolean;
  /** Last commit on branch */
  lastCommit?: GitCommit;
  /** Is remote tracking branch */
  isRemote: boolean;
}

export interface GitStatus {
  /** Current branch */
  branch: string;
  /** Is repository clean */
  clean: boolean;
  /** Modified files */
  modified: string[];
  /** Added files (staged) */
  staged: string[];
  /** Untracked files */
  untracked: string[];
  /** Deleted files */
  deleted: string[];
  /** Ahead of remote by N commits */
  ahead: number;
  /** Behind remote by N commits */
  behind: number;
}

export interface GitDiff {
  /** File path */
  path: string;
  /** Type of change */
  type: "added" | "modified" | "deleted" | "renamed";
  /** Old path (for renames) */
  oldPath?: string;
  /** Lines added */
  additions: number;
  /** Lines removed */
  deletions: number;
  /** Diff content (unified format) */
  patch?: string;
}

export interface GitOperationResult {
  /** Operation success */
  success: boolean;
  /** Result message */
  message: string;
  /** Error details if failed */
  error?: string;
  /** Additional data */
  data?: Record<string, unknown>;
}

// =============================================================================
// IN-MEMORY GIT SIMULATION (Browser-compatible)
// =============================================================================

/**
 * In-memory Git repository for browser environments
 * Simulates Git operations without actual Git binary
 */
export class InMemoryGitRepo {
  private commits: GitCommit[] = [];
  private branches: Map<string, string> = new Map(); // branch -> commit hash
  private currentBranch: string = "main";
  private files: Map<string, string> = new Map(); // path -> content
  private stagedFiles: Set<string> = new Set();
  private config: GitConfig;

  constructor(config: Partial<GitConfig> = {}) {
    this.config = {
      defaultBranch: config.defaultBranch || "main",
      authorName: config.authorName || "Platxa Studio",
      authorEmail: config.authorEmail || "studio@platxa.com",
      remoteUrl: config.remoteUrl,
    };

    // Initialize default branch
    this.branches.set(this.config.defaultBranch, "");
    this.currentBranch = this.config.defaultBranch;
  }

  /**
   * Initialize repository with files
   */
  init(files: GeneratedFile[]): GitOperationResult {
    try {
      // Add all files
      for (const file of files) {
        this.files.set(file.path, file.content);
        this.stagedFiles.add(file.path);
      }

      // Create initial commit
      this.commit("Initial commit: Theme generated by Platxa Studio");

      return {
        success: true,
        message: `Initialized repository with ${files.length} files`,
        data: { fileCount: files.length },
      };
    } catch (error) {
      return {
        success: false,
        message: "Failed to initialize repository",
        error: error instanceof Error ? error.message : "Unknown error",
      };
    }
  }

  /**
   * Stage files for commit
   */
  add(paths: string[] | "all"): GitOperationResult {
    try {
      if (paths === "all") {
        this.files.forEach((_, path) => this.stagedFiles.add(path));
      } else {
        for (const path of paths) {
          if (this.files.has(path)) {
            this.stagedFiles.add(path);
          }
        }
      }

      return {
        success: true,
        message: `Staged ${this.stagedFiles.size} files`,
        data: { stagedCount: this.stagedFiles.size },
      };
    } catch (error) {
      return {
        success: false,
        message: "Failed to stage files",
        error: error instanceof Error ? error.message : "Unknown error",
      };
    }
  }

  /**
   * Create a commit
   */
  commit(message: string): GitOperationResult {
    try {
      if (this.stagedFiles.size === 0) {
        return {
          success: false,
          message: "Nothing to commit",
          error: "No staged files",
        };
      }

      const hash = this.generateHash();
      const commit: GitCommit = {
        hash,
        shortHash: hash.substring(0, 7),
        message,
        author: this.config.authorName,
        email: this.config.authorEmail,
        timestamp: new Date(),
        files: Array.from(this.stagedFiles),
      };

      this.commits.unshift(commit);
      this.branches.set(this.currentBranch, hash);
      this.stagedFiles.clear();

      return {
        success: true,
        message: `Created commit ${commit.shortHash}: ${message}`,
        data: { commit },
      };
    } catch (error) {
      return {
        success: false,
        message: "Failed to create commit",
        error: error instanceof Error ? error.message : "Unknown error",
      };
    }
  }

  /**
   * Get repository status
   */
  status(): GitStatus {
    const modified: string[] = [];
    const untracked: string[] = [];

    // Check for modifications (simplified - tracks staged vs current)
    this.files.forEach((_, path) => {
      if (!this.stagedFiles.has(path) && this.commits.length > 0) {
        // File exists but not in last commit
        const lastCommit = this.commits[0];
        if (!lastCommit.files.includes(path)) {
          untracked.push(path);
        }
      }
    });

    return {
      branch: this.currentBranch,
      clean: this.stagedFiles.size === 0 && modified.length === 0,
      modified,
      staged: Array.from(this.stagedFiles),
      untracked,
      deleted: [],
      ahead: 0,
      behind: 0,
    };
  }

  /**
   * Get commit history
   */
  log(limit: number = 10): GitCommit[] {
    return this.commits.slice(0, limit);
  }

  /**
   * Create a new branch
   */
  branch(name: string, checkout: boolean = false): GitOperationResult {
    try {
      if (this.branches.has(name)) {
        return {
          success: false,
          message: `Branch '${name}' already exists`,
          error: "Branch exists",
        };
      }

      const currentHash = this.branches.get(this.currentBranch) || "";
      this.branches.set(name, currentHash);

      if (checkout) {
        this.currentBranch = name;
      }

      return {
        success: true,
        message: `Created branch '${name}'${checkout ? " and switched to it" : ""}`,
        data: { branch: name, checkedOut: checkout },
      };
    } catch (error) {
      return {
        success: false,
        message: "Failed to create branch",
        error: error instanceof Error ? error.message : "Unknown error",
      };
    }
  }

  /**
   * Switch to a branch
   */
  checkout(branchName: string): GitOperationResult {
    try {
      if (!this.branches.has(branchName)) {
        return {
          success: false,
          message: `Branch '${branchName}' not found`,
          error: "Branch not found",
        };
      }

      this.currentBranch = branchName;

      return {
        success: true,
        message: `Switched to branch '${branchName}'`,
        data: { branch: branchName },
      };
    } catch (error) {
      return {
        success: false,
        message: "Failed to checkout branch",
        error: error instanceof Error ? error.message : "Unknown error",
      };
    }
  }

  /**
   * List all branches
   */
  listBranches(): GitBranch[] {
    const branches: GitBranch[] = [];

    this.branches.forEach((hash, name) => {
      const commit = this.commits.find((c) => c.hash === hash);
      branches.push({
        name,
        current: name === this.currentBranch,
        lastCommit: commit,
        isRemote: false,
      });
    });

    return branches;
  }

  /**
   * Update file content
   */
  updateFile(path: string, content: string): void {
    this.files.set(path, content);
  }

  /**
   * Delete a file
   */
  deleteFile(path: string): void {
    this.files.delete(path);
    this.stagedFiles.delete(path);
  }

  /**
   * Get all files
   */
  getFiles(): Map<string, string> {
    return new Map(this.files);
  }

  /**
   * Export repository state for persistence
   */
  export(): {
    commits: GitCommit[];
    branches: Record<string, string>;
    currentBranch: string;
    files: Record<string, string>;
    config: GitConfig;
  } {
    return {
      commits: this.commits,
      branches: Object.fromEntries(this.branches),
      currentBranch: this.currentBranch,
      files: Object.fromEntries(this.files),
      config: this.config,
    };
  }

  /**
   * Import repository state from persistence
   */
  import(state: ReturnType<typeof this.export>): void {
    this.commits = state.commits.map((c) => ({
      ...c,
      timestamp: new Date(c.timestamp),
    }));
    this.branches = new Map(Object.entries(state.branches));
    this.currentBranch = state.currentBranch;
    this.files = new Map(Object.entries(state.files));
    this.config = state.config;
  }

  /**
   * Generate a random hash (simulating Git SHA)
   */
  private generateHash(): string {
    const chars = "0123456789abcdef";
    let hash = "";
    for (let i = 0; i < 40; i++) {
      hash += chars[Math.floor(Math.random() * chars.length)];
    }
    return hash;
  }
}

// =============================================================================
// GIT SERVICE
// =============================================================================

/**
 * Git service for theme version control
 */
export class GitService {
  private repo: InMemoryGitRepo;

  constructor(config?: Partial<GitConfig>) {
    this.repo = new InMemoryGitRepo(config);
  }

  /**
   * Initialize a new repository with theme files
   */
  initRepository(files: GeneratedFile[]): GitOperationResult {
    return this.repo.init(files);
  }

  /**
   * Save changes with a commit
   */
  saveChanges(
    files: GeneratedFile[],
    message: string
  ): GitOperationResult {
    // Update files
    for (const file of files) {
      this.repo.updateFile(file.path, file.content);
    }

    // Stage all changes
    this.repo.add("all");

    // Commit
    return this.repo.commit(message);
  }

  /**
   * Get current status
   */
  getStatus(): GitStatus {
    return this.repo.status();
  }

  /**
   * Get commit history
   */
  getHistory(limit?: number): GitCommit[] {
    return this.repo.log(limit);
  }

  /**
   * Create a new branch
   */
  createBranch(name: string, checkout?: boolean): GitOperationResult {
    return this.repo.branch(name, checkout);
  }

  /**
   * Switch branches
   */
  switchBranch(name: string): GitOperationResult {
    return this.repo.checkout(name);
  }

  /**
   * List all branches
   */
  getBranches(): GitBranch[] {
    return this.repo.listBranches();
  }

  /**
   * Get all files in repository
   */
  getFiles(): GeneratedFile[] {
    const files: GeneratedFile[] = [];
    this.repo.getFiles().forEach((content, path) => {
      const ext = path.split(".").pop() || "";
      const typeMap: Record<string, GeneratedFile["type"]> = {
        xml: "xml",
        py: "py",
        scss: "scss",
        css: "css",
        js: "js",
        po: "po",
        pot: "pot",
      };
      files.push({
        path,
        content,
        type: typeMap[ext] || "xml",
      });
    });
    return files;
  }

  /**
   * Export repository state for storage
   */
  exportState(): ReturnType<InMemoryGitRepo["export"]> {
    return this.repo.export();
  }

  /**
   * Import repository state from storage
   */
  importState(state: ReturnType<InMemoryGitRepo["export"]>): void {
    this.repo.import(state);
  }
}

// =============================================================================
// HELPER FUNCTIONS
// =============================================================================

/**
 * Generate conventional commit message
 */
export function generateCommitMessage(
  type: "feat" | "fix" | "refactor" | "style" | "docs" | "chore",
  scope: string,
  description: string
): string {
  return `${type}(${scope}): ${description}`;
}

/**
 * Parse conventional commit message
 */
export function parseCommitMessage(message: string): {
  type?: string;
  scope?: string;
  description: string;
} {
  const match = message.match(/^(\w+)(?:\(([^)]+)\))?: (.+)$/);
  if (match) {
    return {
      type: match[1],
      scope: match[2],
      description: match[3],
    };
  }
  return { description: message };
}

/**
 * Format commit for display
 */
export function formatCommit(commit: GitCommit): string {
  const date = commit.timestamp.toLocaleDateString();
  return `${commit.shortHash} - ${commit.message} (${commit.author}, ${date})`;
}
