/**
 * Corporate Theme Template
 *
 * Professional blue/gray design with formal typography.
 * Perfect for businesses, enterprises, and professional services.
 *
 * Features:
 * - Professional blue and gray color palette
 * - Formal serif/sans-serif typography pairing
 * - Structured layout with clear hierarchy
 * - Trust-building design elements
 * - Full-width sections with contained content
 *
 * Feature #62: Theme System - Corporate Theme
 */

import type { ThemeTemplate, ColorScheme, Typography, Spacing, LayoutOptions } from "../../theme-registry";

// =============================================================================
// Theme Configuration
// =============================================================================

/** Corporate theme color scheme */
export const corporateColors: ColorScheme = {
  primary: "#1e3a5f",
  secondary: "#2563eb",
  background: "#ffffff",
  surface: "#f8fafc",
  text: "#1e293b",
  textMuted: "#64748b",
  border: "#e2e8f0",
  success: "#059669",
  warning: "#d97706",
  error: "#dc2626",
};

/** Corporate theme dark variant */
export const corporateDarkColors: ColorScheme = {
  primary: "#60a5fa",
  secondary: "#3b82f6",
  background: "#0f172a",
  surface: "#1e293b",
  text: "#f1f5f9",
  textMuted: "#94a3b8",
  border: "#334155",
  success: "#10b981",
  warning: "#f59e0b",
  error: "#ef4444",
};

/** Corporate theme typography */
export const corporateTypography: Typography = {
  headingFont: "Georgia, 'Times New Roman', serif",
  bodyFont: "system-ui, -apple-system, 'Segoe UI', Roboto, sans-serif",
  baseFontSize: "16px",
  lineHeight: "1.6",
  headingWeight: "700",
};

/** Corporate theme spacing */
export const corporateSpacing: Spacing = {
  sectionPadding: "80px",
  containerWidth: "1200px",
  gap: "24px",
  borderRadius: "6px",
};

/** Corporate theme layout */
export const corporateLayout: LayoutOptions = {
  headerStyle: "sticky",
  navStyle: "horizontal",
  footerColumns: 4,
};

// =============================================================================
// Theme Template Definition
// =============================================================================

/** Corporate theme template */
export const corporateTheme: ThemeTemplate = {
  id: "corporate-professional",
  name: "Corporate Professional",
  description: "Professional blue/gray design with formal typography. Ideal for businesses, enterprises, law firms, consulting, and professional services that want to convey trust and expertise.",
  category: "corporate",
  tags: ["professional", "business", "blue", "formal", "trust", "enterprise", "consulting"],
  previewImage: "/themes/corporate-professional/preview.png",
  thumbnail: "/themes/corporate-professional/thumb.png",
  colors: corporateColors,
  typography: corporateTypography,
  spacing: corporateSpacing,
  layout: corporateLayout,
  isPremium: false,
  version: "1.0.0",
  author: "Platxa Studio",
  updatedAt: new Date("2024-02-22"),
  odooVersion: "17.0",
};

// =============================================================================
// SCSS Generation
// =============================================================================

/** Generate corporate theme SCSS */
export function generateCorporateSCSS(darkMode: boolean = false): string {
  const colors = darkMode ? corporateDarkColors : corporateColors;

  return `
// =============================================================================
// Corporate Professional Theme - ${darkMode ? "Dark Mode" : "Light Mode"}
// Generated by Platxa Studio
// =============================================================================

// -----------------------------------------------------------------------------
// Variables
// -----------------------------------------------------------------------------

// Colors
$corp-primary: ${colors.primary};
$corp-secondary: ${colors.secondary};
$corp-background: ${colors.background};
$corp-surface: ${colors.surface};
$corp-text: ${colors.text};
$corp-text-muted: ${colors.textMuted};
$corp-border: ${colors.border};
$corp-success: ${colors.success};
$corp-warning: ${colors.warning};
$corp-error: ${colors.error};

// Typography
$corp-font-heading: ${corporateTypography.headingFont};
$corp-font-body: ${corporateTypography.bodyFont};
$corp-font-size-base: ${corporateTypography.baseFontSize};
$corp-line-height: ${corporateTypography.lineHeight};
$corp-heading-weight: ${corporateTypography.headingWeight};

// Spacing
$corp-section-padding: ${corporateSpacing.sectionPadding};
$corp-container-width: ${corporateSpacing.containerWidth};
$corp-gap: ${corporateSpacing.gap};
$corp-radius: ${corporateSpacing.borderRadius};

// Shadows
$corp-shadow-sm: 0 1px 2px 0 rgba(0, 0, 0, 0.05);
$corp-shadow: 0 1px 3px 0 rgba(0, 0, 0, 0.1), 0 1px 2px -1px rgba(0, 0, 0, 0.1);
$corp-shadow-md: 0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -2px rgba(0, 0, 0, 0.1);
$corp-shadow-lg: 0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -4px rgba(0, 0, 0, 0.1);

// Transitions
$corp-transition: 0.15s ease-in-out;

// -----------------------------------------------------------------------------
// CSS Custom Properties
// -----------------------------------------------------------------------------

:root {
  --corp-primary: #{$corp-primary};
  --corp-secondary: #{$corp-secondary};
  --corp-background: #{$corp-background};
  --corp-surface: #{$corp-surface};
  --corp-text: #{$corp-text};
  --corp-text-muted: #{$corp-text-muted};
  --corp-border: #{$corp-border};
  --corp-success: #{$corp-success};
  --corp-warning: #{$corp-warning};
  --corp-error: #{$corp-error};

  --corp-font-heading: #{$corp-font-heading};
  --corp-font-body: #{$corp-font-body};

  --corp-section-padding: #{$corp-section-padding};
  --corp-container-width: #{$corp-container-width};
  --corp-gap: #{$corp-gap};
  --corp-radius: #{$corp-radius};
}

// -----------------------------------------------------------------------------
// Base Styles
// -----------------------------------------------------------------------------

html {
  font-size: $corp-font-size-base;
  scroll-behavior: smooth;
}

body {
  margin: 0;
  font-family: $corp-font-body;
  font-size: 1rem;
  line-height: $corp-line-height;
  color: $corp-text;
  background-color: $corp-background;
}

// -----------------------------------------------------------------------------
// Typography
// -----------------------------------------------------------------------------

h1, h2, h3, h4, h5, h6 {
  margin: 0 0 1rem;
  font-family: $corp-font-heading;
  font-weight: $corp-heading-weight;
  line-height: 1.25;
  color: $corp-primary;
}

h1 {
  font-size: 2.75rem;
  margin-bottom: 1.5rem;

  @media (max-width: 768px) {
    font-size: 2rem;
  }
}

h2 {
  font-size: 2.25rem;

  @media (max-width: 768px) {
    font-size: 1.75rem;
  }
}

h3 {
  font-size: 1.75rem;
}

h4 {
  font-size: 1.375rem;
}

h5 {
  font-size: 1.125rem;
}

h6 {
  font-size: 1rem;
  text-transform: uppercase;
  letter-spacing: 0.05em;
  color: $corp-text-muted;
}

p {
  margin: 0 0 1rem;

  &.lead {
    font-size: 1.25rem;
    color: $corp-text-muted;
    line-height: 1.7;
  }
}

a {
  color: $corp-secondary;
  text-decoration: none;
  transition: color $corp-transition;

  &:hover {
    color: darken($corp-secondary, 15%);
    text-decoration: underline;
  }
}

// -----------------------------------------------------------------------------
// Layout
// -----------------------------------------------------------------------------

.container {
  width: 100%;
  max-width: $corp-container-width;
  margin: 0 auto;
  padding: 0 1.5rem;
}

section,
.section {
  padding: $corp-section-padding 0;

  @media (max-width: 768px) {
    padding: 48px 0;
  }
}

.section-alt {
  background-color: $corp-surface;
}

.section-dark {
  background-color: $corp-primary;
  color: #fff;

  h1, h2, h3, h4, h5, h6 {
    color: #fff;
  }

  p {
    color: rgba(255, 255, 255, 0.85);
  }
}

// -----------------------------------------------------------------------------
// Header
// -----------------------------------------------------------------------------

.header {
  position: sticky;
  top: 0;
  z-index: 1000;
  background-color: $corp-background;
  border-bottom: 1px solid $corp-border;
  box-shadow: $corp-shadow-sm;

  .header-inner {
    display: flex;
    align-items: center;
    justify-content: space-between;
    height: 72px;
  }
}

.logo {
  display: flex;
  align-items: center;
  gap: 0.75rem;
  font-family: $corp-font-heading;
  font-size: 1.5rem;
  font-weight: 700;
  color: $corp-primary;
  text-decoration: none;

  &:hover {
    color: $corp-primary;
    text-decoration: none;
  }

  img {
    height: 40px;
    width: auto;
  }
}

.nav {
  display: flex;
  align-items: center;
  gap: 2rem;

  @media (max-width: 992px) {
    display: none;
  }
}

.nav-link {
  font-size: 0.9375rem;
  font-weight: 500;
  color: $corp-text;
  text-decoration: none;
  transition: color $corp-transition;

  &:hover,
  &.active {
    color: $corp-secondary;
    text-decoration: none;
  }
}

.nav-cta {
  margin-left: 1rem;
}

// -----------------------------------------------------------------------------
// Hero
// -----------------------------------------------------------------------------

.hero {
  padding: 100px 0;
  background: linear-gradient(135deg, $corp-primary 0%, darken($corp-primary, 10%) 100%);
  color: #fff;

  @media (max-width: 768px) {
    padding: 60px 0;
  }

  h1 {
    color: #fff;
    max-width: 800px;
  }

  .hero-subtitle {
    font-size: 1.25rem;
    color: rgba(255, 255, 255, 0.9);
    max-width: 600px;
    margin-bottom: 2rem;
  }

  .hero-actions {
    display: flex;
    gap: 1rem;
    flex-wrap: wrap;
  }
}

// -----------------------------------------------------------------------------
// Buttons
// -----------------------------------------------------------------------------

.btn {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  gap: 0.5rem;
  padding: 0.75rem 1.5rem;
  font-family: $corp-font-body;
  font-size: 0.9375rem;
  font-weight: 600;
  line-height: 1.5;
  text-align: center;
  text-decoration: none;
  white-space: nowrap;
  vertical-align: middle;
  cursor: pointer;
  user-select: none;
  border: 2px solid transparent;
  border-radius: $corp-radius;
  transition: all $corp-transition;

  &:focus {
    outline: 2px solid $corp-secondary;
    outline-offset: 2px;
  }

  &:disabled {
    opacity: 0.65;
    cursor: not-allowed;
  }
}

.btn-primary {
  color: #fff;
  background-color: $corp-secondary;
  border-color: $corp-secondary;

  &:hover:not(:disabled) {
    background-color: darken($corp-secondary, 10%);
    border-color: darken($corp-secondary, 10%);
    text-decoration: none;
  }
}

.btn-secondary {
  color: $corp-primary;
  background-color: transparent;
  border-color: $corp-primary;

  &:hover:not(:disabled) {
    color: #fff;
    background-color: $corp-primary;
    text-decoration: none;
  }
}

.btn-white {
  color: $corp-primary;
  background-color: #fff;
  border-color: #fff;

  &:hover:not(:disabled) {
    background-color: $corp-surface;
    border-color: $corp-surface;
    text-decoration: none;
  }
}

.btn-outline-white {
  color: #fff;
  background-color: transparent;
  border-color: #fff;

  &:hover:not(:disabled) {
    color: $corp-primary;
    background-color: #fff;
    text-decoration: none;
  }
}

.btn-lg {
  padding: 1rem 2rem;
  font-size: 1rem;
}

.btn-sm {
  padding: 0.5rem 1rem;
  font-size: 0.875rem;
}

// -----------------------------------------------------------------------------
// Cards
// -----------------------------------------------------------------------------

.card {
  background-color: $corp-background;
  border: 1px solid $corp-border;
  border-radius: $corp-radius;
  box-shadow: $corp-shadow;
  overflow: hidden;
  transition: box-shadow $corp-transition, transform $corp-transition;

  &:hover {
    box-shadow: $corp-shadow-md;
    transform: translateY(-2px);
  }
}

.card-body {
  padding: 1.5rem;
}

.card-title {
  font-size: 1.25rem;
  margin-bottom: 0.75rem;
}

.card-text {
  color: $corp-text-muted;
  margin-bottom: 1rem;
}

.card-icon {
  width: 48px;
  height: 48px;
  display: flex;
  align-items: center;
  justify-content: center;
  background-color: rgba($corp-secondary, 0.1);
  border-radius: $corp-radius;
  margin-bottom: 1rem;
  color: $corp-secondary;

  svg {
    width: 24px;
    height: 24px;
  }
}

// -----------------------------------------------------------------------------
// Services Grid
// -----------------------------------------------------------------------------

.services-grid {
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: $corp-gap;

  @media (max-width: 992px) {
    grid-template-columns: repeat(2, 1fr);
  }

  @media (max-width: 640px) {
    grid-template-columns: 1fr;
  }
}

// -----------------------------------------------------------------------------
// Stats Section
// -----------------------------------------------------------------------------

.stats {
  display: grid;
  grid-template-columns: repeat(4, 1fr);
  gap: $corp-gap;
  text-align: center;

  @media (max-width: 768px) {
    grid-template-columns: repeat(2, 1fr);
  }
}

.stat-item {
  padding: 1.5rem;
}

.stat-number {
  font-family: $corp-font-heading;
  font-size: 3rem;
  font-weight: 700;
  color: $corp-secondary;
  line-height: 1;
  margin-bottom: 0.5rem;
}

.stat-label {
  font-size: 0.9375rem;
  color: $corp-text-muted;
  text-transform: uppercase;
  letter-spacing: 0.05em;
}

// -----------------------------------------------------------------------------
// Testimonials
// -----------------------------------------------------------------------------

.testimonial {
  padding: 2rem;
  background-color: $corp-surface;
  border-radius: $corp-radius;
  border-left: 4px solid $corp-secondary;
}

.testimonial-text {
  font-size: 1.125rem;
  font-style: italic;
  color: $corp-text;
  margin-bottom: 1.5rem;
}

.testimonial-author {
  display: flex;
  align-items: center;
  gap: 1rem;
}

.testimonial-avatar {
  width: 48px;
  height: 48px;
  border-radius: 50%;
  object-fit: cover;
}

.testimonial-name {
  font-weight: 600;
  color: $corp-text;
}

.testimonial-title {
  font-size: 0.875rem;
  color: $corp-text-muted;
}

// -----------------------------------------------------------------------------
// Footer
// -----------------------------------------------------------------------------

.footer {
  padding: 60px 0 30px;
  background-color: $corp-primary;
  color: #fff;
}

.footer-grid {
  display: grid;
  grid-template-columns: 2fr repeat(3, 1fr);
  gap: 3rem;
  margin-bottom: 3rem;

  @media (max-width: 992px) {
    grid-template-columns: repeat(2, 1fr);
  }

  @media (max-width: 640px) {
    grid-template-columns: 1fr;
  }
}

.footer-brand {
  .logo {
    color: #fff;
    margin-bottom: 1rem;
  }

  p {
    color: rgba(255, 255, 255, 0.7);
    max-width: 300px;
  }
}

.footer-heading {
  font-family: $corp-font-body;
  font-size: 0.875rem;
  font-weight: 600;
  text-transform: uppercase;
  letter-spacing: 0.05em;
  color: rgba(255, 255, 255, 0.5);
  margin-bottom: 1.25rem;
}

.footer-links {
  list-style: none;
  padding: 0;
  margin: 0;

  li {
    margin-bottom: 0.75rem;
  }

  a {
    color: rgba(255, 255, 255, 0.8);
    text-decoration: none;
    transition: color $corp-transition;

    &:hover {
      color: #fff;
      text-decoration: none;
    }
  }
}

.footer-bottom {
  padding-top: 1.5rem;
  border-top: 1px solid rgba(255, 255, 255, 0.1);
  display: flex;
  justify-content: space-between;
  align-items: center;
  flex-wrap: wrap;
  gap: 1rem;

  @media (max-width: 640px) {
    flex-direction: column;
    text-align: center;
  }
}

.footer-copyright {
  font-size: 0.875rem;
  color: rgba(255, 255, 255, 0.6);
}

.footer-social {
  display: flex;
  gap: 1rem;

  a {
    color: rgba(255, 255, 255, 0.6);
    transition: color $corp-transition;

    &:hover {
      color: #fff;
    }

    svg {
      width: 20px;
      height: 20px;
    }
  }
}

// -----------------------------------------------------------------------------
// Utilities
// -----------------------------------------------------------------------------

.text-center { text-align: center; }
.text-primary { color: $corp-primary; }
.text-secondary { color: $corp-secondary; }
.text-muted { color: $corp-text-muted; }

.bg-surface { background-color: $corp-surface; }
.bg-primary { background-color: $corp-primary; color: #fff; }

.shadow { box-shadow: $corp-shadow; }
.shadow-md { box-shadow: $corp-shadow-md; }
.shadow-lg { box-shadow: $corp-shadow-lg; }
`.trim();
}

/** Generate CSS variables only */
export function generateCorporateCSSVariables(darkMode: boolean = false): string {
  const colors = darkMode ? corporateDarkColors : corporateColors;

  return `
:root {
  /* Colors */
  --corp-primary: ${colors.primary};
  --corp-secondary: ${colors.secondary};
  --corp-background: ${colors.background};
  --corp-surface: ${colors.surface};
  --corp-text: ${colors.text};
  --corp-text-muted: ${colors.textMuted};
  --corp-border: ${colors.border};
  --corp-success: ${colors.success};
  --corp-warning: ${colors.warning};
  --corp-error: ${colors.error};

  /* Typography */
  --corp-font-heading: ${corporateTypography.headingFont};
  --corp-font-body: ${corporateTypography.bodyFont};
  --corp-font-size-base: ${corporateTypography.baseFontSize};
  --corp-line-height: ${corporateTypography.lineHeight};
  --corp-heading-weight: ${corporateTypography.headingWeight};

  /* Spacing */
  --corp-section-padding: ${corporateSpacing.sectionPadding};
  --corp-container-width: ${corporateSpacing.containerWidth};
  --corp-gap: ${corporateSpacing.gap};
  --corp-radius: ${corporateSpacing.borderRadius};
}
`.trim();
}

/** Generate Odoo manifest */
export function generateCorporateManifest(): Record<string, unknown> {
  return {
    name: corporateTheme.name,
    summary: corporateTheme.description,
    description: `
${corporateTheme.description}

Features:
- Professional blue/gray color palette
- Georgia headings with system UI body text
- Sticky header with professional navigation
- Hero section with gradient background
- Service cards with hover effects
- Stats section for key metrics
- Testimonial component
- Full-featured footer with 4 columns
- Dark mode support
    `.trim(),
    category: "Theme/Website",
    version: corporateTheme.version,
    author: corporateTheme.author,
    website: "https://platxa.com",
    license: "LGPL-3",
    depends: ["website"],
    data: [
      "views/templates.xml",
      "views/snippets.xml",
      "views/options.xml",
    ],
    assets: {
      "web.assets_frontend": [
        "/theme_corporate_professional/static/src/scss/theme.scss",
        "/theme_corporate_professional/static/src/js/theme.js",
      ],
    },
    images: [corporateTheme.previewImage],
    application: false,
    installable: true,
    auto_install: false,
  };
}

// =============================================================================
// Exports
// =============================================================================

export default corporateTheme;
