"use client";

/**
 * DeploymentPanelWrapper - Connects DeploymentPanel to project store and deploy API
 */

import { useState, useCallback } from "react";
import { DeploymentPanel } from "./DeploymentPanel";
import { useProjectStore, useEditorStore } from "@/lib/stores";
import { getDeployService } from "@/lib/deployment/one-click-deploy";
import type { DeploymentTarget, DeploymentHistoryEntry } from "./DeploymentPanel";

interface DeploymentPanelWrapperProps {
  projectId: string;
}

export function DeploymentPanelWrapper({ projectId }: DeploymentPanelWrapperProps) {
  const { projectName, odooUrl, odooStatus } = useProjectStore();
  const fileContents = useEditorStore((s) => s.fileContents);
  const [targets, setTargets] = useState<DeploymentTarget[]>(() => {
    if (odooUrl) {
      return [{
        id: "default",
        name: "Local Odoo",
        url: odooUrl,
        database: "odoo",
        odooVersion: "18.0",
        status: odooStatus === "connected" ? "connected" : "disconnected",
        isDefault: true,
      }];
    }
    return [];
  });
  const [history, setHistory] = useState<DeploymentHistoryEntry[]>([]);
  const [isDeploying, setIsDeploying] = useState(false);
  const [currentDeploymentId, setCurrentDeploymentId] = useState<string>();

  const themeName = projectName?.replace(/\s+/g, "_").toLowerCase() || "theme_custom";

  const handleAddTarget = useCallback(() => {
    const url = prompt("Enter Odoo server URL (e.g., http://localhost:8069):");
    if (!url) return;
    const name = prompt("Enter a name for this target:") || "Odoo Server";
    setTargets(prev => [...prev, {
      id: `target-${Date.now()}`,
      name,
      url,
      database: "odoo",
      odooVersion: "18.0",
      status: "disconnected" as const,
      isDefault: prev.length === 0,
    }]);
  }, []);

  const handleRemoveTarget = useCallback((targetId: string) => {
    setTargets(prev => prev.filter(t => t.id !== targetId));
  }, []);

  const handleTestConnection = useCallback(async (targetId: string) => {
    const target = targets.find(t => t.id === targetId);
    if (!target) return;

    setTargets(prev => prev.map(t =>
      t.id === targetId ? { ...t, status: "checking" as const } : t
    ));

    try {
      const res = await fetch(`/api/deploy?url=${encodeURIComponent(target.url)}`);
      const data = await res.json();
      setTargets(prev => prev.map(t =>
        t.id === targetId
          ? {
              ...t,
              status: data.connected ? "connected" as const : "error" as const,
              lastChecked: new Date(),
            }
          : t
      ));
    } catch {
      setTargets(prev => prev.map(t =>
        t.id === targetId ? { ...t, status: "error" as const } : t
      ));
    }
  }, [targets]);

  const handleDeploy = useCallback(async (targetId: string) => {
    const target = targets.find(t => t.id === targetId);
    if (!target || isDeploying) return;

    const deployId = `deploy-${Date.now()}`;
    setIsDeploying(true);
    setCurrentDeploymentId(deployId);

    const now = new Date();
    const newEntry: DeploymentHistoryEntry = {
      id: deployId,
      targetId,
      targetName: target.name,
      status: "deploying",
      deployedAt: now,
      deployedBy: "current-user",
      version: "1.0.0",
      moduleName: themeName,
      canRollback: false,
    };

    setHistory(prev => [newEntry, ...prev]);

    try {
      // Build module package from editor file contents
      const moduleFiles = new Map<string, string | Uint8Array>();
      for (const [path, content] of Object.entries(fileContents)) {
        // Strip the theme_generated/ prefix if present for proper module structure
        const modulePath = path.replace(/^theme_generated\//, "");
        moduleFiles.set(modulePath, content);
      }

      const deployService = getDeployService();
      const result = await deployService.deploy({
        modulePackage: {
          name: projectName || "Theme Generated",
          technicalName: themeName,
          version: "1.0.0",
          description: `Generated by Platxa Website Studio`,
          files: moduleFiles,
          manifest: {
            name: projectName || "Theme Generated",
            version: "1.0.0",
            category: "Theme",
            summary: "AI-generated Odoo website theme",
            depends: ["website"],
            data: Array.from(moduleFiles.keys()).filter(f => f.endsWith(".xml")).map(f => f),
            assets: {
              "web.assets_frontend": Array.from(moduleFiles.keys())
                .filter(f => f.endsWith(".scss") || f.endsWith(".css") || f.endsWith(".js"))
                .map(f => `${themeName}/${f}`),
            },
            installable: true,
            application: false,
            auto_install: false,
            license: "LGPL-3",
          },
        },
        server: {
          id: target.id,
          name: target.name,
          url: target.url,
          database: target.database,
          version: (target.odooVersion || "17.0") as "14.0" | "15.0" | "16.0" | "17.0",
        },
        activateWebsite: true,
        backupExisting: true,
        onProgress: (progress) => {
          console.log(`[Deploy] ${progress.status}: ${progress.message} (${progress.progress}%)`);
        },
      });

      setHistory(prev => prev.map(h =>
        h.id === deployId
          ? {
              ...h,
              status: result.success ? "success" as const : "failed" as const,
              completedAt: new Date(),
              duration: Date.now() - now.getTime(),
              error: result.error,
              canRollback: result.success,
            }
          : h
      ));
    } catch (error) {
      setHistory(prev => prev.map(h =>
        h.id === deployId
          ? {
              ...h,
              status: "failed" as const,
              completedAt: new Date(),
              duration: Date.now() - now.getTime(),
              error: error instanceof Error ? error.message : "Deploy failed",
            }
          : h
      ));
    } finally {
      setIsDeploying(false);
      setCurrentDeploymentId(undefined);
    }
  }, [targets, isDeploying, fileContents, themeName, projectName]);

  const handleSetDefault = useCallback((targetId: string) => {
    setTargets(prev => prev.map(t => ({
      ...t,
      isDefault: t.id === targetId,
    })));
  }, []);

  return (
    <div className="h-full overflow-auto">
      <DeploymentPanel
        projectId={projectId}
        projectName={projectName || "Untitled"}
        targets={targets}
        history={history}
        isDeploying={isDeploying}
        currentDeploymentId={currentDeploymentId}
        onAddTarget={handleAddTarget}
        onRemoveTarget={handleRemoveTarget}
        onTestConnection={handleTestConnection}
        onDeploy={handleDeploy}
        onSetDefault={handleSetDefault}
      />
    </div>
  );
}
