/**
 * LLM-Based Fix Generator
 *
 * Generates fixes for novel errors that don't match existing patterns
 * by sending error context to an LLM and parsing the response.
 */

// =============================================================================
// Types
// =============================================================================

/** Error context sent to LLM */
export interface LLMErrorContext {
  /** Error message */
  errorMessage: string;
  /** Error type/category if known */
  errorType?: string;
  /** File path where error occurred */
  filePath?: string;
  /** Line number */
  lineNumber?: number;
  /** Column number */
  columnNumber?: number;
  /** Source code context (lines around error) */
  sourceContext?: string;
  /** Stack trace if available */
  stackTrace?: string;
  /** Additional metadata */
  metadata?: Record<string, unknown>;
}

/** Generated fix from LLM */
export interface LLMGeneratedFix {
  /** Fix description */
  description: string;
  /** Suggested code change */
  suggestedCode?: string;
  /** Explanation of the fix */
  explanation: string;
  /** Confidence level (0-1) */
  confidence: number;
  /** Alternative fixes if any */
  alternatives?: Array<{
    description: string;
    suggestedCode?: string;
  }>;
  /** Whether this was generated by LLM */
  isLLMGenerated: boolean;
  /** Raw LLM response for debugging */
  rawResponse?: string;
}

/** LLM provider configuration */
export interface LLMProviderConfig {
  /** Provider name */
  provider: "openai" | "anthropic" | "mock";
  /** API key (for real providers) */
  apiKey?: string;
  /** Model to use */
  model?: string;
  /** Maximum tokens in response */
  maxTokens?: number;
  /** Temperature for generation */
  temperature?: number;
  /** Request timeout in ms */
  timeout?: number;
}

/** LLM request */
export interface LLMRequest {
  /** System prompt */
  systemPrompt: string;
  /** User prompt with error context */
  userPrompt: string;
  /** Provider config */
  config: LLMProviderConfig;
}

/** LLM response */
export interface LLMResponse {
  /** Generated text */
  text: string;
  /** Whether request was successful */
  success: boolean;
  /** Error message if failed */
  error?: string;
  /** Token usage */
  usage?: {
    promptTokens: number;
    completionTokens: number;
    totalTokens: number;
  };
}

/** Fix generator configuration */
export interface FixGeneratorConfig {
  /** LLM provider config */
  llmConfig: LLMProviderConfig;
  /** System prompt template */
  systemPrompt?: string;
  /** Enable caching of responses */
  enableCache?: boolean;
  /** Maximum cache size */
  maxCacheSize?: number;
  /** Minimum confidence threshold */
  minConfidence?: number;
}

// =============================================================================
// Default Configuration
// =============================================================================

/** Default system prompt for fix generation */
export const DEFAULT_SYSTEM_PROMPT = `You are an expert developer assistant that helps fix code errors.
Given an error message and context, provide a clear, actionable fix.

Response format:
1. DESCRIPTION: A brief description of the fix (one line)
2. EXPLANATION: Why this error occurred and how the fix addresses it (2-3 sentences)
3. CODE: The suggested code fix (if applicable)
4. CONFIDENCE: Your confidence level (high/medium/low)

Be concise and focus on the most likely solution.`;

/** Default fix generator configuration */
export const DEFAULT_FIX_GENERATOR_CONFIG: FixGeneratorConfig = {
  llmConfig: {
    provider: "mock",
    model: "gpt-4",
    maxTokens: 500,
    temperature: 0.3,
    timeout: 30000,
  },
  systemPrompt: DEFAULT_SYSTEM_PROMPT,
  enableCache: true,
  maxCacheSize: 100,
  minConfidence: 0.5,
};

// =============================================================================
// Prompt Building
// =============================================================================

/**
 * Builds user prompt from error context.
 */
export function buildUserPrompt(context: LLMErrorContext): string {
  const parts: string[] = [];

  parts.push(`ERROR: ${context.errorMessage}`);

  if (context.errorType) {
    parts.push(`TYPE: ${context.errorType}`);
  }

  if (context.filePath) {
    let location = `FILE: ${context.filePath}`;
    if (context.lineNumber) {
      location += `:${context.lineNumber}`;
      if (context.columnNumber) {
        location += `:${context.columnNumber}`;
      }
    }
    parts.push(location);
  }

  if (context.sourceContext) {
    parts.push(`\nSOURCE CONTEXT:\n\`\`\`\n${context.sourceContext}\n\`\`\``);
  }

  if (context.stackTrace) {
    parts.push(`\nSTACK TRACE:\n${context.stackTrace}`);
  }

  parts.push("\nPlease provide a fix for this error.");

  return parts.join("\n");
}

/**
 * Creates an LLM request from error context.
 */
export function createLLMRequest(
  context: LLMErrorContext,
  config: FixGeneratorConfig
): LLMRequest {
  return {
    systemPrompt: config.systemPrompt ?? DEFAULT_SYSTEM_PROMPT,
    userPrompt: buildUserPrompt(context),
    config: config.llmConfig,
  };
}

// =============================================================================
// Response Parsing
// =============================================================================

/**
 * Parses confidence level from text.
 */
export function parseConfidence(text: string): number {
  const lowered = text.toLowerCase();

  if (lowered.includes("high")) return 0.9;
  if (lowered.includes("medium")) return 0.7;
  if (lowered.includes("low")) return 0.4;

  // Try to parse numeric confidence
  const numMatch = lowered.match(/(\d+(?:\.\d+)?)\s*%?/);
  if (numMatch) {
    const num = parseFloat(numMatch[1]);
    return num > 1 ? num / 100 : num;
  }

  return 0.6; // Default medium confidence
}

/**
 * Extracts code block from LLM response.
 */
export function extractCodeBlock(text: string): string | undefined {
  // Match fenced code blocks
  const fencedMatch = text.match(/```(?:\w+)?\s*\n([\s\S]*?)\n```/);
  if (fencedMatch) {
    return fencedMatch[1].trim();
  }

  // Match indented code (4+ spaces)
  const indentedLines: string[] = [];
  let inCodeBlock = false;

  for (const line of text.split("\n")) {
    if (line.match(/^(?:\s{4,}|\t)/)) {
      inCodeBlock = true;
      indentedLines.push(line.replace(/^(?:\s{4}|\t)/, ""));
    } else if (inCodeBlock && line.trim() === "") {
      indentedLines.push("");
    } else if (inCodeBlock) {
      break;
    }
  }

  if (indentedLines.length > 0) {
    return indentedLines.join("\n").trim();
  }

  return undefined;
}

/**
 * Extracts section from LLM response.
 */
export function extractSection(text: string, sectionName: string): string {
  const patterns = [
    new RegExp(`${sectionName}:\\s*(.+?)(?=\\n[A-Z]+:|$)`, "is"),
    new RegExp(`\\*\\*${sectionName}\\*\\*:\\s*(.+?)(?=\\n\\*\\*|$)`, "is"),
    new RegExp(`#+ ${sectionName}\\s*\\n(.+?)(?=\\n#|$)`, "is"),
  ];

  for (const pattern of patterns) {
    const match = text.match(pattern);
    if (match) {
      return match[1].trim();
    }
  }

  return "";
}

/**
 * Parses LLM response into a generated fix.
 */
export function parseLLMResponse(response: LLMResponse): LLMGeneratedFix {
  if (!response.success || !response.text) {
    return {
      description: "Failed to generate fix",
      explanation: response.error ?? "Unknown error occurred",
      confidence: 0,
      isLLMGenerated: true,
      rawResponse: response.text,
    };
  }

  const text = response.text;

  // Extract sections
  const description = extractSection(text, "DESCRIPTION") ||
    extractSection(text, "Fix") ||
    text.split("\n")[0].replace(/^[#*\-\d.]+\s*/, "").trim();

  const explanation = extractSection(text, "EXPLANATION") ||
    extractSection(text, "Why") ||
    extractSection(text, "Cause") ||
    "See the suggested fix below.";

  const confidenceText = extractSection(text, "CONFIDENCE") || "medium";
  const confidence = parseConfidence(confidenceText);

  const suggestedCode = extractCodeBlock(text) ||
    extractSection(text, "CODE") ||
    undefined;

  // Extract alternatives if present
  const alternatives: Array<{ description: string; suggestedCode?: string }> = [];
  const altMatch = text.match(/(?:alternative|other|also)[\s\S]*?(?:```[\s\S]*?```|$)/gi);
  if (altMatch) {
    for (const alt of altMatch) {
      const altCode = extractCodeBlock(alt);
      const altDesc = alt.split("\n")[0].replace(/^[#*\-\d.]+\s*/, "").trim();
      if (altDesc && altDesc !== description) {
        alternatives.push({ description: altDesc, suggestedCode: altCode });
      }
    }
  }

  return {
    description: description || "Fix suggested by AI",
    explanation,
    suggestedCode,
    confidence,
    alternatives: alternatives.length > 0 ? alternatives : undefined,
    isLLMGenerated: true,
    rawResponse: text,
  };
}

// =============================================================================
// Mock LLM Provider
// =============================================================================

/**
 * Mock LLM responses for testing.
 */
export const MOCK_LLM_RESPONSES: Record<string, string> = {
  "undefined": `DESCRIPTION: Add null check before accessing property
EXPLANATION: The error occurs because you're trying to access a property on an undefined value. Add a null/undefined check or use optional chaining (?.) to safely access nested properties.
CODE:
\`\`\`javascript
if (obj && obj.property) {
  // safe to use obj.property
}
// or use optional chaining:
const value = obj?.property;
\`\`\`
CONFIDENCE: high`,

  "syntax": `DESCRIPTION: Fix syntax error in code
EXPLANATION: There's a syntax error in your code, likely a missing bracket, semicolon, or incorrect keyword usage. Check the line indicated for common syntax issues.
CODE:
\`\`\`javascript
// Check for:
// - Missing closing brackets } ] )
// - Missing semicolons ;
// - Incorrect keyword usage
\`\`\`
CONFIDENCE: medium`,

  "import": `DESCRIPTION: Fix import statement or install missing module
EXPLANATION: The module cannot be found. Either the import path is incorrect, the module isn't installed, or there's a typo in the module name.
CODE:
\`\`\`bash
# If module is missing:
npm install <module-name>

# If path is wrong, use correct relative path:
import { something } from './correct/path';
\`\`\`
CONFIDENCE: high`,

  "type": `DESCRIPTION: Fix type mismatch or add proper type annotation
EXPLANATION: There's a type error - the value doesn't match the expected type. Check that you're passing the correct type or add explicit type conversion.
CODE:
\`\`\`typescript
// Add explicit type or conversion:
const value: ExpectedType = actualValue as ExpectedType;
// Or fix the source of the wrong type
\`\`\`
CONFIDENCE: medium`,

  "default": `DESCRIPTION: Review error and check common causes
EXPLANATION: This is an uncommon error. Review the error message carefully and check the code context. Common fixes include checking variable names, ensuring proper initialization, and verifying function signatures.
CONFIDENCE: low`,
};

/**
 * Gets mock response based on error context.
 */
export function getMockResponse(context: LLMErrorContext): LLMResponse {
  const message = context.errorMessage.toLowerCase();

  let responseKey = "default";

  if (message.includes("undefined") || message.includes("null")) {
    responseKey = "undefined";
  } else if (message.includes("syntax") || message.includes("unexpected")) {
    responseKey = "syntax";
  } else if (message.includes("import") || message.includes("module") || message.includes("cannot find")) {
    responseKey = "import";
  } else if (message.includes("type") || message.includes("assignable")) {
    responseKey = "type";
  }

  return {
    text: MOCK_LLM_RESPONSES[responseKey],
    success: true,
    usage: {
      promptTokens: 100,
      completionTokens: 150,
      totalTokens: 250,
    },
  };
}

// =============================================================================
// LLM Provider Interface
// =============================================================================

/**
 * Sends request to LLM provider.
 */
export async function sendToLLM(request: LLMRequest): Promise<LLMResponse> {
  const { config } = request;

  switch (config.provider) {
    case "mock":
      // Parse context from user prompt for mock response
      const errorMatch = request.userPrompt.match(/ERROR:\s*(.+?)(?:\n|$)/);
      const mockContext: LLMErrorContext = {
        errorMessage: errorMatch ? errorMatch[1] : request.userPrompt,
      };
      return getMockResponse(mockContext);

    case "openai":
    case "anthropic":
      // Real providers would be implemented here
      // For now, return error indicating not implemented
      return {
        text: "",
        success: false,
        error: `Provider '${config.provider}' requires API integration. Use 'mock' for testing.`,
      };

    default:
      return {
        text: "",
        success: false,
        error: `Unknown provider: ${config.provider}`,
      };
  }
}

// =============================================================================
// LLMFixGenerator Class
// =============================================================================

/**
 * LLM-based fix generator for novel errors.
 */
export class LLMFixGenerator {
  private config: FixGeneratorConfig;
  private cache: Map<string, LLMGeneratedFix> = new Map();

  constructor(config: Partial<FixGeneratorConfig> = {}) {
    this.config = { ...DEFAULT_FIX_GENERATOR_CONFIG, ...config };
  }

  /**
   * Generates a fix for an error using LLM.
   */
  async generateFix(context: LLMErrorContext): Promise<LLMGeneratedFix> {
    // Check cache
    const cacheKey = this.getCacheKey(context);
    if (this.config.enableCache && this.cache.has(cacheKey)) {
      return this.cache.get(cacheKey)!;
    }

    // Create and send request
    const request = createLLMRequest(context, this.config);
    const response = await sendToLLM(request);

    // Parse response
    const fix = parseLLMResponse(response);

    // Check confidence threshold
    if (fix.confidence < (this.config.minConfidence ?? 0.5)) {
      fix.description = `[Low confidence] ${fix.description}`;
    }

    // Cache result
    if (this.config.enableCache) {
      this.manageCache();
      this.cache.set(cacheKey, fix);
    }

    return fix;
  }

  /**
   * Generates fix synchronously (uses cached mock for testing).
   */
  generateFixSync(context: LLMErrorContext): LLMGeneratedFix {
    const cacheKey = this.getCacheKey(context);
    if (this.cache.has(cacheKey)) {
      return this.cache.get(cacheKey)!;
    }

    // For sync, only mock provider works
    if (this.config.llmConfig.provider !== "mock") {
      return {
        description: "Sync generation only available with mock provider",
        explanation: "Use async generateFix() for real LLM providers",
        confidence: 0,
        isLLMGenerated: false,
      };
    }

    const mockResponse = getMockResponse(context);
    const fix = parseLLMResponse(mockResponse);

    if (this.config.enableCache) {
      this.manageCache();
      this.cache.set(cacheKey, fix);
    }

    return fix;
  }

  /**
   * Checks if error should be sent to LLM (no pattern match).
   */
  shouldUseLLM(hasPatternMatch: boolean): boolean {
    return !hasPatternMatch;
  }

  /**
   * Gets cache key for context.
   */
  private getCacheKey(context: LLMErrorContext): string {
    return JSON.stringify({
      message: context.errorMessage,
      type: context.errorType,
      file: context.filePath,
      line: context.lineNumber,
    });
  }

  /**
   * Manages cache size.
   */
  private manageCache(): void {
    const maxSize = this.config.maxCacheSize ?? 100;
    if (this.cache.size >= maxSize) {
      const firstKey = this.cache.keys().next().value;
      if (firstKey) this.cache.delete(firstKey);
    }
  }

  /**
   * Clears the cache.
   */
  clearCache(): void {
    this.cache.clear();
  }

  /**
   * Gets cache statistics.
   */
  getCacheStats(): { size: number; maxSize: number } {
    return {
      size: this.cache.size,
      maxSize: this.config.maxCacheSize ?? 100,
    };
  }

  /**
   * Updates configuration.
   */
  updateConfig(config: Partial<FixGeneratorConfig>): void {
    this.config = { ...this.config, ...config };
    if (config.llmConfig) {
      this.config.llmConfig = { ...this.config.llmConfig, ...config.llmConfig };
    }
  }

  /**
   * Gets current configuration.
   */
  getConfig(): FixGeneratorConfig {
    return { ...this.config };
  }
}

// =============================================================================
// Factory Functions
// =============================================================================

/**
 * Creates an LLMFixGenerator instance.
 */
export function createLLMFixGenerator(
  config?: Partial<FixGeneratorConfig>
): LLMFixGenerator {
  return new LLMFixGenerator(config);
}

/**
 * Creates error context from basic info.
 */
export function createErrorContext(
  errorMessage: string,
  options: Partial<Omit<LLMErrorContext, "errorMessage">> = {}
): LLMErrorContext {
  return {
    errorMessage,
    ...options,
  };
}

// =============================================================================
// Utility Functions
// =============================================================================

/**
 * Formats a generated fix for display.
 */
export function formatGeneratedFix(fix: LLMGeneratedFix): string {
  const parts: string[] = [];

  parts.push(`Fix: ${fix.description}`);
  parts.push(`Explanation: ${fix.explanation}`);

  if (fix.suggestedCode) {
    parts.push(`\nSuggested Code:\n\`\`\`\n${fix.suggestedCode}\n\`\`\``);
  }

  const confidencePercent = Math.round(fix.confidence * 100);
  parts.push(`\nConfidence: ${confidencePercent}%`);

  if (fix.alternatives && fix.alternatives.length > 0) {
    parts.push("\nAlternatives:");
    for (const alt of fix.alternatives) {
      parts.push(`  - ${alt.description}`);
    }
  }

  if (fix.isLLMGenerated) {
    parts.push("\n[Generated by AI]");
  }

  return parts.join("\n");
}

/**
 * Checks if a fix is high confidence.
 */
export function isHighConfidenceFix(fix: LLMGeneratedFix): boolean {
  return fix.confidence >= 0.8;
}

/**
 * Checks if a fix has code suggestion.
 */
export function hasCodeSuggestion(fix: LLMGeneratedFix): boolean {
  return !!fix.suggestedCode && fix.suggestedCode.trim().length > 0;
}

/**
 * Combines multiple fixes into a summary.
 */
export function combineFixes(fixes: LLMGeneratedFix[]): LLMGeneratedFix {
  if (fixes.length === 0) {
    return {
      description: "No fixes available",
      explanation: "Could not generate any fixes for this error",
      confidence: 0,
      isLLMGenerated: false,
    };
  }

  if (fixes.length === 1) {
    return fixes[0];
  }

  // Take highest confidence fix as primary
  const sorted = [...fixes].sort((a, b) => b.confidence - a.confidence);
  const primary = sorted[0];

  // Others become alternatives
  const alternatives = sorted.slice(1).map((fix) => ({
    description: fix.description,
    suggestedCode: fix.suggestedCode,
  }));

  return {
    ...primary,
    alternatives: [
      ...(primary.alternatives ?? []),
      ...alternatives,
    ],
  };
}
