#!/usr/bin/env node
/**
 * CLI Brand Generate Command (Feature #77)
 *
 * Generates a brand kit package scaffold with template files.
 *
 * @example
 * ```bash
 * npx @platxa/frontend-agent generate my-brand-kit
 * # or
 * platxa-generate @acme/brand-kit --preset blue
 * ```
 *
 * @module cli/generate
 */

import * as fs from "node:fs"
import * as path from "node:path"
import * as readline from "node:readline"

// =============================================================================
// TYPES
// =============================================================================

interface GenerateOptions {
  /** Package name */
  name: string
  /** Output directory */
  outputDir: string
  /** Base preset to use */
  preset: "default" | "blue" | "green" | "violet"
  /** Primary hue (0-360) */
  primaryHue: number
  /** Include TypeScript */
  typescript: boolean
  /** Include CSS file */
  includeCss: boolean
  /** Include Tailwind preset */
  includeTailwind: boolean
  /** Author name */
  author?: string
  /** Description */
  description?: string
}

interface GenerateResult {
  success: boolean
  outputDir: string
  files: string[]
  error?: string
}

// =============================================================================
// PRESET CONFIGURATIONS
// =============================================================================

const PRESET_CONFIGS = {
  default: {
    primaryHue: 222,
    accentHue: 262,
    name: "Default (Blue-Violet)",
  },
  blue: {
    primaryHue: 217,
    accentHue: 199,
    name: "Blue (Ocean)",
  },
  green: {
    primaryHue: 142,
    accentHue: 160,
    name: "Green (Nature)",
  },
  violet: {
    primaryHue: 262,
    accentHue: 292,
    name: "Violet (Royal)",
  },
} as const

// =============================================================================
// TEMPLATES
// =============================================================================

function generatePackageJson(options: GenerateOptions): string {
  const pkg = {
    name: options.name,
    version: "1.0.0",
    description: options.description || `Brand kit for ${options.name}`,
    author: options.author || "",
    license: "MIT",
    type: "module",
    main: options.typescript ? "./dist/index.js" : "./index.js",
    types: options.typescript ? "./dist/index.d.ts" : undefined,
    exports: {
      ".": {
        types: options.typescript ? "./dist/index.d.ts" : undefined,
        import: options.typescript ? "./dist/index.js" : "./index.js",
        require: options.typescript ? "./dist/index.cjs" : "./index.cjs",
      },
    },
    files: options.typescript ? ["dist", "src"] : ["index.js", "index.cjs"],
    scripts: options.typescript
      ? {
          build: "tsc",
          prepublishOnly: "npm run build",
        }
      : {},
    peerDependencies: {
      "@platxa/frontend-agent": "^1.0.0",
    },
    devDependencies: options.typescript
      ? {
          typescript: "^5.0.0",
          "@platxa/frontend-agent": "^1.0.0",
        }
      : {
          "@platxa/frontend-agent": "^1.0.0",
        },
    keywords: ["platxa", "brand-kit", "design-tokens", "theme"],
  }

  // Remove undefined values
  const cleaned = JSON.parse(JSON.stringify(pkg))
  return JSON.stringify(cleaned, null, 2)
}

function generateTsConfig(): string {
  return JSON.stringify(
    {
      compilerOptions: {
        target: "ES2020",
        module: "ESNext",
        moduleResolution: "bundler",
        declaration: true,
        declarationMap: true,
        strict: true,
        esModuleInterop: true,
        skipLibCheck: true,
        outDir: "./dist",
        rootDir: "./src",
      },
      include: ["src/**/*"],
      exclude: ["node_modules", "dist"],
    },
    null,
    2
  )
}

function generateIndexTs(options: GenerateOptions): string {
  const preset = PRESET_CONFIGS[options.preset]
  const primaryHue = options.primaryHue || preset.primaryHue
  const accentHue = preset.accentHue

  return `/**
 * ${options.name} Brand Kit
 *
 * Generated by @platxa/frontend-agent
 * Preset: ${options.preset}
 *
 * @packageDocumentation
 */

import type { BrandKitExport } from "@platxa/frontend-agent"

// =============================================================================
// METADATA
// =============================================================================

export const meta = {
  name: "${options.name}",
  version: "1.0.0",
  description: "${options.description || `Brand kit for ${options.name}`}",
  author: "${options.author || ""}",
} as const

// =============================================================================
// COLOR PRIMITIVES
// =============================================================================

/**
 * Primary color scale (12 steps)
 * Hue: ${primaryHue}
 */
export const primary = {
  50: "oklch(0.97 0.02 ${primaryHue})",
  100: "oklch(0.93 0.04 ${primaryHue})",
  200: "oklch(0.86 0.08 ${primaryHue})",
  300: "oklch(0.76 0.12 ${primaryHue})",
  400: "oklch(0.66 0.16 ${primaryHue})",
  500: "oklch(0.55 0.18 ${primaryHue})",
  600: "oklch(0.47 0.17 ${primaryHue})",
  700: "oklch(0.40 0.15 ${primaryHue})",
  800: "oklch(0.33 0.12 ${primaryHue})",
  900: "oklch(0.27 0.09 ${primaryHue})",
  950: "oklch(0.20 0.06 ${primaryHue})",
} as const

/**
 * Accent color scale (12 steps)
 * Hue: ${accentHue}
 */
export const accent = {
  50: "oklch(0.97 0.02 ${accentHue})",
  100: "oklch(0.93 0.04 ${accentHue})",
  200: "oklch(0.86 0.08 ${accentHue})",
  300: "oklch(0.76 0.12 ${accentHue})",
  400: "oklch(0.66 0.16 ${accentHue})",
  500: "oklch(0.55 0.18 ${accentHue})",
  600: "oklch(0.47 0.17 ${accentHue})",
  700: "oklch(0.40 0.15 ${accentHue})",
  800: "oklch(0.33 0.12 ${accentHue})",
  900: "oklch(0.27 0.09 ${accentHue})",
  950: "oklch(0.20 0.06 ${accentHue})",
} as const

/**
 * Neutral color scale (12 steps)
 */
export const neutral = {
  50: "oklch(0.98 0.005 ${primaryHue})",
  100: "oklch(0.95 0.005 ${primaryHue})",
  200: "oklch(0.90 0.005 ${primaryHue})",
  300: "oklch(0.82 0.005 ${primaryHue})",
  400: "oklch(0.70 0.01 ${primaryHue})",
  500: "oklch(0.55 0.01 ${primaryHue})",
  600: "oklch(0.45 0.01 ${primaryHue})",
  700: "oklch(0.37 0.01 ${primaryHue})",
  800: "oklch(0.27 0.01 ${primaryHue})",
  900: "oklch(0.20 0.01 ${primaryHue})",
  950: "oklch(0.14 0.01 ${primaryHue})",
} as const

export const primitives = {
  primary,
  accent,
  neutral,
} as const

// =============================================================================
// SEMANTIC COLORS
// =============================================================================

/**
 * Light mode semantic colors
 */
export const lightColors = {
  background: "oklch(0.99 0.002 ${primaryHue})",
  foreground: "oklch(0.15 0.01 ${primaryHue})",

  card: "oklch(1 0 0)",
  cardForeground: "oklch(0.15 0.01 ${primaryHue})",

  popover: "oklch(1 0 0)",
  popoverForeground: "oklch(0.15 0.01 ${primaryHue})",

  primary: primary[600],
  primaryForeground: "oklch(0.99 0 0)",

  secondary: neutral[100],
  secondaryForeground: neutral[900],

  muted: neutral[100],
  mutedForeground: neutral[500],

  accent: accent[100],
  accentForeground: accent[900],

  destructive: "oklch(0.55 0.22 25)",
  destructiveForeground: "oklch(0.99 0 0)",

  border: neutral[200],
  input: neutral[200],
  ring: primary[500],
} as const

/**
 * Dark mode semantic colors
 */
export const darkColors = {
  background: "oklch(0.14 0.01 ${primaryHue})",
  foreground: "oklch(0.95 0.005 ${primaryHue})",

  card: "oklch(0.17 0.01 ${primaryHue})",
  cardForeground: "oklch(0.95 0.005 ${primaryHue})",

  popover: "oklch(0.17 0.01 ${primaryHue})",
  popoverForeground: "oklch(0.95 0.005 ${primaryHue})",

  primary: primary[500],
  primaryForeground: "oklch(0.12 0.01 ${primaryHue})",

  secondary: neutral[800],
  secondaryForeground: neutral[100],

  muted: neutral[800],
  mutedForeground: neutral[400],

  accent: accent[800],
  accentForeground: accent[100],

  destructive: "oklch(0.60 0.20 25)",
  destructiveForeground: "oklch(0.99 0 0)",

  border: neutral[800],
  input: neutral[800],
  ring: primary[400],
} as const

export const semantics = {
  light: lightColors,
  dark: darkColors,
} as const

// =============================================================================
// TYPOGRAPHY (Optional)
// =============================================================================

export const typography = {
  fontFamily: {
    sans: ["Inter", "system-ui", "sans-serif"],
    mono: ["JetBrains Mono", "Consolas", "monospace"],
  },
  fontSize: {
    xs: "0.75rem",
    sm: "0.875rem",
    base: "1rem",
    lg: "1.125rem",
    xl: "1.25rem",
    "2xl": "1.5rem",
    "3xl": "1.875rem",
    "4xl": "2.25rem",
  },
  fontWeight: {
    normal: "400",
    medium: "500",
    semibold: "600",
    bold: "700",
  },
  lineHeight: {
    tight: "1.25",
    normal: "1.5",
    relaxed: "1.75",
  },
} as const

// =============================================================================
// SPACING (Optional)
// =============================================================================

export const spacing = {
  px: "1px",
  0: "0",
  0.5: "0.125rem",
  1: "0.25rem",
  1.5: "0.375rem",
  2: "0.5rem",
  2.5: "0.625rem",
  3: "0.75rem",
  3.5: "0.875rem",
  4: "1rem",
  5: "1.25rem",
  6: "1.5rem",
  7: "1.75rem",
  8: "2rem",
  9: "2.25rem",
  10: "2.5rem",
  12: "3rem",
  14: "3.5rem",
  16: "4rem",
  20: "5rem",
  24: "6rem",
  28: "7rem",
  32: "8rem",
} as const

// =============================================================================
// RADIUS (Optional)
// =============================================================================

export const radius = {
  none: "0",
  sm: "0.125rem",
  default: "0.25rem",
  md: "0.375rem",
  lg: "0.5rem",
  xl: "0.75rem",
  "2xl": "1rem",
  "3xl": "1.5rem",
  full: "9999px",
} as const

// =============================================================================
// SHADOW (Optional)
// =============================================================================

export const shadow = {
  sm: "0 1px 2px 0 rgb(0 0 0 / 0.05)",
  default: "0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1)",
  md: "0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)",
  lg: "0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)",
  xl: "0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1)",
  "2xl": "0 25px 50px -12px rgb(0 0 0 / 0.25)",
  inner: "inset 0 2px 4px 0 rgb(0 0 0 / 0.05)",
  none: "none",
} as const

// =============================================================================
// TAILWIND PRESET (Optional)
// =============================================================================

export const tailwindPreset = {
  theme: {
    extend: {
      colors: {
        primary: primitives.primary,
        accent: primitives.accent,
        neutral: primitives.neutral,
      },
      borderRadius: radius,
      boxShadow: shadow,
    },
  },
} as const

// =============================================================================
// EXPORT
// =============================================================================

/**
 * Complete brand kit export
 */
const brandKit: BrandKitExport = {
  meta,
  primitives,
  semantics,
  typography,
  spacing,
  radius,
  shadow,
  tailwindPreset,
}

export default brandKit
`
}

function generateIndexJs(options: GenerateOptions): string {
  const preset = PRESET_CONFIGS[options.preset]
  const primaryHue = options.primaryHue || preset.primaryHue
  const accentHue = preset.accentHue

  return `/**
 * ${options.name} Brand Kit
 *
 * Generated by @platxa/frontend-agent
 * Preset: ${options.preset}
 */

// =============================================================================
// METADATA
// =============================================================================

const meta = {
  name: "${options.name}",
  version: "1.0.0",
  description: "${options.description || `Brand kit for ${options.name}`}",
  author: "${options.author || ""}",
}

// =============================================================================
// COLOR PRIMITIVES
// =============================================================================

const primary = {
  50: "oklch(0.97 0.02 ${primaryHue})",
  100: "oklch(0.93 0.04 ${primaryHue})",
  200: "oklch(0.86 0.08 ${primaryHue})",
  300: "oklch(0.76 0.12 ${primaryHue})",
  400: "oklch(0.66 0.16 ${primaryHue})",
  500: "oklch(0.55 0.18 ${primaryHue})",
  600: "oklch(0.47 0.17 ${primaryHue})",
  700: "oklch(0.40 0.15 ${primaryHue})",
  800: "oklch(0.33 0.12 ${primaryHue})",
  900: "oklch(0.27 0.09 ${primaryHue})",
  950: "oklch(0.20 0.06 ${primaryHue})",
}

const accent = {
  50: "oklch(0.97 0.02 ${accentHue})",
  100: "oklch(0.93 0.04 ${accentHue})",
  200: "oklch(0.86 0.08 ${accentHue})",
  300: "oklch(0.76 0.12 ${accentHue})",
  400: "oklch(0.66 0.16 ${accentHue})",
  500: "oklch(0.55 0.18 ${accentHue})",
  600: "oklch(0.47 0.17 ${accentHue})",
  700: "oklch(0.40 0.15 ${accentHue})",
  800: "oklch(0.33 0.12 ${accentHue})",
  900: "oklch(0.27 0.09 ${accentHue})",
  950: "oklch(0.20 0.06 ${accentHue})",
}

const neutral = {
  50: "oklch(0.98 0.005 ${primaryHue})",
  100: "oklch(0.95 0.005 ${primaryHue})",
  200: "oklch(0.90 0.005 ${primaryHue})",
  300: "oklch(0.82 0.005 ${primaryHue})",
  400: "oklch(0.70 0.01 ${primaryHue})",
  500: "oklch(0.55 0.01 ${primaryHue})",
  600: "oklch(0.45 0.01 ${primaryHue})",
  700: "oklch(0.37 0.01 ${primaryHue})",
  800: "oklch(0.27 0.01 ${primaryHue})",
  900: "oklch(0.20 0.01 ${primaryHue})",
  950: "oklch(0.14 0.01 ${primaryHue})",
}

const primitives = { primary, accent, neutral }

// =============================================================================
// SEMANTIC COLORS
// =============================================================================

const lightColors = {
  background: "oklch(0.99 0.002 ${primaryHue})",
  foreground: "oklch(0.15 0.01 ${primaryHue})",
  card: "oklch(1 0 0)",
  cardForeground: "oklch(0.15 0.01 ${primaryHue})",
  popover: "oklch(1 0 0)",
  popoverForeground: "oklch(0.15 0.01 ${primaryHue})",
  primary: primary[600],
  primaryForeground: "oklch(0.99 0 0)",
  secondary: neutral[100],
  secondaryForeground: neutral[900],
  muted: neutral[100],
  mutedForeground: neutral[500],
  accent: accent[100],
  accentForeground: accent[900],
  destructive: "oklch(0.55 0.22 25)",
  destructiveForeground: "oklch(0.99 0 0)",
  border: neutral[200],
  input: neutral[200],
  ring: primary[500],
}

const darkColors = {
  background: "oklch(0.14 0.01 ${primaryHue})",
  foreground: "oklch(0.95 0.005 ${primaryHue})",
  card: "oklch(0.17 0.01 ${primaryHue})",
  cardForeground: "oklch(0.95 0.005 ${primaryHue})",
  popover: "oklch(0.17 0.01 ${primaryHue})",
  popoverForeground: "oklch(0.95 0.005 ${primaryHue})",
  primary: primary[500],
  primaryForeground: "oklch(0.12 0.01 ${primaryHue})",
  secondary: neutral[800],
  secondaryForeground: neutral[100],
  muted: neutral[800],
  mutedForeground: neutral[400],
  accent: accent[800],
  accentForeground: accent[100],
  destructive: "oklch(0.60 0.20 25)",
  destructiveForeground: "oklch(0.99 0 0)",
  border: neutral[800],
  input: neutral[800],
  ring: primary[400],
}

const semantics = { light: lightColors, dark: darkColors }

// =============================================================================
// OPTIONAL TOKENS
// =============================================================================

const typography = {
  fontFamily: {
    sans: ["Inter", "system-ui", "sans-serif"],
    mono: ["JetBrains Mono", "Consolas", "monospace"],
  },
}

const spacing = {
  px: "1px", 0: "0", 1: "0.25rem", 2: "0.5rem", 3: "0.75rem", 4: "1rem",
  5: "1.25rem", 6: "1.5rem", 8: "2rem", 10: "2.5rem", 12: "3rem", 16: "4rem",
}

const radius = {
  none: "0", sm: "0.125rem", default: "0.25rem", md: "0.375rem",
  lg: "0.5rem", xl: "0.75rem", "2xl": "1rem", full: "9999px",
}

const shadow = {
  sm: "0 1px 2px 0 rgb(0 0 0 / 0.05)",
  default: "0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1)",
  md: "0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)",
  lg: "0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)",
  none: "none",
}

const tailwindPreset = {
  theme: {
    extend: {
      colors: { primary, accent, neutral },
      borderRadius: radius,
      boxShadow: shadow,
    },
  },
}

// =============================================================================
// EXPORT
// =============================================================================

module.exports = {
  meta,
  primitives,
  semantics,
  typography,
  spacing,
  radius,
  shadow,
  tailwindPreset,
}

module.exports.default = module.exports
`
}

function generateReadme(options: GenerateOptions): string {
  return `# ${options.name}

${options.description || `Brand kit for ${options.name}`}

Generated by [@platxa/frontend-agent](https://github.com/platxa/frontend-agent)

## Installation

\`\`\`bash
npm install ${options.name}
# or
pnpm add ${options.name}
\`\`\`

## Usage

### With BrandProvider

\`\`\`tsx
import { BrandProvider } from "@platxa/frontend-agent"

function App() {
  return (
    <BrandProvider brandPackage="${options.name}">
      <YourApp />
    </BrandProvider>
  )
}
\`\`\`

### Direct Import

\`\`\`typescript
import brandKit from "${options.name}"

// Access colors
console.log(brandKit.primitives.primary[500])
console.log(brandKit.semantics.light.background)

// Access design tokens
console.log(brandKit.typography)
console.log(brandKit.spacing)
\`\`\`

### With Tailwind CSS

Add the preset to your \`tailwind.config.js\`:

\`\`\`javascript
import brandKit from "${options.name}"

export default {
  presets: [brandKit.tailwindPreset],
  // ... rest of config
}
\`\`\`

## Customization

Edit the source files to customize:

- \`${options.typescript ? "src/index.ts" : "index.js"}\` - Main brand kit definition
- Color primitives (primary, accent, neutral scales)
- Semantic colors (light/dark mode)
- Typography, spacing, radius, shadow tokens

## Validation

Validate your brand kit:

\`\`\`bash
npx @platxa/frontend-agent validate .
\`\`\`

## License

MIT
`
}

function generateGitignore(): string {
  return `node_modules/
dist/
*.log
.DS_Store
`
}

// =============================================================================
// PROMPTS
// =============================================================================

function createPrompt(): readline.Interface {
  return readline.createInterface({
    input: process.stdin,
    output: process.stdout,
  })
}

function ask(rl: readline.Interface, question: string): Promise<string> {
  return new Promise((resolve) => {
    rl.question(question, (answer) => resolve(answer.trim()))
  })
}

async function askYesNo(
  rl: readline.Interface,
  question: string,
  defaultValue: boolean = true
): Promise<boolean> {
  const hint = defaultValue ? "[Y/n]" : "[y/N]"
  const answer = await ask(rl, `${question} ${hint} `)
  if (answer === "") return defaultValue
  return answer.toLowerCase().startsWith("y")
}

async function askChoice<T extends string>(
  rl: readline.Interface,
  question: string,
  options: readonly T[],
  defaultIndex: number = 0
): Promise<T> {
  console.log(question)
  options.forEach((opt, i) => {
    const marker = i === defaultIndex ? ">" : " "
    console.log(`  ${marker} ${i + 1}. ${opt}`)
  })

  const answer = await ask(rl, `Choice [${defaultIndex + 1}]: `)
  if (answer === "") return options[defaultIndex]

  const index = parseInt(answer, 10) - 1
  if (index >= 0 && index < options.length) {
    return options[index]
  }
  return options[defaultIndex]
}

// =============================================================================
// MAIN GENERATE FUNCTION
// =============================================================================

/**
 * Run interactive prompts for generation options
 */
async function runInteractivePrompts(
  initialName?: string
): Promise<GenerateOptions> {
  const rl = createPrompt()

  console.log("\n🎨 Platxa Brand Kit Generator\n")
  console.log("This will create a new brand kit package.\n")

  try {
    // Package name
    const defaultName = initialName || "my-brand-kit"
    const name = (await ask(rl, `Package name [${defaultName}]: `)) || defaultName

    // Output directory
    const defaultDir = name.replace(/^@[^/]+\//, "")
    const outputDir =
      (await ask(rl, `Output directory [./${defaultDir}]: `)) ||
      `./${defaultDir}`

    // Description
    const description = await ask(rl, "Description (optional): ")

    // Author
    const author = await ask(rl, "Author (optional): ")

    // Preset
    const presetOptions = ["default", "blue", "green", "violet"] as const
    console.log("\nPreset colors:")
    for (const p of presetOptions) {
      const config = PRESET_CONFIGS[p]
      console.log(`  - ${p}: ${config.name}`)
    }
    const preset = await askChoice(rl, "\nSelect preset:", presetOptions, 0)

    // Primary hue override
    const hueStr = await ask(
      rl,
      `Primary hue (0-360) [${PRESET_CONFIGS[preset].primaryHue}]: `
    )
    const primaryHue = hueStr
      ? parseInt(hueStr, 10)
      : PRESET_CONFIGS[preset].primaryHue

    // TypeScript
    const typescript = await askYesNo(rl, "\nUse TypeScript?", true)

    // Include CSS
    const includeCss = await askYesNo(rl, "Include CSS file?", false)

    // Include Tailwind preset
    const includeTailwind = await askYesNo(rl, "Include Tailwind preset?", true)

    rl.close()

    return {
      name,
      outputDir,
      preset,
      primaryHue,
      typescript,
      includeCss,
      includeTailwind,
      author: author || undefined,
      description: description || undefined,
    }
  } catch (error) {
    rl.close()
    throw error
  }
}

/**
 * Generate brand kit scaffold (Feature #77)
 *
 * @param options - Generation options
 * @returns Generation result
 */
export async function generateBrandKit(
  options: GenerateOptions
): Promise<GenerateResult> {
  const files: string[] = []

  try {
    // Create output directory
    const outDir = path.resolve(process.cwd(), options.outputDir)

    if (fs.existsSync(outDir)) {
      const contents = fs.readdirSync(outDir)
      if (contents.length > 0) {
        return {
          success: false,
          outputDir: outDir,
          files: [],
          error: `Directory "${options.outputDir}" is not empty`,
        }
      }
    } else {
      fs.mkdirSync(outDir, { recursive: true })
    }

    // Generate package.json
    const pkgJson = generatePackageJson(options)
    fs.writeFileSync(path.join(outDir, "package.json"), pkgJson)
    files.push("package.json")

    // Generate main source file
    if (options.typescript) {
      const srcDir = path.join(outDir, "src")
      fs.mkdirSync(srcDir, { recursive: true })

      const indexTs = generateIndexTs(options)
      fs.writeFileSync(path.join(srcDir, "index.ts"), indexTs)
      files.push("src/index.ts")

      // Generate tsconfig
      const tsconfig = generateTsConfig()
      fs.writeFileSync(path.join(outDir, "tsconfig.json"), tsconfig)
      files.push("tsconfig.json")
    } else {
      const indexJs = generateIndexJs(options)
      fs.writeFileSync(path.join(outDir, "index.js"), indexJs)
      files.push("index.js")
    }

    // Generate README
    const readme = generateReadme(options)
    fs.writeFileSync(path.join(outDir, "README.md"), readme)
    files.push("README.md")

    // Generate .gitignore
    const gitignore = generateGitignore()
    fs.writeFileSync(path.join(outDir, ".gitignore"), gitignore)
    files.push(".gitignore")

    console.log(`\n✅ Generated brand kit at ${options.outputDir}\n`)
    console.log("Files created:")
    files.forEach((f) => console.log(`  • ${f}`))

    console.log("\nNext steps:")
    console.log(`  1. cd ${options.outputDir}`)
    console.log("  2. npm install")
    if (options.typescript) {
      console.log("  3. npm run build")
    }
    console.log(`  ${options.typescript ? "4" : "3"}. Customize colors in ${options.typescript ? "src/index.ts" : "index.js"}`)
    console.log("")

    return {
      success: true,
      outputDir: outDir,
      files,
    }
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error)
    return {
      success: false,
      outputDir: options.outputDir,
      files,
      error: message,
    }
  }
}

// =============================================================================
// CLI ENTRY POINT
// =============================================================================

/**
 * CLI entry point
 */
export async function main(): Promise<void> {
  const args = process.argv.slice(2)

  // Handle help
  if (args.includes("--help") || args.includes("-h")) {
    console.log(`
Usage: platxa-generate [name] [options]

Generate a brand kit package scaffold.

Arguments:
  name                 Package name (e.g., @acme/brand-kit)

Options:
  --output, -o <dir>   Output directory (default: derived from name)
  --preset <name>      Color preset (default, blue, green, violet)
  --hue <number>       Primary hue (0-360)
  --typescript, --ts   Generate TypeScript (default: true)
  --javascript, --js   Generate JavaScript
  --author <name>      Package author
  --description <text> Package description
  -h, --help           Show this help message

Examples:
  platxa-generate my-brand-kit
  platxa-generate @acme/brand-kit --preset blue
  platxa-generate my-brand --hue 180 --js
`)
    process.exit(0)
  }

  // Parse CLI args
  let name: string | undefined
  let outputDir: string | undefined
  let preset: GenerateOptions["preset"] = "default"
  let primaryHue: number | undefined
  let typescript = true
  let author: string | undefined
  let description: string | undefined

  for (let i = 0; i < args.length; i++) {
    const arg = args[i]

    if (arg === "--output" || arg === "-o") {
      outputDir = args[++i]
    } else if (arg === "--preset") {
      const p = args[++i]
      if (["default", "blue", "green", "violet"].includes(p)) {
        preset = p as GenerateOptions["preset"]
      }
    } else if (arg === "--hue") {
      primaryHue = parseInt(args[++i], 10)
    } else if (arg === "--typescript" || arg === "--ts") {
      typescript = true
    } else if (arg === "--javascript" || arg === "--js") {
      typescript = false
    } else if (arg === "--author") {
      author = args[++i]
    } else if (arg === "--description") {
      description = args[++i]
    } else if (!arg.startsWith("-") && !name) {
      name = arg
    }
  }

  // If no name provided, run interactive mode
  if (!name) {
    const options = await runInteractivePrompts()
    const result = await generateBrandKit(options)
    process.exit(result.success ? 0 : 1)
  }

  // Non-interactive mode
  const options: GenerateOptions = {
    name,
    outputDir: outputDir || `./${name.replace(/^@[^/]+\//, "")}`,
    preset,
    primaryHue: primaryHue || PRESET_CONFIGS[preset].primaryHue,
    typescript,
    includeCss: false,
    includeTailwind: true,
    author,
    description,
  }

  const result = await generateBrandKit(options)

  if (!result.success) {
    console.error(`\n❌ Error: ${result.error}\n`)
  }

  process.exit(result.success ? 0 : 1)
}

// Run if executed directly
const isMain =
  typeof require !== "undefined"
    ? require.main === module
    : import.meta.url === `file://${process.argv[1]}`

if (isMain) {
  main().catch((err) => {
    console.error("Error:", err.message)
    process.exit(1)
  })
}
