/**
 * SCSS Transformer
 *
 * Transforms brand tokens (OKLCH palette) into Odoo-compatible SCSS:
 * - $o-color-1 through $o-color-5 palette variables
 * - Bootstrap variable overrides ($primary, $secondary, etc.)
 * - Custom SCSS variables for the theme
 */

import type { BrandTokenContext } from "./types";
import { generateLightnessScale } from "./color-mapper";

// =============================================================================
// Odoo Color Palette SCSS
// =============================================================================

/**
 * Maps brand tokens to Odoo's $o-color-N palette system.
 *
 * Odoo uses $o-color-1 through $o-color-5 as the canonical palette.
 * These feed into o_cc1-o_cc5 CSS classes used by the website builder.
 *
 * Mapping:
 *   $o-color-1 = primary
 *   $o-color-2 = secondary
 *   $o-color-3 = accent (extra/highlight)
 *   $o-color-4 = background (light)
 *   $o-color-5 = text (dark)
 */
export function generateOdooColorVariables(tokens: BrandTokenContext): string {
  const { colors } = tokens;

  const lines = [
    "// =============================================================================",
    "// Odoo Color Palette (auto-generated by Platxa Agent Bridge)",
    "// =============================================================================",
    "",
    `$o-color-1: ${colors.primary};`,
    `$o-color-2: ${colors.secondary};`,
    `$o-color-3: ${colors.accent};`,
    `$o-color-4: ${colors.background};`,
    `$o-color-5: ${colors.text};`,
    "",
    "// Odoo color palettes map",
    "$o-color-palettes: (",
    "  1: $o-color-1,",
    "  2: $o-color-2,",
    "  3: $o-color-3,",
    "  4: $o-color-4,",
    "  5: $o-color-5,",
    ") !default;",
  ];

  return lines.join("\n");
}

// =============================================================================
// Bootstrap Variable Overrides
// =============================================================================

/**
 * Generates Bootstrap 5 variable overrides from brand tokens.
 * These override Bootstrap's defaults when included before bootstrap.scss.
 */
export function generateBootstrapOverrides(tokens: BrandTokenContext): string {
  const { colors } = tokens;

  const lines = [
    "// =============================================================================",
    "// Bootstrap Overrides (auto-generated by Platxa Agent Bridge)",
    "// =============================================================================",
    "",
    `$primary: ${colors.primary};`,
    `$secondary: ${colors.secondary};`,
    `$success: ${colors.success};`,
    `$info: ${colors.info};`,
    `$warning: ${colors.warning};`,
    `$danger: ${colors.error};`,
    `$light: ${colors.background};`,
    `$dark: ${colors.text};`,
    "",
    "// Body",
    `$body-bg: ${colors.background};`,
    `$body-color: ${colors.text};`,
    "",
    "// Links",
    `$link-color: ${colors.primary};`,
  ];

  // Typography overrides
  if (tokens.typography) {
    lines.push("");
    lines.push("// Typography");
    lines.push(`$font-family-sans-serif: "${tokens.typography.bodyFamily}", system-ui, -apple-system, sans-serif;`);
    lines.push(`$headings-font-family: "${tokens.typography.headingFamily}", system-ui, -apple-system, sans-serif;`);
  }

  return lines.join("\n");
}

// =============================================================================
// Full Theme SCSS
// =============================================================================

export interface OdooScssOutput {
  /** primary_variables.scss - Odoo color palette */
  variables: string;
  /** bootstrap_overridden.scss - Bootstrap overrides */
  overrides: string;
  /** color_scale.scss - Full lightness scale (optional) */
  colorScale: string;
}

/**
 * Generates all Odoo SCSS files from brand tokens.
 */
export function transformToOdooScss(tokens: BrandTokenContext): OdooScssOutput {
  const variables = generateOdooColorVariables(tokens);
  const overrides = generateBootstrapOverrides(tokens);
  const colorScale = generateColorScale(tokens);

  return { variables, overrides, colorScale };
}

/**
 * Generates a full lightness scale for the primary color.
 * Useful for detailed theme customization.
 */
function generateColorScale(tokens: BrandTokenContext): string {
  const scale = generateLightnessScale(tokens.colors.primary);

  const lines = [
    "// =============================================================================",
    "// Primary Color Scale (auto-generated by Platxa Agent Bridge)",
    "// =============================================================================",
    "",
    "// 50-950 lightness scale derived from OKLCH color space",
  ];

  for (const [step, hex] of Object.entries(scale)) {
    lines.push(`$primary-${step}: ${hex};`);
  }

  lines.push("");
  lines.push("$primary-scale: (");
  for (const [step, hex] of Object.entries(scale)) {
    lines.push(`  ${step}: ${hex},`);
  }
  lines.push(");");

  return lines.join("\n");
}
