/**
 * Odoo Default Theme Template
 *
 * Matches Odoo 16/17 default website theme styling.
 * Uses Odoo's standard variables, Bootstrap integration,
 * and official color palette.
 *
 * Features:
 * - Odoo 17 default purple primary color
 * - Bootstrap 5 integration
 * - Odoo-specific component classes
 * - Standard snippet compatibility
 * - Official icon set support
 *
 * Feature #65: Theme System - Odoo Default Theme
 */

import type { ThemeTemplate, ColorScheme, Typography, Spacing, LayoutOptions } from "../../theme-registry";

// =============================================================================
// Theme Configuration
// =============================================================================

/** Odoo default color scheme (Odoo 17) */
export const odooDefaultColors: ColorScheme = {
  primary: "#714B67",      // Odoo purple
  secondary: "#017E84",    // Odoo teal
  background: "#ffffff",
  surface: "#f8f9fa",
  text: "#212529",
  textMuted: "#6c757d",
  border: "#dee2e6",
  success: "#28a745",
  warning: "#ffc107",
  error: "#dc3545",
};

/** Odoo default typography */
export const odooDefaultTypography: Typography = {
  headingFont: "Roboto, system-ui, -apple-system, sans-serif",
  bodyFont: "Roboto, system-ui, -apple-system, sans-serif",
  baseFontSize: "1rem",
  lineHeight: "1.5",
  headingWeight: "500",
};

/** Odoo default spacing */
export const odooDefaultSpacing: Spacing = {
  sectionPadding: "48px",
  containerWidth: "1320px",
  gap: "1.5rem",
  borderRadius: "0.375rem",
};

/** Odoo default layout */
export const odooDefaultLayout: LayoutOptions = {
  headerStyle: "sticky",
  navStyle: "horizontal",
  footerColumns: 4,
};

// =============================================================================
// Theme Template Definition
// =============================================================================

/** Odoo Default theme template */
export const odooDefaultTheme: ThemeTemplate = {
  id: "odoo-default",
  name: "Odoo Default",
  description: "Matches Odoo 16/17 default website theme. Perfect for seamless integration with Odoo's standard modules and maintaining visual consistency with the Odoo ecosystem.",
  category: "business",
  tags: ["odoo", "default", "standard", "bootstrap", "official", "compatible"],
  previewImage: "/themes/odoo-default/preview.png",
  thumbnail: "/themes/odoo-default/thumb.png",
  colors: odooDefaultColors,
  typography: odooDefaultTypography,
  spacing: odooDefaultSpacing,
  layout: odooDefaultLayout,
  isPremium: false,
  version: "17.0.0",
  author: "Platxa Studio",
  updatedAt: new Date("2024-02-25"),
  odooVersion: "17.0",
};

// =============================================================================
// Odoo-Specific Variables
// =============================================================================

/** Odoo brand colors */
export const odooBrandColors = {
  purple: "#714B67",
  teal: "#017E84",
  darkPurple: "#4B3049",
  lightPurple: "#E8D5E4",
  lightTeal: "#D4EEEF",
};

/** Odoo grayscale */
export const odooGrayscale = {
  white: "#ffffff",
  100: "#f8f9fa",
  200: "#e9ecef",
  300: "#dee2e6",
  400: "#ced4da",
  500: "#adb5bd",
  600: "#6c757d",
  700: "#495057",
  800: "#343a40",
  900: "#212529",
  black: "#000000",
};

/** Bootstrap 5 breakpoints */
export const odooBreakpoints = {
  xs: "0",
  sm: "576px",
  md: "768px",
  lg: "992px",
  xl: "1200px",
  xxl: "1400px",
};

// =============================================================================
// SCSS Generation
// =============================================================================

/** Generate Odoo default theme SCSS */
export function generateOdooDefaultSCSS(): string {
  return `
// =============================================================================
// Odoo Default Theme
// Matches Odoo 16/17 default website styling
// Generated by Platxa Studio
// =============================================================================

// -----------------------------------------------------------------------------
// Odoo Brand Colors
// -----------------------------------------------------------------------------

$o-brand-primary: ${odooBrandColors.purple};
$o-brand-secondary: ${odooBrandColors.teal};
$o-brand-odoo: $o-brand-primary;

// Brand shades
$o-brand-lighten: ${odooBrandColors.lightPurple};
$o-brand-darken: ${odooBrandColors.darkPurple};

// -----------------------------------------------------------------------------
// Bootstrap Color Overrides
// -----------------------------------------------------------------------------

$primary: $o-brand-primary;
$secondary: $o-brand-secondary;
$success: ${odooDefaultColors.success};
$info: $o-brand-secondary;
$warning: ${odooDefaultColors.warning};
$danger: ${odooDefaultColors.error};
$light: ${odooGrayscale[100]};
$dark: ${odooGrayscale[900]};

// Gray scale
$white: ${odooGrayscale.white};
$gray-100: ${odooGrayscale[100]};
$gray-200: ${odooGrayscale[200]};
$gray-300: ${odooGrayscale[300]};
$gray-400: ${odooGrayscale[400]};
$gray-500: ${odooGrayscale[500]};
$gray-600: ${odooGrayscale[600]};
$gray-700: ${odooGrayscale[700]};
$gray-800: ${odooGrayscale[800]};
$gray-900: ${odooGrayscale[900]};
$black: ${odooGrayscale.black};

// -----------------------------------------------------------------------------
// Typography
// -----------------------------------------------------------------------------

$font-family-sans-serif: ${odooDefaultTypography.bodyFont};
$font-family-base: $font-family-sans-serif;
$font-size-base: ${odooDefaultTypography.baseFontSize};
$line-height-base: ${odooDefaultTypography.lineHeight};
$headings-font-weight: ${odooDefaultTypography.headingWeight};

// Font sizes
$h1-font-size: 2.5rem;
$h2-font-size: 2rem;
$h3-font-size: 1.75rem;
$h4-font-size: 1.5rem;
$h5-font-size: 1.25rem;
$h6-font-size: 1rem;

// -----------------------------------------------------------------------------
// Spacing
// -----------------------------------------------------------------------------

$spacer: 1rem;
$spacers: (
  0: 0,
  1: $spacer * 0.25,
  2: $spacer * 0.5,
  3: $spacer,
  4: $spacer * 1.5,
  5: $spacer * 3,
);

// Container
$container-max-widths: (
  sm: 540px,
  md: 720px,
  lg: 960px,
  xl: 1140px,
  xxl: ${odooDefaultSpacing.containerWidth},
);

// -----------------------------------------------------------------------------
// Components
// -----------------------------------------------------------------------------

$border-radius: ${odooDefaultSpacing.borderRadius};
$border-radius-sm: 0.25rem;
$border-radius-lg: 0.5rem;
$border-radius-xl: 1rem;
$border-radius-pill: 50rem;

// Box shadow
$box-shadow-sm: 0 0.125rem 0.25rem rgba($black, 0.075);
$box-shadow: 0 0.5rem 1rem rgba($black, 0.15);
$box-shadow-lg: 0 1rem 3rem rgba($black, 0.175);

// Transition
$transition-base: all 0.2s ease-in-out;

// -----------------------------------------------------------------------------
// Buttons
// -----------------------------------------------------------------------------

$btn-padding-y: 0.5rem;
$btn-padding-x: 1rem;
$btn-font-weight: 500;
$btn-border-radius: $border-radius;

$btn-padding-y-sm: 0.25rem;
$btn-padding-x-sm: 0.5rem;
$btn-padding-y-lg: 0.75rem;
$btn-padding-x-lg: 1.5rem;

// -----------------------------------------------------------------------------
// Forms
// -----------------------------------------------------------------------------

$input-padding-y: 0.5rem;
$input-padding-x: 0.75rem;
$input-border-radius: $border-radius;
$input-border-color: $gray-400;
$input-focus-border-color: $primary;
$input-focus-box-shadow: 0 0 0 0.25rem rgba($primary, 0.25);

// -----------------------------------------------------------------------------
// Cards
// -----------------------------------------------------------------------------

$card-border-radius: $border-radius-lg;
$card-border-color: $gray-200;
$card-cap-padding-y: 0.75rem;
$card-cap-padding-x: 1rem;
$card-spacer-y: 1rem;
$card-spacer-x: 1rem;

// -----------------------------------------------------------------------------
// Navbar
// -----------------------------------------------------------------------------

$navbar-padding-y: 0.75rem;
$navbar-brand-font-size: 1.25rem;
$nav-link-padding-y: 0.5rem;
$nav-link-padding-x: 1rem;

// -----------------------------------------------------------------------------
// Base Styles
// -----------------------------------------------------------------------------

:root {
  --o-brand-primary: #{$o-brand-primary};
  --o-brand-secondary: #{$o-brand-secondary};
  --o-brand-odoo: #{$o-brand-odoo};
}

body {
  font-family: $font-family-base;
  font-size: $font-size-base;
  line-height: $line-height-base;
  color: $gray-900;
  background-color: $white;
}

// -----------------------------------------------------------------------------
// Odoo Website Header
// -----------------------------------------------------------------------------

#wrapwrap {
  position: relative;
  min-height: 100vh;
}

header {
  .navbar {
    padding: $navbar-padding-y 0;
    background-color: $white;
    border-bottom: 1px solid $gray-200;

    &.navbar-dark {
      background-color: $gray-900;
      border-bottom-color: $gray-800;
    }
  }

  .navbar-brand {
    font-size: $navbar-brand-font-size;
    font-weight: 600;
    color: $gray-900;

    img {
      height: 32px;
      width: auto;
    }
  }

  .nav-link {
    padding: $nav-link-padding-y $nav-link-padding-x;
    font-weight: 500;
    color: $gray-700;
    transition: color 0.15s ease-in-out;

    &:hover,
    &.active {
      color: $primary;
    }
  }

  .navbar-toggler {
    border: none;
    padding: 0.5rem;

    &:focus {
      box-shadow: none;
    }
  }
}

// -----------------------------------------------------------------------------
// Odoo Website Main Content
// -----------------------------------------------------------------------------

main {
  flex: 1;
}

// Section styles
section, .s_section {
  padding: ${odooDefaultSpacing.sectionPadding} 0;
}

.s_section_no_padding {
  padding: 0;
}

// Cover/Hero sections
.s_cover, .s_parallax {
  position: relative;
  background-size: cover;
  background-position: center;
  min-height: 400px;
  display: flex;
  align-items: center;
}

.s_cover_color_overlay {
  position: absolute;
  inset: 0;
  background-color: rgba($black, 0.5);
}

// Text over image
.s_text_image {
  padding: 48px 0;
}

// -----------------------------------------------------------------------------
// Odoo Buttons
// -----------------------------------------------------------------------------

.btn {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  gap: 0.5rem;
  padding: $btn-padding-y $btn-padding-x;
  font-weight: $btn-font-weight;
  border-radius: $btn-border-radius;
  transition: $transition-base;
  text-decoration: none;
}

.btn-primary {
  color: $white;
  background-color: $primary;
  border-color: $primary;

  &:hover {
    background-color: darken($primary, 7.5%);
    border-color: darken($primary, 10%);
  }

  &:focus {
    box-shadow: 0 0 0 0.25rem rgba($primary, 0.5);
  }
}

.btn-secondary {
  color: $white;
  background-color: $secondary;
  border-color: $secondary;

  &:hover {
    background-color: darken($secondary, 7.5%);
    border-color: darken($secondary, 10%);
  }
}

.btn-outline-primary {
  color: $primary;
  border-color: $primary;
  background-color: transparent;

  &:hover {
    color: $white;
    background-color: $primary;
  }
}

.btn-outline-secondary {
  color: $secondary;
  border-color: $secondary;
  background-color: transparent;

  &:hover {
    color: $white;
    background-color: $secondary;
  }
}

.btn-light {
  color: $gray-900;
  background-color: $gray-100;
  border-color: $gray-200;

  &:hover {
    background-color: $gray-200;
    border-color: $gray-300;
  }
}

// Button sizes
.btn-lg {
  padding: $btn-padding-y-lg $btn-padding-x-lg;
  font-size: 1.125rem;
}

.btn-sm {
  padding: $btn-padding-y-sm $btn-padding-x-sm;
  font-size: 0.875rem;
}

// -----------------------------------------------------------------------------
// Odoo Cards
// -----------------------------------------------------------------------------

.card {
  border: 1px solid $card-border-color;
  border-radius: $card-border-radius;
  box-shadow: $box-shadow-sm;
  transition: $transition-base;

  &:hover {
    box-shadow: $box-shadow;
  }
}

.card-header {
  padding: $card-cap-padding-y $card-cap-padding-x;
  background-color: $gray-100;
  border-bottom: 1px solid $card-border-color;
}

.card-body {
  padding: $card-spacer-y $card-spacer-x;
}

.card-footer {
  padding: $card-cap-padding-y $card-cap-padding-x;
  background-color: $gray-100;
  border-top: 1px solid $card-border-color;
}

// -----------------------------------------------------------------------------
// Odoo Forms
// -----------------------------------------------------------------------------

.form-control {
  padding: $input-padding-y $input-padding-x;
  border: 1px solid $input-border-color;
  border-radius: $input-border-radius;
  transition: border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out;

  &:focus {
    border-color: $input-focus-border-color;
    box-shadow: $input-focus-box-shadow;
    outline: none;
  }

  &::placeholder {
    color: $gray-500;
  }
}

.form-label {
  margin-bottom: 0.5rem;
  font-weight: 500;
}

// -----------------------------------------------------------------------------
// Odoo Website Footer
// -----------------------------------------------------------------------------

footer {
  background-color: $gray-900;
  color: $gray-300;
  padding: 48px 0 24px;

  h5, .h5 {
    color: $white;
    font-size: 1rem;
    font-weight: 600;
    margin-bottom: 1rem;
    text-transform: uppercase;
    letter-spacing: 0.05em;
  }

  a {
    color: $gray-400;
    text-decoration: none;
    transition: color 0.15s;

    &:hover {
      color: $white;
    }
  }

  ul {
    list-style: none;
    padding: 0;
    margin: 0;

    li {
      margin-bottom: 0.5rem;
    }
  }

  .footer-copyright {
    padding-top: 1.5rem;
    margin-top: 1.5rem;
    border-top: 1px solid $gray-700;
    font-size: 0.875rem;
    color: $gray-500;
  }
}

// -----------------------------------------------------------------------------
// Utilities
// -----------------------------------------------------------------------------

.text-primary { color: $primary !important; }
.text-secondary { color: $secondary !important; }
.text-muted { color: $gray-600 !important; }

.bg-primary { background-color: $primary !important; }
.bg-secondary { background-color: $secondary !important; }
.bg-light { background-color: $gray-100 !important; }
.bg-dark { background-color: $gray-900 !important; }

.bg-o-color-1 { background-color: $o-brand-primary !important; }
.bg-o-color-2 { background-color: $o-brand-secondary !important; }
.bg-o-color-3 { background-color: $o-brand-lighten !important; }

.rounded { border-radius: $border-radius !important; }
.rounded-lg { border-radius: $border-radius-lg !important; }
.rounded-pill { border-radius: $border-radius-pill !important; }

.shadow-sm { box-shadow: $box-shadow-sm !important; }
.shadow { box-shadow: $box-shadow !important; }
.shadow-lg { box-shadow: $box-shadow-lg !important; }
`.trim();
}

/** Generate CSS variables only */
export function generateOdooDefaultCSSVariables(): string {
  return `
:root {
  /* Odoo Brand Colors */
  --o-brand-primary: ${odooBrandColors.purple};
  --o-brand-secondary: ${odooBrandColors.teal};
  --o-brand-odoo: ${odooBrandColors.purple};
  --o-brand-lighten: ${odooBrandColors.lightPurple};
  --o-brand-darken: ${odooBrandColors.darkPurple};

  /* Bootstrap Color Variables */
  --bs-primary: ${odooDefaultColors.primary};
  --bs-secondary: ${odooDefaultColors.secondary};
  --bs-success: ${odooDefaultColors.success};
  --bs-warning: ${odooDefaultColors.warning};
  --bs-danger: ${odooDefaultColors.error};
  --bs-light: ${odooGrayscale[100]};
  --bs-dark: ${odooGrayscale[900]};

  /* Gray Scale */
  --bs-gray-100: ${odooGrayscale[100]};
  --bs-gray-200: ${odooGrayscale[200]};
  --bs-gray-300: ${odooGrayscale[300]};
  --bs-gray-400: ${odooGrayscale[400]};
  --bs-gray-500: ${odooGrayscale[500]};
  --bs-gray-600: ${odooGrayscale[600]};
  --bs-gray-700: ${odooGrayscale[700]};
  --bs-gray-800: ${odooGrayscale[800]};
  --bs-gray-900: ${odooGrayscale[900]};

  /* Typography */
  --bs-font-sans-serif: ${odooDefaultTypography.bodyFont};
  --bs-body-font-family: var(--bs-font-sans-serif);
  --bs-body-font-size: ${odooDefaultTypography.baseFontSize};
  --bs-body-line-height: ${odooDefaultTypography.lineHeight};

  /* Spacing */
  --bs-gutter-x: ${odooDefaultSpacing.gap};

  /* Border Radius */
  --bs-border-radius: ${odooDefaultSpacing.borderRadius};
}
`.trim();
}

/** Generate Odoo manifest */
export function generateOdooDefaultManifest(): Record<string, unknown> {
  return {
    name: odooDefaultTheme.name,
    summary: odooDefaultTheme.description,
    description: `
${odooDefaultTheme.description}

Features:
- Odoo 17 default purple brand color
- Bootstrap 5 integration
- Full compatibility with Odoo snippets
- Standard navbar and footer styling
- Form controls matching Odoo style
- Card components with Odoo aesthetics
- All standard Odoo section types
- Utility classes matching Odoo conventions
    `.trim(),
    category: "Theme/Website",
    version: odooDefaultTheme.version,
    author: odooDefaultTheme.author,
    website: "https://platxa.com",
    license: "LGPL-3",
    depends: ["website"],
    data: [
      "views/templates.xml",
      "views/snippets.xml",
    ],
    assets: {
      "web.assets_frontend": [
        "/theme_odoo_default/static/src/scss/primary_variables.scss",
        "/theme_odoo_default/static/src/scss/theme.scss",
      ],
    },
    images: [odooDefaultTheme.previewImage],
    application: false,
    installable: true,
    auto_install: false,
  };
}

// =============================================================================
// Exports
// =============================================================================

export default odooDefaultTheme;
