/**
 * Minimal Theme Template
 *
 * Clean, whitespace-focused design with modern typography.
 * Perfect for portfolios, blogs, and professional services.
 *
 * Features:
 * - Generous whitespace for breathing room
 * - Modern sans-serif typography
 * - Subtle animations and transitions
 * - Light/dark mode support
 * - Mobile-first responsive design
 *
 * Feature #61: Theme System - Minimal Theme
 */

import type { ThemeTemplate, ColorScheme, Typography, Spacing, LayoutOptions } from "../../theme-registry";

// =============================================================================
// Theme Configuration
// =============================================================================

/** Minimal theme color scheme - Light mode */
export const minimalLightColors: ColorScheme = {
  primary: "#171717",
  secondary: "#525252",
  background: "#ffffff",
  surface: "#fafafa",
  text: "#171717",
  textMuted: "#737373",
  border: "#e5e5e5",
  success: "#22c55e",
  warning: "#f59e0b",
  error: "#ef4444",
};

/** Minimal theme color scheme - Dark mode */
export const minimalDarkColors: ColorScheme = {
  primary: "#fafafa",
  secondary: "#a3a3a3",
  background: "#0a0a0a",
  surface: "#171717",
  text: "#fafafa",
  textMuted: "#a3a3a3",
  border: "#262626",
  success: "#22c55e",
  warning: "#f59e0b",
  error: "#ef4444",
};

/** Minimal theme typography */
export const minimalTypography: Typography = {
  headingFont: "Inter, system-ui, -apple-system, sans-serif",
  bodyFont: "Inter, system-ui, -apple-system, sans-serif",
  baseFontSize: "16px",
  lineHeight: "1.75",
  headingWeight: "500",
};

/** Minimal theme spacing */
export const minimalSpacing: Spacing = {
  sectionPadding: "120px",
  containerWidth: "960px",
  gap: "32px",
  borderRadius: "4px",
};

/** Minimal theme layout */
export const minimalLayout: LayoutOptions = {
  headerStyle: "static",
  navStyle: "horizontal",
  footerColumns: 2,
};

// =============================================================================
// Theme Template Definition
// =============================================================================

/** Minimal theme template */
export const minimalTheme: ThemeTemplate = {
  id: "minimal-pure",
  name: "Minimal Pure",
  description: "Clean, whitespace-focused design with modern typography. Perfect for portfolios, blogs, and professional services that want a sophisticated, uncluttered look.",
  category: "minimal",
  tags: ["clean", "whitespace", "modern", "typography", "professional", "elegant", "simple"],
  previewImage: "/themes/minimal-pure/preview.png",
  thumbnail: "/themes/minimal-pure/thumb.png",
  colors: minimalLightColors,
  typography: minimalTypography,
  spacing: minimalSpacing,
  layout: minimalLayout,
  isPremium: false,
  version: "1.0.0",
  author: "Platxa Studio",
  updatedAt: new Date("2024-02-20"),
  odooVersion: "17.0",
};

// =============================================================================
// SCSS Generation
// =============================================================================

/** Generate theme SCSS */
export function generateMinimalSCSS(darkMode: boolean = false): string {
  const colors = darkMode ? minimalDarkColors : minimalLightColors;

  return `
// =============================================================================
// Minimal Theme - ${darkMode ? "Dark Mode" : "Light Mode"}
// Generated by Platxa Studio
// =============================================================================

// -----------------------------------------------------------------------------
// Variables
// -----------------------------------------------------------------------------

// Colors
$theme-primary: ${colors.primary};
$theme-secondary: ${colors.secondary};
$theme-background: ${colors.background};
$theme-surface: ${colors.surface};
$theme-text: ${colors.text};
$theme-text-muted: ${colors.textMuted};
$theme-border: ${colors.border};
$theme-success: ${colors.success};
$theme-warning: ${colors.warning};
$theme-error: ${colors.error};

// Typography
$theme-font-stack: ${minimalTypography.headingFont};
$theme-font-size-base: ${minimalTypography.baseFontSize};
$theme-line-height: ${minimalTypography.lineHeight};
$theme-heading-weight: ${minimalTypography.headingWeight};

// Spacing
$theme-section-padding: ${minimalSpacing.sectionPadding};
$theme-container-width: ${minimalSpacing.containerWidth};
$theme-gap: ${minimalSpacing.gap};
$theme-radius: ${minimalSpacing.borderRadius};

// Transitions
$theme-transition: 0.2s ease;
$theme-transition-slow: 0.4s ease;

// -----------------------------------------------------------------------------
// CSS Custom Properties
// -----------------------------------------------------------------------------

:root {
  --color-primary: #{$theme-primary};
  --color-secondary: #{$theme-secondary};
  --color-background: #{$theme-background};
  --color-surface: #{$theme-surface};
  --color-text: #{$theme-text};
  --color-text-muted: #{$theme-text-muted};
  --color-border: #{$theme-border};
  --color-success: #{$theme-success};
  --color-warning: #{$theme-warning};
  --color-error: #{$theme-error};

  --font-family: #{$theme-font-stack};
  --font-size-base: #{$theme-font-size-base};
  --line-height: #{$theme-line-height};

  --section-padding: #{$theme-section-padding};
  --container-width: #{$theme-container-width};
  --gap: #{$theme-gap};
  --radius: #{$theme-radius};

  --transition: #{$theme-transition};
  --transition-slow: #{$theme-transition-slow};
}

// -----------------------------------------------------------------------------
// Reset & Base
// -----------------------------------------------------------------------------

*,
*::before,
*::after {
  box-sizing: border-box;
}

html {
  font-size: $theme-font-size-base;
  scroll-behavior: smooth;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

body {
  margin: 0;
  font-family: $theme-font-stack;
  font-size: 1rem;
  line-height: $theme-line-height;
  color: $theme-text;
  background-color: $theme-background;
  transition: background-color $theme-transition-slow, color $theme-transition-slow;
}

// -----------------------------------------------------------------------------
// Typography
// -----------------------------------------------------------------------------

h1, h2, h3, h4, h5, h6 {
  margin: 0 0 1.5rem;
  font-family: $theme-font-stack;
  font-weight: $theme-heading-weight;
  line-height: 1.2;
  letter-spacing: -0.02em;
  color: $theme-text;
}

h1 {
  font-size: clamp(2.5rem, 5vw, 4rem);
  margin-bottom: 2rem;
}

h2 {
  font-size: clamp(2rem, 4vw, 3rem);
}

h3 {
  font-size: clamp(1.5rem, 3vw, 2rem);
}

h4 {
  font-size: 1.25rem;
}

h5 {
  font-size: 1.125rem;
}

h6 {
  font-size: 1rem;
  text-transform: uppercase;
  letter-spacing: 0.05em;
}

p {
  margin: 0 0 1.5rem;
  color: $theme-text-muted;

  &:last-child {
    margin-bottom: 0;
  }
}

a {
  color: $theme-primary;
  text-decoration: none;
  transition: color $theme-transition;

  &:hover {
    color: $theme-secondary;
  }
}

// -----------------------------------------------------------------------------
// Layout
// -----------------------------------------------------------------------------

.container {
  width: 100%;
  max-width: $theme-container-width;
  margin: 0 auto;
  padding: 0 1.5rem;
}

.container-wide {
  max-width: 1280px;
}

.container-narrow {
  max-width: 720px;
}

section,
.section {
  padding: $theme-section-padding 0;

  @media (max-width: 768px) {
    padding: calc(#{$theme-section-padding} / 2) 0;
  }
}

// -----------------------------------------------------------------------------
// Header
// -----------------------------------------------------------------------------

.header {
  position: relative;
  padding: 2rem 0;
  border-bottom: 1px solid $theme-border;
  background-color: $theme-background;

  .header-inner {
    display: flex;
    align-items: center;
    justify-content: space-between;
    gap: 2rem;
  }
}

.logo {
  font-size: 1.25rem;
  font-weight: 600;
  letter-spacing: -0.02em;
  color: $theme-text;
  text-decoration: none;

  &:hover {
    color: $theme-text;
  }
}

.nav {
  display: flex;
  gap: 2.5rem;

  @media (max-width: 768px) {
    display: none;
  }
}

.nav-link {
  font-size: 0.875rem;
  font-weight: 500;
  color: $theme-text-muted;
  text-decoration: none;
  transition: color $theme-transition;

  &:hover,
  &.active {
    color: $theme-text;
  }
}

// -----------------------------------------------------------------------------
// Hero Section
// -----------------------------------------------------------------------------

.hero {
  min-height: 70vh;
  display: flex;
  align-items: center;
  padding: calc(#{$theme-section-padding} * 1.5) 0;

  .hero-content {
    max-width: 800px;
  }

  .hero-title {
    margin-bottom: 1.5rem;
  }

  .hero-subtitle {
    font-size: 1.25rem;
    line-height: 1.6;
    color: $theme-text-muted;
    margin-bottom: 2.5rem;
  }
}

// -----------------------------------------------------------------------------
// Buttons
// -----------------------------------------------------------------------------

.btn {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  gap: 0.5rem;
  padding: 0.875rem 1.75rem;
  font-family: $theme-font-stack;
  font-size: 0.875rem;
  font-weight: 500;
  line-height: 1;
  text-decoration: none;
  border: 1px solid transparent;
  border-radius: $theme-radius;
  cursor: pointer;
  transition: all $theme-transition;

  &:disabled {
    opacity: 0.5;
    cursor: not-allowed;
  }
}

.btn-primary {
  color: ${darkMode ? "#0a0a0a" : "#ffffff"};
  background-color: $theme-primary;
  border-color: $theme-primary;

  &:hover:not(:disabled) {
    background-color: $theme-secondary;
    border-color: $theme-secondary;
  }
}

.btn-secondary {
  color: $theme-text;
  background-color: transparent;
  border-color: $theme-border;

  &:hover:not(:disabled) {
    background-color: $theme-surface;
    border-color: $theme-text;
  }
}

.btn-ghost {
  color: $theme-text-muted;
  background-color: transparent;
  border-color: transparent;

  &:hover:not(:disabled) {
    color: $theme-text;
    background-color: $theme-surface;
  }
}

// -----------------------------------------------------------------------------
// Cards
// -----------------------------------------------------------------------------

.card {
  padding: 2rem;
  background-color: $theme-surface;
  border: 1px solid $theme-border;
  border-radius: $theme-radius;
  transition: border-color $theme-transition, box-shadow $theme-transition;

  &:hover {
    border-color: $theme-text-muted;
  }
}

.card-title {
  font-size: 1.125rem;
  margin-bottom: 0.75rem;
}

.card-text {
  font-size: 0.9375rem;
  color: $theme-text-muted;
}

// -----------------------------------------------------------------------------
// Grid
// -----------------------------------------------------------------------------

.grid {
  display: grid;
  gap: $theme-gap;
}

.grid-2 {
  grid-template-columns: repeat(2, 1fr);

  @media (max-width: 768px) {
    grid-template-columns: 1fr;
  }
}

.grid-3 {
  grid-template-columns: repeat(3, 1fr);

  @media (max-width: 1024px) {
    grid-template-columns: repeat(2, 1fr);
  }

  @media (max-width: 640px) {
    grid-template-columns: 1fr;
  }
}

// -----------------------------------------------------------------------------
// Footer
// -----------------------------------------------------------------------------

.footer {
  padding: 4rem 0;
  border-top: 1px solid $theme-border;

  .footer-inner {
    display: flex;
    justify-content: space-between;
    align-items: center;
    gap: 2rem;

    @media (max-width: 640px) {
      flex-direction: column;
      text-align: center;
    }
  }

  .footer-text {
    font-size: 0.875rem;
    color: $theme-text-muted;
  }

  .footer-links {
    display: flex;
    gap: 1.5rem;

    a {
      font-size: 0.875rem;
      color: $theme-text-muted;

      &:hover {
        color: $theme-text;
      }
    }
  }
}

// -----------------------------------------------------------------------------
// Utilities
// -----------------------------------------------------------------------------

.text-center { text-align: center; }
.text-left { text-align: left; }
.text-right { text-align: right; }

.text-muted { color: $theme-text-muted; }
.text-primary { color: $theme-primary; }

.mt-0 { margin-top: 0; }
.mt-1 { margin-top: 0.5rem; }
.mt-2 { margin-top: 1rem; }
.mt-3 { margin-top: 1.5rem; }
.mt-4 { margin-top: 2rem; }
.mt-5 { margin-top: 3rem; }

.mb-0 { margin-bottom: 0; }
.mb-1 { margin-bottom: 0.5rem; }
.mb-2 { margin-bottom: 1rem; }
.mb-3 { margin-bottom: 1.5rem; }
.mb-4 { margin-bottom: 2rem; }
.mb-5 { margin-bottom: 3rem; }

.visually-hidden {
  position: absolute;
  width: 1px;
  height: 1px;
  padding: 0;
  margin: -1px;
  overflow: hidden;
  clip: rect(0, 0, 0, 0);
  white-space: nowrap;
  border: 0;
}

// -----------------------------------------------------------------------------
// Animations
// -----------------------------------------------------------------------------

@keyframes fadeIn {
  from {
    opacity: 0;
    transform: translateY(10px);
  }
  to {
    opacity: 1;
    transform: translateY(0);
  }
}

.fade-in {
  animation: fadeIn 0.6s ease forwards;
}

.fade-in-delay-1 { animation-delay: 0.1s; }
.fade-in-delay-2 { animation-delay: 0.2s; }
.fade-in-delay-3 { animation-delay: 0.3s; }
`.trim();
}

/** Generate CSS variables only */
export function generateMinimalCSSVariables(darkMode: boolean = false): string {
  const colors = darkMode ? minimalDarkColors : minimalLightColors;

  return `
:root {
  /* Colors */
  --color-primary: ${colors.primary};
  --color-secondary: ${colors.secondary};
  --color-background: ${colors.background};
  --color-surface: ${colors.surface};
  --color-text: ${colors.text};
  --color-text-muted: ${colors.textMuted};
  --color-border: ${colors.border};
  --color-success: ${colors.success};
  --color-warning: ${colors.warning};
  --color-error: ${colors.error};

  /* Typography */
  --font-family: ${minimalTypography.headingFont};
  --font-size-base: ${minimalTypography.baseFontSize};
  --line-height: ${minimalTypography.lineHeight};
  --heading-weight: ${minimalTypography.headingWeight};

  /* Spacing */
  --section-padding: ${minimalSpacing.sectionPadding};
  --container-width: ${minimalSpacing.containerWidth};
  --gap: ${minimalSpacing.gap};
  --radius: ${minimalSpacing.borderRadius};
}
`.trim();
}

/** Generate Odoo manifest */
export function generateMinimalManifest(): Record<string, unknown> {
  return {
    name: minimalTheme.name,
    summary: minimalTheme.description,
    description: `
${minimalTheme.description}

Features:
- Generous whitespace for breathing room
- Modern Inter typography
- Light and dark mode support
- Subtle animations
- Mobile-first responsive design
- Accessible color contrast
    `.trim(),
    category: "Theme/Website",
    version: minimalTheme.version,
    author: minimalTheme.author,
    website: "https://platxa.com",
    license: "LGPL-3",
    depends: ["website"],
    data: [
      "views/templates.xml",
      "views/snippets.xml",
      "views/options.xml",
    ],
    assets: {
      "web.assets_frontend": [
        "/theme_minimal_pure/static/src/scss/theme.scss",
        "/theme_minimal_pure/static/src/js/theme.js",
      ],
    },
    images: [minimalTheme.previewImage],
    application: false,
    installable: true,
    auto_install: false,
  };
}

// =============================================================================
// Exports
// =============================================================================

export default minimalTheme;
