/**
 * Tech Theme Template
 *
 * Dark, sophisticated design with accent colors and mono fonts.
 * Perfect for developer tools, SaaS platforms, and tech companies.
 *
 * Features:
 * - Dark backgrounds with high contrast
 * - Neon accent colors (cyan, purple, green)
 * - Monospace typography emphasis
 * - Sharp, precise design elements
 * - Terminal-inspired aesthetics
 * - Subtle glow effects
 *
 * Feature #64: Theme System - Tech Theme
 */

import type { ThemeTemplate, ColorScheme, Typography, Spacing, LayoutOptions } from "../../theme-registry";

// =============================================================================
// Theme Configuration
// =============================================================================

/** Tech theme color scheme - Dark mode (primary) */
export const techDarkColors: ColorScheme = {
  primary: "#00D9FF",        // Electric cyan
  secondary: "#A855F7",      // Vibrant purple
  background: "#0A0A0F",     // Near black
  surface: "#1A1A24",
  text: "#E4E4E7",
  textMuted: "#71717A",
  border: "#27272A",
  success: "#10B981",        // Terminal green
  warning: "#F59E0B",
  error: "#EF4444",
};

/** Tech theme color scheme - Light mode (alternative) */
export const techLightColors: ColorScheme = {
  primary: "#0891B2",        // Darker cyan for light bg
  secondary: "#7C3AED",      // Purple
  background: "#FAFAFA",
  surface: "#FFFFFF",
  text: "#18181B",
  textMuted: "#71717A",
  border: "#E4E4E7",
  success: "#059669",
  warning: "#D97706",
  error: "#DC2626",
};

/** Tech theme typography - mono-focused */
export const techTypography: Typography = {
  headingFont: "'JetBrains Mono', 'Fira Code', 'SF Mono', monospace",
  bodyFont: "'Inter', 'SF Pro Display', -apple-system, BlinkMacSystemFont, sans-serif",
  baseFontSize: "14px",      // Slightly smaller for tech feel
  lineHeight: "1.5",
  headingWeight: "600",
};

/** Tech theme spacing - precise, minimal */
export const techSpacing: Spacing = {
  sectionPadding: "80px",
  containerWidth: "1200px",
  gap: "24px",
  borderRadius: "8px",       // Sharp, minimal
};

/** Tech theme layout */
export const techLayout: LayoutOptions = {
  headerStyle: "fixed",
  navStyle: "horizontal",
  footerColumns: 4,
  sidebarPosition: "left",
};

// =============================================================================
// Theme Template Definition
// =============================================================================

/** Tech theme template */
export const techTheme: ThemeTemplate = {
  id: "tech-dark",
  name: "Tech Dark",
  description: "Dark mode with neon accents and mono fonts for a technical, developer-focused aesthetic. Perfect for SaaS, dev tools, and tech startups.",
  category: "business",
  tags: ["dark", "tech", "developer", "saas", "monospace", "neon", "terminal", "modern"],
  previewImage: "/themes/tech-dark/preview.png",
  thumbnail: "/themes/tech-dark/thumb.png",
  colors: techDarkColors,
  typography: techTypography,
  spacing: techSpacing,
  layout: techLayout,
  isPremium: false,
  version: "1.0.0",
  author: "Platxa Studio",
  updatedAt: new Date("2024-02-20"),
  odooVersion: "17.0",
};

// =============================================================================
// SCSS Generation
// =============================================================================

/** Generate tech theme SCSS */
export function generateTechSCSS(darkMode: boolean = true): string {
  const colors = darkMode ? techDarkColors : techLightColors;
  const accent = "#10B981"; // Terminal green

  return `
// =============================================================================
// Tech Theme - ${darkMode ? "Dark Mode" : "Light Mode"}
// Generated by Platxa Studio
// =============================================================================

// -----------------------------------------------------------------------------
// Variables
// -----------------------------------------------------------------------------

// Colors
$theme-primary: ${colors.primary};
$theme-secondary: ${colors.secondary};
$theme-accent: ${accent};
$theme-background: ${colors.background};
$theme-surface: ${colors.surface};
$theme-surface-hover: ${darkMode ? "#24242F" : "#F4F4F5"};
$theme-text: ${colors.text};
$theme-text-muted: ${colors.textMuted};
$theme-border: ${colors.border};
$theme-success: ${colors.success};
$theme-warning: ${colors.warning};
$theme-error: ${colors.error};
$theme-code-bg: ${darkMode ? "#0D1117" : "#F4F4F5"};

// Typography
$theme-font-heading: ${techTypography.headingFont};
$theme-font-body: ${techTypography.bodyFont};
$theme-font-mono: 'JetBrains Mono', 'Fira Code', 'SF Mono', 'Menlo', monospace;
$theme-font-size-base: ${techTypography.baseFontSize};
$theme-line-height: ${techTypography.lineHeight};
$theme-heading-weight: ${techTypography.headingWeight};

// Spacing
$theme-section-padding: ${techSpacing.sectionPadding};
$theme-container-width: ${techSpacing.containerWidth};
$theme-gap: ${techSpacing.gap};
$theme-radius: ${techSpacing.borderRadius};

// Transitions - sharp, precise
$theme-transition: 0.15s cubic-bezier(0.4, 0, 0.2, 1);
$theme-transition-fast: 0.1s ease;

// Shadows - subtle with glows
$theme-shadow-sm: 0 1px 2px rgba(0, 0, 0, 0.5);
$theme-shadow: 0 2px 4px rgba(0, 0, 0, 0.5);
$theme-shadow-md: 0 4px 8px rgba(0, 0, 0, 0.5);
$theme-shadow-lg: 0 8px 16px rgba(0, 0, 0, 0.5);
$theme-shadow-glow: 0 0 20px rgba(0, 217, 255, 0.3);
$theme-shadow-glow-primary: 0 0 30px rgba(0, 217, 255, 0.4);
$theme-shadow-glow-accent: 0 0 20px rgba(16, 185, 129, 0.4);

// -----------------------------------------------------------------------------
// CSS Custom Properties
// -----------------------------------------------------------------------------

:root {
  --color-primary: #{$theme-primary};
  --color-secondary: #{$theme-secondary};
  --color-accent: #{$theme-accent};
  --color-background: #{$theme-background};
  --color-surface: #{$theme-surface};
  --color-surface-hover: #{$theme-surface-hover};
  --color-text: #{$theme-text};
  --color-text-muted: #{$theme-text-muted};
  --color-border: #{$theme-border};
  --color-success: #{$theme-success};
  --color-warning: #{$theme-warning};
  --color-error: #{$theme-error};
  --color-code-bg: #{$theme-code-bg};

  --font-heading: #{$theme-font-heading};
  --font-body: #{$theme-font-body};
  --font-mono: #{$theme-font-mono};
  --font-size-base: #{$theme-font-size-base};
  --line-height: #{$theme-line-height};

  --section-padding: #{$theme-section-padding};
  --container-width: #{$theme-container-width};
  --gap: #{$theme-gap};
  --radius: #{$theme-radius};

  --transition: #{$theme-transition};
  --transition-fast: #{$theme-transition-fast};

  --shadow-sm: #{$theme-shadow-sm};
  --shadow: #{$theme-shadow};
  --shadow-md: #{$theme-shadow-md};
  --shadow-lg: #{$theme-shadow-lg};
  --shadow-glow: #{$theme-shadow-glow};
  --shadow-glow-primary: #{$theme-shadow-glow-primary};
  --shadow-glow-accent: #{$theme-shadow-glow-accent};
}

// -----------------------------------------------------------------------------
// Reset & Base
// -----------------------------------------------------------------------------

*,
*::before,
*::after {
  box-sizing: border-box;
}

html {
  font-size: $theme-font-size-base;
  scroll-behavior: smooth;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

body {
  margin: 0;
  font-family: $theme-font-body;
  font-size: 1rem;
  line-height: $theme-line-height;
  color: $theme-text;
  background-color: $theme-background;
  transition: background-color $theme-transition, color $theme-transition;
}

::selection {
  background-color: rgba(0, 217, 255, 0.3);
  color: $theme-text;
}

// -----------------------------------------------------------------------------
// Typography
// -----------------------------------------------------------------------------

h1, h2, h3, h4, h5, h6 {
  margin: 0 0 1rem;
  font-family: $theme-font-heading;
  font-weight: $theme-heading-weight;
  line-height: 1.25;
  letter-spacing: -0.02em;
  color: $theme-text;
}

h1 {
  font-size: clamp(2rem, 5vw, 3rem);
  margin-bottom: 1.5rem;
}

h2 {
  font-size: clamp(1.5rem, 4vw, 2.25rem);
}

h3 {
  font-size: clamp(1.25rem, 3vw, 1.75rem);
}

h4 {
  font-size: 1.25rem;
}

h5 {
  font-size: 1rem;
  text-transform: uppercase;
  letter-spacing: 0.1em;
}

h6 {
  font-size: 0.875rem;
  text-transform: uppercase;
  letter-spacing: 0.1em;
}

p {
  margin: 0 0 1rem;
  color: $theme-text-muted;

  &:last-child {
    margin-bottom: 0;
  }
}

a {
  color: $theme-primary;
  text-decoration: none;
  transition: color $theme-transition;

  &:hover {
    color: lighten($theme-primary, 10%);
    text-decoration: underline;
  }
}

code, kbd, pre, samp {
  font-family: $theme-font-mono;
}

code {
  padding: 0.125rem 0.375rem;
  font-size: 0.875em;
  background-color: $theme-code-bg;
  border: 1px solid $theme-border;
  border-radius: 4px;
  color: $theme-accent;
}

pre {
  padding: 1rem;
  overflow-x: auto;
  background-color: $theme-code-bg;
  border: 1px solid $theme-border;
  border-radius: $theme-radius;

  code {
    padding: 0;
    background: none;
    border: none;
  }
}

// -----------------------------------------------------------------------------
// Layout
// -----------------------------------------------------------------------------

.container {
  width: 100%;
  max-width: $theme-container-width;
  margin: 0 auto;
  padding: 0 1.5rem;
}

.container-narrow {
  max-width: 800px;
}

section,
.section {
  padding: $theme-section-padding 0;

  @media (max-width: 768px) {
    padding: calc(#{$theme-section-padding} / 2) 0;
  }
}

// -----------------------------------------------------------------------------
// Header
// -----------------------------------------------------------------------------

.header {
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  z-index: 100;
  padding: 1rem 0;
  background-color: rgba($theme-background, 0.85);
  backdrop-filter: blur(12px);
  border-bottom: 1px solid $theme-border;

  .header-inner {
    display: flex;
    align-items: center;
    justify-content: space-between;
    gap: 2rem;
  }
}

.logo {
  font-family: $theme-font-mono;
  font-size: 1.125rem;
  font-weight: 700;
  color: $theme-primary;
  text-decoration: none;
  letter-spacing: -0.02em;

  &:hover {
    color: $theme-primary;
    text-decoration: none;
  }

  &::before {
    content: '>';
    margin-right: 0.5rem;
    color: $theme-accent;
  }
}

.nav {
  display: flex;
  gap: 2rem;

  @media (max-width: 768px) {
    display: none;
  }
}

.nav-link {
  font-family: $theme-font-mono;
  font-size: 0.8125rem;
  font-weight: 500;
  color: $theme-text-muted;
  text-decoration: none;
  text-transform: uppercase;
  letter-spacing: 0.05em;
  transition: color $theme-transition;

  &:hover,
  &.active {
    color: $theme-primary;
    text-decoration: none;
  }
}

// -----------------------------------------------------------------------------
// Hero Section
// -----------------------------------------------------------------------------

.hero {
  min-height: 100vh;
  display: flex;
  align-items: center;
  padding: calc(#{$theme-section-padding} + 80px) 0 $theme-section-padding;

  .hero-content {
    max-width: 800px;
  }

  .hero-title {
    margin-bottom: 1.5rem;

    .highlight {
      color: $theme-primary;
      text-shadow: $theme-shadow-glow;
    }
  }

  .hero-subtitle {
    font-size: 1.125rem;
    line-height: 1.7;
    color: $theme-text-muted;
    margin-bottom: 2rem;
  }

  .hero-terminal {
    margin-top: 3rem;
    padding: 1.5rem;
    background-color: $theme-code-bg;
    border: 1px solid $theme-border;
    border-radius: $theme-radius;
    font-family: $theme-font-mono;
    font-size: 0.875rem;

    .terminal-line {
      display: flex;
      gap: 0.75rem;
      margin-bottom: 0.5rem;

      &:last-child {
        margin-bottom: 0;
      }

      .prompt {
        color: $theme-accent;
      }

      .command {
        color: $theme-text;
      }

      .output {
        color: $theme-text-muted;
      }
    }
  }
}

// -----------------------------------------------------------------------------
// Buttons
// -----------------------------------------------------------------------------

.btn {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  gap: 0.5rem;
  padding: 0.625rem 1.25rem;
  font-family: $theme-font-mono;
  font-size: 0.8125rem;
  font-weight: 500;
  line-height: 1;
  text-decoration: none;
  text-transform: uppercase;
  letter-spacing: 0.05em;
  border: 1px solid transparent;
  border-radius: 4px;
  cursor: pointer;
  transition: all $theme-transition;

  &:disabled {
    opacity: 0.5;
    cursor: not-allowed;
  }
}

.btn-primary {
  color: $theme-background;
  background-color: $theme-primary;
  border-color: $theme-primary;

  &:hover:not(:disabled) {
    background-color: lighten($theme-primary, 5%);
    box-shadow: $theme-shadow-glow;
  }

  &:active:not(:disabled) {
    transform: translateY(1px);
  }
}

.btn-secondary {
  color: $theme-primary;
  background-color: transparent;
  border-color: $theme-primary;

  &:hover:not(:disabled) {
    background-color: rgba($theme-primary, 0.1);
    box-shadow: $theme-shadow-glow;
  }
}

.btn-ghost {
  color: $theme-text-muted;
  background-color: transparent;
  border-color: $theme-border;

  &:hover:not(:disabled) {
    color: $theme-text;
    border-color: $theme-text-muted;
  }
}

.btn-terminal {
  color: $theme-accent;
  background-color: $theme-code-bg;
  border-color: $theme-accent;
  font-family: $theme-font-mono;

  &::before {
    content: '$';
    margin-right: 0.5rem;
  }

  &:hover:not(:disabled) {
    box-shadow: $theme-shadow-glow-accent;
  }
}

// -----------------------------------------------------------------------------
// Cards
// -----------------------------------------------------------------------------

.card {
  padding: 1.5rem;
  background-color: $theme-surface;
  border: 1px solid $theme-border;
  border-radius: $theme-radius;
  transition: all $theme-transition;

  &:hover {
    border-color: $theme-primary;
    box-shadow: $theme-shadow-glow;
  }
}

.card-terminal {
  background-color: $theme-code-bg;
  font-family: $theme-font-mono;

  .card-header {
    display: flex;
    align-items: center;
    gap: 0.5rem;
    padding-bottom: 1rem;
    margin-bottom: 1rem;
    border-bottom: 1px solid $theme-border;

    .dot {
      width: 12px;
      height: 12px;
      border-radius: 50%;

      &.red { background-color: #ff5f56; }
      &.yellow { background-color: #ffbd2e; }
      &.green { background-color: #27c93f; }
    }
  }
}

.card-glass {
  background: rgba(26, 26, 36, 0.8);
  backdrop-filter: blur(12px);
  border-color: rgba(255, 255, 255, 0.1);
}

.card-title {
  font-family: $theme-font-mono;
  font-size: 1rem;
  margin-bottom: 0.5rem;
  color: $theme-text;
}

.card-text {
  font-size: 0.875rem;
  color: $theme-text-muted;
}

// -----------------------------------------------------------------------------
// Badges
// -----------------------------------------------------------------------------

.badge {
  display: inline-flex;
  align-items: center;
  padding: 0.125rem 0.5rem;
  font-family: $theme-font-mono;
  font-size: 0.6875rem;
  font-weight: 500;
  text-transform: uppercase;
  letter-spacing: 0.05em;
  border: 1px solid;
  border-radius: 4px;
}

.badge-primary {
  background-color: rgba(0, 217, 255, 0.15);
  color: $theme-primary;
  border-color: $theme-primary;
}

.badge-secondary {
  background-color: rgba(168, 85, 247, 0.15);
  color: $theme-secondary;
  border-color: $theme-secondary;
}

.badge-success {
  background-color: rgba(16, 185, 129, 0.15);
  color: $theme-success;
  border-color: $theme-success;
}

.badge-warning {
  background-color: rgba(245, 158, 11, 0.15);
  color: $theme-warning;
  border-color: $theme-warning;
}

.badge-error {
  background-color: rgba(239, 68, 68, 0.15);
  color: $theme-error;
  border-color: $theme-error;
}

// -----------------------------------------------------------------------------
// Grid
// -----------------------------------------------------------------------------

.grid {
  display: grid;
  gap: $theme-gap;
}

.grid-2 {
  grid-template-columns: repeat(2, 1fr);

  @media (max-width: 768px) {
    grid-template-columns: 1fr;
  }
}

.grid-3 {
  grid-template-columns: repeat(3, 1fr);

  @media (max-width: 1024px) {
    grid-template-columns: repeat(2, 1fr);
  }

  @media (max-width: 640px) {
    grid-template-columns: 1fr;
  }
}

// -----------------------------------------------------------------------------
// Footer
// -----------------------------------------------------------------------------

.footer {
  padding: 4rem 0;
  border-top: 1px solid $theme-border;

  .footer-inner {
    display: grid;
    grid-template-columns: repeat(4, 1fr);
    gap: 3rem;

    @media (max-width: 768px) {
      grid-template-columns: repeat(2, 1fr);
    }

    @media (max-width: 480px) {
      grid-template-columns: 1fr;
    }
  }

  .footer-column-title {
    font-family: $theme-font-mono;
    font-size: 0.75rem;
    font-weight: 600;
    text-transform: uppercase;
    letter-spacing: 0.1em;
    color: $theme-text-muted;
    margin-bottom: 1rem;
  }

  .footer-link {
    display: block;
    font-size: 0.875rem;
    color: $theme-text-muted;
    margin-bottom: 0.5rem;

    &:hover {
      color: $theme-primary;
    }
  }

  .footer-bottom {
    margin-top: 3rem;
    padding-top: 2rem;
    border-top: 1px solid $theme-border;
    font-family: $theme-font-mono;
    font-size: 0.75rem;
    color: $theme-text-muted;
    text-align: center;
  }
}

// -----------------------------------------------------------------------------
// Animations
// -----------------------------------------------------------------------------

@keyframes pulse {
  0%, 100% { opacity: 1; }
  50% { opacity: 0.5; }
}

@keyframes blink {
  0%, 100% { opacity: 1; }
  50% { opacity: 0; }
}

@keyframes glow {
  0%, 100% { box-shadow: 0 0 5px $theme-primary; }
  50% { box-shadow: 0 0 20px $theme-primary, 0 0 30px $theme-primary; }
}

@keyframes typing {
  from { width: 0; }
  to { width: 100%; }
}

.animate-pulse { animation: pulse 2s ease-in-out infinite; }
.animate-blink { animation: blink 1s step-end infinite; }
.animate-glow { animation: glow 2s ease-in-out infinite; }

.cursor-blink::after {
  content: '_';
  animation: blink 1s step-end infinite;
}

// -----------------------------------------------------------------------------
// Utilities
// -----------------------------------------------------------------------------

.text-mono { font-family: $theme-font-mono; }
.text-primary { color: $theme-primary; }
.text-accent { color: $theme-accent; }
.text-glow { text-shadow: $theme-shadow-glow; }

.bg-surface { background-color: $theme-surface; }
.bg-code { background-color: $theme-code-bg; }

.border-glow {
  border-color: $theme-primary;
  box-shadow: $theme-shadow-glow;
}
`.trim();
}

/** Generate CSS variables only */
export function generateTechCSSVariables(darkMode: boolean = true): string {
  const colors = darkMode ? techDarkColors : techLightColors;

  return `
:root {
  /* Colors */
  --color-primary: ${colors.primary};
  --color-secondary: ${colors.secondary};
  --color-accent: #10B981;
  --color-background: ${colors.background};
  --color-surface: ${colors.surface};
  --color-text: ${colors.text};
  --color-text-muted: ${colors.textMuted};
  --color-border: ${colors.border};
  --color-success: ${colors.success};
  --color-warning: ${colors.warning};
  --color-error: ${colors.error};
  --color-code-bg: ${darkMode ? "#0D1117" : "#F4F4F5"};

  /* Typography */
  --font-heading: ${techTypography.headingFont};
  --font-body: ${techTypography.bodyFont};
  --font-mono: 'JetBrains Mono', 'Fira Code', monospace;
  --font-size-base: ${techTypography.baseFontSize};
  --line-height: ${techTypography.lineHeight};
  --heading-weight: ${techTypography.headingWeight};

  /* Spacing */
  --section-padding: ${techSpacing.sectionPadding};
  --container-width: ${techSpacing.containerWidth};
  --gap: ${techSpacing.gap};
  --radius: ${techSpacing.borderRadius};
}
`.trim();
}

/** Get syntax highlighting colors */
export function getSyntaxColors(): Record<string, string> {
  return {
    comment: "#6A737D",
    keyword: "#FF7B72",
    string: "#A5D6FF",
    number: "#79C0FF",
    function: "#D2A8FF",
    variable: "#FFA657",
    operator: "#FF7B72",
    punctuation: "#8B949E",
    property: "#79C0FF",
    class: "#FFA657",
    constant: "#79C0FF",
    boolean: "#FF7B72",
    null: "#FF7B72",
    tag: "#7EE787",
    attribute: "#79C0FF",
  };
}

/** Generate Odoo manifest */
export function generateTechManifest(): Record<string, unknown> {
  return {
    name: techTheme.name,
    summary: techTheme.description,
    description: `
${techTheme.description}

Features:
- Dark backgrounds with high contrast
- Neon accent colors (cyan, purple, green)
- JetBrains Mono typography
- Terminal-inspired aesthetics
- Subtle glow effects
- Sharp, precise design elements
- Light and dark mode support
- Glass-morphism card variants
    `.trim(),
    category: "Theme/Website",
    version: techTheme.version,
    author: techTheme.author,
    website: "https://platxa.com",
    license: "LGPL-3",
    depends: ["website"],
    data: [
      "views/templates.xml",
      "views/snippets.xml",
      "views/options.xml",
    ],
    assets: {
      "web.assets_frontend": [
        "/theme_tech_dark/static/src/scss/theme.scss",
        "/theme_tech_dark/static/src/js/theme.js",
      ],
    },
    images: [techTheme.previewImage],
    application: false,
    installable: true,
    auto_install: false,
  };
}

// =============================================================================
// Exports
// =============================================================================

export default techTheme;
