/**
 * Generate Hooks Command
 *
 * Generates Claude Code hooks in .claude/hooks/ directory that integrate
 * with the debug agent for automated error analysis and pre-commit checks.
 *
 * @module generate-hooks
 */

import { existsSync, mkdirSync, writeFileSync, chmodSync, unlinkSync } from 'node:fs';
import { dirname, join } from 'node:path';

// =============================================================================
// Types
// =============================================================================

export interface GenerateHooksOptions {
  /** Overwrite existing hooks */
  force?: boolean;
  /** Target directory for hooks (default: .claude/hooks/) */
  target?: string;
  /** Hooks to generate */
  hooks?: ('pre-commit' | 'post-error' | 'pre-tool-use' | 'post-tool-use')[];
  /** Include debug agent analyze on errors */
  analyzeErrors?: boolean;
  /** Include pre-commit type checking */
  preCommitTypecheck?: boolean;
  /** Verbose output */
  verbose?: boolean;
}

export interface HookConfig {
  /** Hook name */
  name: string;
  /** Hook file name */
  filename: string;
  /** Hook content */
  content: string;
  /** Hook description */
  description: string;
}

// =============================================================================
// Constants
// =============================================================================

const DEFAULT_HOOKS: Array<'pre-commit' | 'post-error' | 'pre-tool-use' | 'post-tool-use'> = [
  'pre-commit',
  'post-error',
];

// =============================================================================
// Hook Templates
// =============================================================================

function getPreCommitHook(_debugAgentPath: string): HookConfig {
  return {
    name: 'pre-commit',
    filename: 'pre-commit.sh',
    description: 'Runs type checking and linting before commits',
    content: `#!/bin/bash
# Claude Code Pre-Commit Hook
# Generated by platxa-debug-agent
#
# This hook runs before git commits to catch issues early.

set -e

echo "🔍 Running pre-commit checks..."

# Get staged files
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM)

# Check if there are any TypeScript/JavaScript files
TS_FILES=$(echo "$STAGED_FILES" | grep -E '\\.(ts|tsx|js|jsx)$' || true)
PY_FILES=$(echo "$STAGED_FILES" | grep -E '\\.py$' || true)

# TypeScript/JavaScript checks
if [ -n "$TS_FILES" ]; then
  echo "📝 Checking TypeScript/JavaScript files..."

  # Run type checking if tsconfig exists
  if [ -f "tsconfig.json" ]; then
    echo "  → Running type checker..."
    if command -v pnpm &> /dev/null; then
      pnpm exec tsc --noEmit 2>&1 || {
        echo "❌ Type check failed. Run 'pnpm typecheck' to see errors."
        echo "   Use 'platxa-debug analyze' for detailed error analysis."
        exit 1
      }
    elif command -v npx &> /dev/null; then
      npx tsc --noEmit 2>&1 || {
        echo "❌ Type check failed. Run 'npx tsc --noEmit' to see errors."
        exit 1
      }
    fi
    echo "  ✓ Type check passed"
  fi
fi

# Python checks
if [ -n "$PY_FILES" ]; then
  echo "📝 Checking Python files..."

  # Run type checking if pyright/mypy available
  if command -v pyright &> /dev/null; then
    echo "  → Running pyright..."
    pyright $PY_FILES 2>&1 || {
      echo "❌ Type check failed. Run 'pyright' to see errors."
      echo "   Use 'platxa-debug analyze' for detailed error analysis."
      exit 1
    }
    echo "  ✓ Pyright passed"
  fi
fi

# Run debug agent pattern check on staged files if available
if command -v platxa-debug &> /dev/null && [ -n "$STAGED_FILES" ]; then
  echo "🔎 Running pattern analysis on staged files..."
  for file in $STAGED_FILES; do
    if [ -f "$file" ]; then
      platxa-debug patterns --action stats 2>/dev/null || true
    fi
  done
fi

echo "✅ Pre-commit checks passed!"
exit 0
`,
  };
}

function getPostErrorHook(_debugAgentPath: string): HookConfig {
  return {
    name: 'post-error',
    filename: 'post-error.sh',
    description: 'Analyzes errors automatically when they occur',
    content: `#!/bin/bash
# Claude Code Post-Error Hook
# Generated by platxa-debug-agent
#
# This hook is triggered when an error occurs during Claude Code operations.
# It automatically analyzes the error and provides debugging suggestions.

# Error information is passed via environment variables:
# - CLAUDE_ERROR_MESSAGE: The error message
# - CLAUDE_ERROR_CODE: Exit code (if applicable)
# - CLAUDE_ERROR_COMMAND: Command that failed (if applicable)
# - CLAUDE_ERROR_FILE: File where error occurred (if applicable)

set -e

# Only run if we have an error message
if [ -z "$CLAUDE_ERROR_MESSAGE" ]; then
  exit 0
fi

echo ""
echo "🔍 Analyzing error with platxa-debug-agent..."
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

# Run debug agent analysis
if command -v platxa-debug &> /dev/null; then
  # Analyze the error
  platxa-debug analyze "$CLAUDE_ERROR_MESSAGE" --output text 2>&1 || true

  echo ""
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo "💡 For more detailed analysis, run:"
  echo '   platxa-debug rca "$CLAUDE_ERROR_MESSAGE"'
  echo ""
  echo "🔧 For fix suggestions, run:"
  echo '   platxa-debug suggest "$CLAUDE_ERROR_MESSAGE"'
else
  echo "⚠️  platxa-debug not found in PATH"
  echo "   Install with: npm install -g platxa-debug-agent"
fi

exit 0
`,
  };
}

function getPreToolUseHook(): HookConfig {
  return {
    name: 'pre-tool-use',
    filename: 'pre-tool-use.sh',
    description: 'Validates tool calls before execution',
    content: `#!/bin/bash
# Claude Code Pre-Tool-Use Hook
# Generated by platxa-debug-agent
#
# This hook runs before Claude executes a tool.
# Tool information is passed via environment variables:
# - CLAUDE_TOOL_NAME: Name of the tool being called
# - CLAUDE_TOOL_ARGS: JSON-encoded arguments

# Example: Log all tool calls
# echo "[$(date +%H:%M:%S)] Tool: $CLAUDE_TOOL_NAME" >> ~/.claude/tool-calls.log

# Allow all tool calls by default
exit 0
`,
  };
}

function getPostToolUseHook(): HookConfig {
  return {
    name: 'post-tool-use',
    filename: 'post-tool-use.sh',
    description: 'Processes tool results after execution',
    content: `#!/bin/bash
# Claude Code Post-Tool-Use Hook
# Generated by platxa-debug-agent
#
# This hook runs after Claude executes a tool.
# Tool information is passed via environment variables:
# - CLAUDE_TOOL_NAME: Name of the tool that was called
# - CLAUDE_TOOL_RESULT: Tool execution result
# - CLAUDE_TOOL_SUCCESS: "true" or "false"

# Analyze failed Bash commands automatically
if [ "$CLAUDE_TOOL_NAME" = "Bash" ] && [ "$CLAUDE_TOOL_SUCCESS" = "false" ]; then
  if command -v platxa-debug &> /dev/null; then
    echo "🔍 Analyzing command failure..."
    platxa-debug analyze "$CLAUDE_TOOL_RESULT" --output text 2>&1 || true
  fi
fi

exit 0
`,
  };
}

// =============================================================================
// Hook Generator
// =============================================================================

/**
 * Generate Claude Code hooks for debug agent integration
 */
export async function generateHooksCommand(
  options: Record<string, unknown>
): Promise<void> {
  const opts = options as GenerateHooksOptions;
  const targetDir = opts.target ?? join(process.cwd(), '.claude', 'hooks');
  const hooksToGenerate = opts.hooks ?? DEFAULT_HOOKS;
  const verbose = opts.verbose ?? false;

  console.log('\n=== Claude Code Hook Generator ===\n');

  // Create hooks directory
  if (!existsSync(targetDir)) {
    mkdirSync(targetDir, { recursive: true });
    if (verbose) {
      console.log(`Created directory: ${targetDir}`);
    }
  }

  // Determine debug agent path (relative to hooks directory)
  const debugAgentPath = 'platxa-debug';

  // Generate requested hooks
  const generatedHooks: string[] = [];
  const skippedHooks: string[] = [];

  for (const hookType of hooksToGenerate) {
    const hook = getHookConfig(hookType, debugAgentPath);
    const hookPath = join(targetDir, hook.filename);

    // Check if hook exists
    if (existsSync(hookPath) && !opts.force) {
      skippedHooks.push(hook.name);
      if (verbose) {
        console.log(`⏭️  Skipped ${hook.name} (already exists, use --force to overwrite)`);
      }
      continue;
    }

    // Write hook file
    writeFileSync(hookPath, hook.content, { encoding: 'utf-8' });

    // Make hook executable
    chmodSync(hookPath, 0o755);

    generatedHooks.push(hook.name);
    if (verbose) {
      console.log(`✅ Generated ${hook.name}: ${hookPath}`);
      console.log(`   ${hook.description}`);
    }
  }

  // Create settings.json to enable hooks
  const settingsPath = join(dirname(targetDir), 'settings.json');
  if (!existsSync(settingsPath)) {
    const settings = {
      hooks: {
        enabled: true,
        preCommit: hooksToGenerate.includes('pre-commit'),
        postError: hooksToGenerate.includes('post-error'),
        preToolUse: hooksToGenerate.includes('pre-tool-use'),
        postToolUse: hooksToGenerate.includes('post-tool-use'),
      },
    };
    writeFileSync(settingsPath, JSON.stringify(settings, null, 2));
    if (verbose) {
      console.log(`\n📝 Created ${settingsPath}`);
    }
  }

  // Summary
  console.log('Hooks Directory:', targetDir);
  console.log('');

  if (generatedHooks.length > 0) {
    console.log('Generated hooks:');
    for (const hook of generatedHooks) {
      const config = getHookConfig(hook as 'pre-commit' | 'post-error' | 'pre-tool-use' | 'post-tool-use', debugAgentPath);
      console.log(`  ✅ ${hook}`);
      console.log(`     ${config.description}`);
    }
  }

  if (skippedHooks.length > 0) {
    console.log('\nSkipped (already exist):');
    for (const hook of skippedHooks) {
      console.log(`  ⏭️  ${hook}`);
    }
    console.log('\nUse --force to overwrite existing hooks.');
  }

  console.log('\n📖 Usage:');
  console.log('   The hooks will be automatically called by Claude Code.');
  console.log('   pre-commit: Runs before git commit operations');
  console.log('   post-error: Analyzes errors when they occur');
  console.log('');
  console.log('🔧 To customize hooks, edit the files in:');
  console.log(`   ${targetDir}`);
}

/**
 * Get hook configuration by type
 */
function getHookConfig(
  hookType: 'pre-commit' | 'post-error' | 'pre-tool-use' | 'post-tool-use',
  debugAgentPath: string
): HookConfig {
  switch (hookType) {
    case 'pre-commit':
      return getPreCommitHook(debugAgentPath);
    case 'post-error':
      return getPostErrorHook(debugAgentPath);
    case 'pre-tool-use':
      return getPreToolUseHook();
    case 'post-tool-use':
      return getPostToolUseHook();
  }
}

// =============================================================================
// Utility Functions
// =============================================================================

/**
 * Check if hooks are installed
 */
export function checkHooksInstalled(targetDir?: string): {
  installed: boolean;
  hooks: string[];
  path: string;
} {
  const hooksDir = targetDir ?? join(process.cwd(), '.claude', 'hooks');
  const hooks: string[] = [];

  if (existsSync(join(hooksDir, 'pre-commit.sh'))) {
    hooks.push('pre-commit');
  }
  if (existsSync(join(hooksDir, 'post-error.sh'))) {
    hooks.push('post-error');
  }
  if (existsSync(join(hooksDir, 'pre-tool-use.sh'))) {
    hooks.push('pre-tool-use');
  }
  if (existsSync(join(hooksDir, 'post-tool-use.sh'))) {
    hooks.push('post-tool-use');
  }

  return {
    installed: hooks.length > 0,
    hooks,
    path: hooksDir,
  };
}

/**
 * Remove installed hooks
 */
export function removeHooks(targetDir?: string): void {
  const hooksDir = targetDir ?? join(process.cwd(), '.claude', 'hooks');

  const hookFiles = [
    'pre-commit.sh',
    'post-error.sh',
    'pre-tool-use.sh',
    'post-tool-use.sh',
  ];

  for (const file of hookFiles) {
    const hookPath = join(hooksDir, file);
    if (existsSync(hookPath)) {
      unlinkSync(hookPath);
    }
  }
}
